workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    LucidLayer API:
        inputs:
            - location: ../openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/raijin-labs-gc4/lucid/lucid-layer-api
targets:
    raijinlabs-mcp:
        target: mcp-typescript
        source: LucidLayer API
