/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Executors = {
  n8n?: boolean | undefined;
  langgraph?: boolean | undefined;
};

/**
 * OK
 */
export type CheckExecutorHealthResponse = {
  success: boolean;
  executors: Executors;
  message?: string | undefined;
};

/** @internal */
export const Executors$inboundSchema: z.ZodMiniType<Executors, unknown> = z
  .object({
    n8n: types.optional(types.boolean()),
    langgraph: types.optional(types.boolean()),
  });

export function executorsFromJSON(
  jsonString: string,
): SafeParseResult<Executors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Executors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Executors' from JSON`,
  );
}

/** @internal */
export const CheckExecutorHealthResponse$inboundSchema: z.ZodMiniType<
  CheckExecutorHealthResponse,
  unknown
> = z.object({
  success: types.boolean(),
  executors: z.lazy(() => Executors$inboundSchema),
  message: types.optional(types.string()),
});

export function checkExecutorHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckExecutorHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckExecutorHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckExecutorHealthResponse' from JSON`,
  );
}
