/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Context = {
  tenantId: string;
  variables?: { [k: string]: any } | undefined;
};

export const Executor = {
  N8n: "n8n",
  Langgraph: "langgraph",
} as const;
export type Executor = ClosedEnum<typeof Executor>;

export type ExecuteAgentFlowspecRequest = {
  flowspec: { [k: string]: any };
  context: Context;
  executor?: Executor | undefined;
};

/**
 * OK
 */
export type ExecuteAgentFlowspecResponse = {
  success: boolean;
  result?: { [k: string]: any } | undefined;
};

/** @internal */
export type Context$Outbound = {
  tenantId: string;
  variables?: { [k: string]: any } | undefined;
};

/** @internal */
export const Context$outboundSchema: z.ZodMiniType<Context$Outbound, Context> =
  z.object({
    tenantId: z.string(),
    variables: z.optional(z.record(z.string(), z.any())),
  });

export function contextToJSON(context: Context): string {
  return JSON.stringify(Context$outboundSchema.parse(context));
}

/** @internal */
export const Executor$outboundSchema: z.ZodMiniEnum<typeof Executor> = z.enum(
  Executor,
);

/** @internal */
export type ExecuteAgentFlowspecRequest$Outbound = {
  flowspec: { [k: string]: any };
  context: Context$Outbound;
  executor?: string | undefined;
};

/** @internal */
export const ExecuteAgentFlowspecRequest$outboundSchema: z.ZodMiniType<
  ExecuteAgentFlowspecRequest$Outbound,
  ExecuteAgentFlowspecRequest
> = z.object({
  flowspec: z.record(z.string(), z.any()),
  context: z.lazy(() => Context$outboundSchema),
  executor: z.optional(Executor$outboundSchema),
});

export function executeAgentFlowspecRequestToJSON(
  executeAgentFlowspecRequest: ExecuteAgentFlowspecRequest,
): string {
  return JSON.stringify(
    ExecuteAgentFlowspecRequest$outboundSchema.parse(
      executeAgentFlowspecRequest,
    ),
  );
}

/** @internal */
export const ExecuteAgentFlowspecResponse$inboundSchema: z.ZodMiniType<
  ExecuteAgentFlowspecResponse,
  unknown
> = z.object({
  success: types.boolean(),
  result: types.optional(z.record(z.string(), z.any())),
});

export function executeAgentFlowspecResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteAgentFlowspecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteAgentFlowspecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteAgentFlowspecResponse' from JSON`,
  );
}
