/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAgentOrchestratorHistoryRequest = {
  tenantId: string;
  limit?: number | undefined;
};

/**
 * OK
 */
export type GetAgentOrchestratorHistoryResponse = {
  success: boolean;
  tenantId: string;
  history: Array<{ [k: string]: any }>;
  stats?: { [k: string]: any } | undefined;
  message?: string | undefined;
};

/** @internal */
export type GetAgentOrchestratorHistoryRequest$Outbound = {
  tenantId: string;
  limit?: number | undefined;
};

/** @internal */
export const GetAgentOrchestratorHistoryRequest$outboundSchema: z.ZodMiniType<
  GetAgentOrchestratorHistoryRequest$Outbound,
  GetAgentOrchestratorHistoryRequest
> = z.object({
  tenantId: z.string(),
  limit: z.optional(z.int()),
});

export function getAgentOrchestratorHistoryRequestToJSON(
  getAgentOrchestratorHistoryRequest: GetAgentOrchestratorHistoryRequest,
): string {
  return JSON.stringify(
    GetAgentOrchestratorHistoryRequest$outboundSchema.parse(
      getAgentOrchestratorHistoryRequest,
    ),
  );
}

/** @internal */
export const GetAgentOrchestratorHistoryResponse$inboundSchema: z.ZodMiniType<
  GetAgentOrchestratorHistoryResponse,
  unknown
> = z.object({
  success: types.boolean(),
  tenantId: types.string(),
  history: z.array(z.record(z.string(), z.any())),
  stats: types.optional(z.record(z.string(), z.any())),
  message: types.optional(types.string()),
});

export function getAgentOrchestratorHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAgentOrchestratorHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAgentOrchestratorHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAgentOrchestratorHistoryResponse' from JSON`,
  );
}
