/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type GetPlannerInfoResponse = {
  success: boolean;
  status: string;
  info?: { [k: string]: any } | undefined;
  message?: string | undefined;
};

/** @internal */
export const GetPlannerInfoResponse$inboundSchema: z.ZodMiniType<
  GetPlannerInfoResponse,
  unknown
> = z.object({
  success: types.boolean(),
  status: types.string(),
  info: types.optional(z.record(z.string(), z.any())),
  message: types.optional(types.string()),
});

export function getPlannerInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlannerInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlannerInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlannerInfoResponse' from JSON`,
  );
}
