/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type LucidLaunchShareTokenRequest = {
  /**
   * Passport identifier to launch share token for
   */
  passportId: string;
  body: models.TokenLaunchRequest;
};

/** @internal */
export type LucidLaunchShareTokenRequest$Outbound = {
  passport_id: string;
  body: models.TokenLaunchRequest$Outbound;
};

/** @internal */
export const LucidLaunchShareTokenRequest$outboundSchema: z.ZodMiniType<
  LucidLaunchShareTokenRequest$Outbound,
  LucidLaunchShareTokenRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    body: models.TokenLaunchRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function lucidLaunchShareTokenRequestToJSON(
  lucidLaunchShareTokenRequest: LucidLaunchShareTokenRequest,
): string {
  return JSON.stringify(
    LucidLaunchShareTokenRequest$outboundSchema.parse(
      lucidLaunchShareTokenRequest,
    ),
  );
}
