/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidGetAnchoringHealthResponse = {
  success: boolean;
  connected: boolean;
  network?: string | undefined;
  authority?: string | undefined;
  mockMode?: boolean | undefined;
  error?: string | undefined;
};

/** @internal */
export const LucidGetAnchoringHealthResponse$inboundSchema: z.ZodMiniType<
  LucidGetAnchoringHealthResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    connected: types.boolean(),
    network: types.optional(types.string()),
    authority: types.optional(types.string()),
    mock_mode: types.optional(types.boolean()),
    error: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mock_mode": "mockMode",
    });
  }),
);

export function lucidGetAnchoringHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAnchoringHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetAnchoringHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAnchoringHealthResponse' from JSON`,
  );
}
