/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidSubmitReputationOnChainRequestBody = {
  /**
   * Target chain for on-chain submission
   */
  chainId: string;
};

export type LucidSubmitReputationOnChainRequest = {
  /**
   * Agent identifier for on-chain reputation submission
   */
  agentId: string;
  body: LucidSubmitReputationOnChainRequestBody;
};

/**
 * Submission result
 */
export type LucidSubmitReputationOnChainResponse = {
  success: boolean;
  txHash?: string | undefined;
  score?: number | undefined;
  error?: string | undefined;
};

/** @internal */
export type LucidSubmitReputationOnChainRequestBody$Outbound = {
  chainId: string;
};

/** @internal */
export const LucidSubmitReputationOnChainRequestBody$outboundSchema:
  z.ZodMiniType<
    LucidSubmitReputationOnChainRequestBody$Outbound,
    LucidSubmitReputationOnChainRequestBody
  > = z.object({
    chainId: z.string(),
  });

export function lucidSubmitReputationOnChainRequestBodyToJSON(
  lucidSubmitReputationOnChainRequestBody:
    LucidSubmitReputationOnChainRequestBody,
): string {
  return JSON.stringify(
    LucidSubmitReputationOnChainRequestBody$outboundSchema.parse(
      lucidSubmitReputationOnChainRequestBody,
    ),
  );
}

/** @internal */
export type LucidSubmitReputationOnChainRequest$Outbound = {
  agentId: string;
  body: LucidSubmitReputationOnChainRequestBody$Outbound;
};

/** @internal */
export const LucidSubmitReputationOnChainRequest$outboundSchema: z.ZodMiniType<
  LucidSubmitReputationOnChainRequest$Outbound,
  LucidSubmitReputationOnChainRequest
> = z.object({
  agentId: z.string(),
  body: z.lazy(() => LucidSubmitReputationOnChainRequestBody$outboundSchema),
});

export function lucidSubmitReputationOnChainRequestToJSON(
  lucidSubmitReputationOnChainRequest: LucidSubmitReputationOnChainRequest,
): string {
  return JSON.stringify(
    LucidSubmitReputationOnChainRequest$outboundSchema.parse(
      lucidSubmitReputationOnChainRequest,
    ),
  );
}

/** @internal */
export const LucidSubmitReputationOnChainResponse$inboundSchema: z.ZodMiniType<
  LucidSubmitReputationOnChainResponse,
  unknown
> = z.object({
  success: types.boolean(),
  txHash: types.optional(types.string()),
  score: types.optional(types.number()),
  error: types.optional(types.string()),
});

export function lucidSubmitReputationOnChainResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidSubmitReputationOnChainResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LucidSubmitReputationOnChainResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidSubmitReputationOnChainResponse' from JSON`,
  );
}
