/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidAgentWalletSendRequest = {
  /**
   * Agent passport identifier for wallet send
   */
  agentId: string;
  body: models.AgentWalletSendRequest;
};

/**
 * Transaction executed
 */
export type LucidAgentWalletSendResponse = {
  success: boolean;
  transaction: { [k: string]: any };
};

/** @internal */
export type LucidAgentWalletSendRequest$Outbound = {
  agentId: string;
  body: models.AgentWalletSendRequest$Outbound;
};

/** @internal */
export const LucidAgentWalletSendRequest$outboundSchema: z.ZodMiniType<
  LucidAgentWalletSendRequest$Outbound,
  LucidAgentWalletSendRequest
> = z.object({
  agentId: z.string(),
  body: models.AgentWalletSendRequest$outboundSchema,
});

export function lucidAgentWalletSendRequestToJSON(
  lucidAgentWalletSendRequest: LucidAgentWalletSendRequest,
): string {
  return JSON.stringify(
    LucidAgentWalletSendRequest$outboundSchema.parse(
      lucidAgentWalletSendRequest,
    ),
  );
}

/** @internal */
export const LucidAgentWalletSendResponse$inboundSchema: z.ZodMiniType<
  LucidAgentWalletSendResponse,
  unknown
> = z.object({
  success: types.boolean(),
  transaction: z.record(z.string(), z.any()),
});

export function lucidAgentWalletSendResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidAgentWalletSendResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidAgentWalletSendResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidAgentWalletSendResponse' from JSON`,
  );
}
