/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidRouteRequest = {
  modelMeta?: { [k: string]: any } | undefined;
  policy?: models.Policy | undefined;
  computeCatalog?: Array<{ [k: string]: any }> | undefined;
  requestId?: string | undefined;
  requireLiveHealthy?: boolean | undefined;
};

export type Route = {
  computePassportId?: string | undefined;
  modelPassportId?: string | undefined;
  endpoint?: string | undefined;
  runtime?: string | undefined;
  policyHash?: string | undefined;
  fallbacks?: Array<{ [k: string]: any }> | undefined;
};

/**
 * OK
 */
export type LucidRouteResponse = {
  success: boolean;
  requestId?: string | undefined;
  route: Route;
  explain: { [k: string]: any };
};

/** @internal */
export type LucidRouteRequest$Outbound = {
  model_meta?: { [k: string]: any } | undefined;
  policy?: models.Policy$Outbound | undefined;
  compute_catalog?: Array<{ [k: string]: any }> | undefined;
  request_id?: string | undefined;
  require_live_healthy: boolean;
};

/** @internal */
export const LucidRouteRequest$outboundSchema: z.ZodMiniType<
  LucidRouteRequest$Outbound,
  LucidRouteRequest
> = z.pipe(
  z.object({
    modelMeta: z.optional(z.record(z.string(), z.any())),
    policy: z.optional(models.Policy$outboundSchema),
    computeCatalog: z.optional(z.array(z.record(z.string(), z.any()))),
    requestId: z.optional(z.string()),
    requireLiveHealthy: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelMeta: "model_meta",
      computeCatalog: "compute_catalog",
      requestId: "request_id",
      requireLiveHealthy: "require_live_healthy",
    });
  }),
);

export function lucidRouteRequestToJSON(
  lucidRouteRequest: LucidRouteRequest,
): string {
  return JSON.stringify(
    LucidRouteRequest$outboundSchema.parse(lucidRouteRequest),
  );
}

/** @internal */
export const Route$inboundSchema: z.ZodMiniType<Route, unknown> = z.pipe(
  z.object({
    compute_passport_id: types.optional(types.string()),
    model_passport_id: types.optional(types.string()),
    endpoint: types.optional(types.string()),
    runtime: types.optional(types.string()),
    policy_hash: types.optional(types.string()),
    fallbacks: types.optional(z.array(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "compute_passport_id": "computePassportId",
      "model_passport_id": "modelPassportId",
      "policy_hash": "policyHash",
    });
  }),
);

export function routeFromJSON(
  jsonString: string,
): SafeParseResult<Route, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Route$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Route' from JSON`,
  );
}

/** @internal */
export const LucidRouteResponse$inboundSchema: z.ZodMiniType<
  LucidRouteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    request_id: types.optional(types.string()),
    route: z.lazy(() => Route$inboundSchema),
    explain: z.record(z.string(), z.any()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function lucidRouteResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidRouteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidRouteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidRouteResponse' from JSON`,
  );
}
