/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidWithdrawAssetRevenueRequestBody = {
  token?: string | undefined;
};

export type LucidWithdrawAssetRevenueRequest = {
  /**
   * AI asset passport identifier to withdraw revenue from
   */
  passportId: string;
  body?: LucidWithdrawAssetRevenueRequestBody | undefined;
};

export const LucidWithdrawAssetRevenueStatus = {
  PendingPayout: "pending_payout",
  NoFunds: "no_funds",
} as const;
export type LucidWithdrawAssetRevenueStatus = OpenEnum<
  typeof LucidWithdrawAssetRevenueStatus
>;

export type Withdrawal = {
  /**
   * Amount in micro-units
   */
  amount: string;
  token: string;
  status: LucidWithdrawAssetRevenueStatus;
};

/**
 * Withdrawal queued
 */
export type LucidWithdrawAssetRevenueResponse = {
  success: boolean;
  withdrawal: Withdrawal;
};

/** @internal */
export type LucidWithdrawAssetRevenueRequestBody$Outbound = {
  token: string;
};

/** @internal */
export const LucidWithdrawAssetRevenueRequestBody$outboundSchema: z.ZodMiniType<
  LucidWithdrawAssetRevenueRequestBody$Outbound,
  LucidWithdrawAssetRevenueRequestBody
> = z.object({
  token: z._default(z.string(), "USDC"),
});

export function lucidWithdrawAssetRevenueRequestBodyToJSON(
  lucidWithdrawAssetRevenueRequestBody: LucidWithdrawAssetRevenueRequestBody,
): string {
  return JSON.stringify(
    LucidWithdrawAssetRevenueRequestBody$outboundSchema.parse(
      lucidWithdrawAssetRevenueRequestBody,
    ),
  );
}

/** @internal */
export type LucidWithdrawAssetRevenueRequest$Outbound = {
  passport_id: string;
  body?: LucidWithdrawAssetRevenueRequestBody$Outbound | undefined;
};

/** @internal */
export const LucidWithdrawAssetRevenueRequest$outboundSchema: z.ZodMiniType<
  LucidWithdrawAssetRevenueRequest$Outbound,
  LucidWithdrawAssetRevenueRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    body: z.optional(
      z.lazy(() => LucidWithdrawAssetRevenueRequestBody$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function lucidWithdrawAssetRevenueRequestToJSON(
  lucidWithdrawAssetRevenueRequest: LucidWithdrawAssetRevenueRequest,
): string {
  return JSON.stringify(
    LucidWithdrawAssetRevenueRequest$outboundSchema.parse(
      lucidWithdrawAssetRevenueRequest,
    ),
  );
}

/** @internal */
export const LucidWithdrawAssetRevenueStatus$inboundSchema: z.ZodMiniType<
  LucidWithdrawAssetRevenueStatus,
  unknown
> = openEnums.inboundSchema(LucidWithdrawAssetRevenueStatus);

/** @internal */
export const Withdrawal$inboundSchema: z.ZodMiniType<Withdrawal, unknown> = z
  .object({
    amount: types.string(),
    token: types.string(),
    status: LucidWithdrawAssetRevenueStatus$inboundSchema,
  });

export function withdrawalFromJSON(
  jsonString: string,
): SafeParseResult<Withdrawal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Withdrawal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Withdrawal' from JSON`,
  );
}

/** @internal */
export const LucidWithdrawAssetRevenueResponse$inboundSchema: z.ZodMiniType<
  LucidWithdrawAssetRevenueResponse,
  unknown
> = z.object({
  success: types.boolean(),
  withdrawal: z.lazy(() => Withdrawal$inboundSchema),
});

export function lucidWithdrawAssetRevenueResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidWithdrawAssetRevenueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidWithdrawAssetRevenueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidWithdrawAssetRevenueResponse' from JSON`,
  );
}
