/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidVerifyAgentMmrRequest = {
  /**
   * Legacy agent identifier
   */
  agentId: string;
};

/**
 * OK
 */
export type LucidVerifyAgentMmrResponse = {
  success: boolean;
  agentId: string;
  verification: { [k: string]: any };
  message?: string | undefined;
};

/** @internal */
export type LucidVerifyAgentMmrRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidVerifyAgentMmrRequest$outboundSchema: z.ZodMiniType<
  LucidVerifyAgentMmrRequest$Outbound,
  LucidVerifyAgentMmrRequest
> = z.object({
  agentId: z.string(),
});

export function lucidVerifyAgentMmrRequestToJSON(
  lucidVerifyAgentMmrRequest: LucidVerifyAgentMmrRequest,
): string {
  return JSON.stringify(
    LucidVerifyAgentMmrRequest$outboundSchema.parse(lucidVerifyAgentMmrRequest),
  );
}

/** @internal */
export const LucidVerifyAgentMmrResponse$inboundSchema: z.ZodMiniType<
  LucidVerifyAgentMmrResponse,
  unknown
> = z.object({
  success: types.boolean(),
  agentId: types.string(),
  verification: z.record(z.string(), z.any()),
  message: types.optional(types.string()),
});

export function lucidVerifyAgentMmrResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidVerifyAgentMmrResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidVerifyAgentMmrResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidVerifyAgentMmrResponse' from JSON`,
  );
}
