/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type LucidSendA2aTaskRequest = {
  /**
   * Agent passport identifier to send task to
   */
  passportId: string;
  body: models.A2ASendTaskRequest;
};

/** @internal */
export type LucidSendA2aTaskRequest$Outbound = {
  passportId: string;
  body: models.A2ASendTaskRequest$Outbound;
};

/** @internal */
export const LucidSendA2aTaskRequest$outboundSchema: z.ZodMiniType<
  LucidSendA2aTaskRequest$Outbound,
  LucidSendA2aTaskRequest
> = z.object({
  passportId: z.string(),
  body: models.A2ASendTaskRequest$outboundSchema,
});

export function lucidSendA2aTaskRequestToJSON(
  lucidSendA2aTaskRequest: LucidSendA2aTaskRequest,
): string {
  return JSON.stringify(
    LucidSendA2aTaskRequest$outboundSchema.parse(lucidSendA2aTaskRequest),
  );
}
