/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetAgentDeployStatusRequest = {
  /**
   * Agent passport identifier
   */
  passportId: string;
};

/**
 * OK
 */
export type LucidGetAgentDeployStatusResponse = {
  success: boolean;
  status: { [k: string]: any };
};

/** @internal */
export type LucidGetAgentDeployStatusRequest$Outbound = {
  passportId: string;
};

/** @internal */
export const LucidGetAgentDeployStatusRequest$outboundSchema: z.ZodMiniType<
  LucidGetAgentDeployStatusRequest$Outbound,
  LucidGetAgentDeployStatusRequest
> = z.object({
  passportId: z.string(),
});

export function lucidGetAgentDeployStatusRequestToJSON(
  lucidGetAgentDeployStatusRequest: LucidGetAgentDeployStatusRequest,
): string {
  return JSON.stringify(
    LucidGetAgentDeployStatusRequest$outboundSchema.parse(
      lucidGetAgentDeployStatusRequest,
    ),
  );
}

/** @internal */
export const LucidGetAgentDeployStatusResponse$inboundSchema: z.ZodMiniType<
  LucidGetAgentDeployStatusResponse,
  unknown
> = z.object({
  success: types.boolean(),
  status: z.record(z.string(), z.any()),
});

export function lucidGetAgentDeployStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAgentDeployStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetAgentDeployStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAgentDeployStatusResponse' from JSON`,
  );
}
