/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidTriggerAgentAirdropRequest = {
  /**
   * Agent passport identifier for revenue airdrop
   */
  agentId: string;
};

export type Airdrop = {
  distributedLamports?: string | undefined;
  holderCount?: number | undefined;
};

/**
 * Airdrop executed
 */
export type LucidTriggerAgentAirdropResponse = {
  success: boolean;
  airdrop: Airdrop;
};

/** @internal */
export type LucidTriggerAgentAirdropRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidTriggerAgentAirdropRequest$outboundSchema: z.ZodMiniType<
  LucidTriggerAgentAirdropRequest$Outbound,
  LucidTriggerAgentAirdropRequest
> = z.object({
  agentId: z.string(),
});

export function lucidTriggerAgentAirdropRequestToJSON(
  lucidTriggerAgentAirdropRequest: LucidTriggerAgentAirdropRequest,
): string {
  return JSON.stringify(
    LucidTriggerAgentAirdropRequest$outboundSchema.parse(
      lucidTriggerAgentAirdropRequest,
    ),
  );
}

/** @internal */
export const Airdrop$inboundSchema: z.ZodMiniType<Airdrop, unknown> = z.pipe(
  z.object({
    distributed_lamports: types.optional(types.string()),
    holder_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "distributed_lamports": "distributedLamports",
      "holder_count": "holderCount",
    });
  }),
);

export function airdropFromJSON(
  jsonString: string,
): SafeParseResult<Airdrop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Airdrop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Airdrop' from JSON`,
  );
}

/** @internal */
export const LucidTriggerAgentAirdropResponse$inboundSchema: z.ZodMiniType<
  LucidTriggerAgentAirdropResponse,
  unknown
> = z.object({
  success: types.boolean(),
  airdrop: z.lazy(() => Airdrop$inboundSchema),
});

export function lucidTriggerAgentAirdropResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidTriggerAgentAirdropResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidTriggerAgentAirdropResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidTriggerAgentAirdropResponse' from JSON`,
  );
}
