/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetHealthRequest = {
  computePassportId: string;
};

/**
 * OK
 */
export type LucidGetHealthResponse = {
  success?: boolean | undefined;
  state?: { [k: string]: any } | undefined;
};

/** @internal */
export type LucidGetHealthRequest$Outbound = {
  computePassportId: string;
};

/** @internal */
export const LucidGetHealthRequest$outboundSchema: z.ZodMiniType<
  LucidGetHealthRequest$Outbound,
  LucidGetHealthRequest
> = z.object({
  computePassportId: z.string(),
});

export function lucidGetHealthRequestToJSON(
  lucidGetHealthRequest: LucidGetHealthRequest,
): string {
  return JSON.stringify(
    LucidGetHealthRequest$outboundSchema.parse(lucidGetHealthRequest),
  );
}

/** @internal */
export const LucidGetHealthResponse$inboundSchema: z.ZodMiniType<
  LucidGetHealthResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  state: types.optional(z.record(z.string(), z.any())),
});

export function lucidGetHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetHealthResponse' from JSON`,
  );
}
