/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidGetEscrowRequest = {
  /**
   * Blockchain chain identifier (e.g. base, solana-devnet)
   */
  chainId: string;
  /**
   * Escrow identifier on the specified chain
   */
  escrowId: string;
};

/** @internal */
export type LucidGetEscrowRequest$Outbound = {
  chainId: string;
  escrowId: string;
};

/** @internal */
export const LucidGetEscrowRequest$outboundSchema: z.ZodMiniType<
  LucidGetEscrowRequest$Outbound,
  LucidGetEscrowRequest
> = z.object({
  chainId: z.string(),
  escrowId: z.string(),
});

export function lucidGetEscrowRequestToJSON(
  lucidGetEscrowRequest: LucidGetEscrowRequest,
): string {
  return JSON.stringify(
    LucidGetEscrowRequest$outboundSchema.parse(lucidGetEscrowRequest),
  );
}
