/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidHeartbeatResponse = {
  success?: boolean | undefined;
  state?: { [k: string]: any } | undefined;
};

/** @internal */
export const LucidHeartbeatResponse$inboundSchema: z.ZodMiniType<
  LucidHeartbeatResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  state: types.optional(z.record(z.string(), z.any())),
});

export function lucidHeartbeatResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidHeartbeatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidHeartbeatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidHeartbeatResponse' from JSON`,
  );
}
