/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetAgentWalletBalanceRequest = {
  /**
   * Agent passport identifier for wallet balance
   */
  agentId: string;
};

/**
 * OK
 */
export type LucidGetAgentWalletBalanceResponse = {
  success: boolean;
  balance: { [k: string]: any };
};

/** @internal */
export type LucidGetAgentWalletBalanceRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidGetAgentWalletBalanceRequest$outboundSchema: z.ZodMiniType<
  LucidGetAgentWalletBalanceRequest$Outbound,
  LucidGetAgentWalletBalanceRequest
> = z.object({
  agentId: z.string(),
});

export function lucidGetAgentWalletBalanceRequestToJSON(
  lucidGetAgentWalletBalanceRequest: LucidGetAgentWalletBalanceRequest,
): string {
  return JSON.stringify(
    LucidGetAgentWalletBalanceRequest$outboundSchema.parse(
      lucidGetAgentWalletBalanceRequest,
    ),
  );
}

/** @internal */
export const LucidGetAgentWalletBalanceResponse$inboundSchema: z.ZodMiniType<
  LucidGetAgentWalletBalanceResponse,
  unknown
> = z.object({
  success: types.boolean(),
  balance: z.record(z.string(), z.any()),
});

export function lucidGetAgentWalletBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAgentWalletBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LucidGetAgentWalletBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAgentWalletBalanceResponse' from JSON`,
  );
}
