/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidResolveDisputeRequestBody = {
  chainId: string;
};

export type LucidResolveDisputeRequest = {
  /**
   * Dispute identifier to resolve
   */
  disputeId: string;
  body: LucidResolveDisputeRequestBody;
};

/** @internal */
export type LucidResolveDisputeRequestBody$Outbound = {
  chainId: string;
};

/** @internal */
export const LucidResolveDisputeRequestBody$outboundSchema: z.ZodMiniType<
  LucidResolveDisputeRequestBody$Outbound,
  LucidResolveDisputeRequestBody
> = z.object({
  chainId: z.string(),
});

export function lucidResolveDisputeRequestBodyToJSON(
  lucidResolveDisputeRequestBody: LucidResolveDisputeRequestBody,
): string {
  return JSON.stringify(
    LucidResolveDisputeRequestBody$outboundSchema.parse(
      lucidResolveDisputeRequestBody,
    ),
  );
}

/** @internal */
export type LucidResolveDisputeRequest$Outbound = {
  disputeId: string;
  body: LucidResolveDisputeRequestBody$Outbound;
};

/** @internal */
export const LucidResolveDisputeRequest$outboundSchema: z.ZodMiniType<
  LucidResolveDisputeRequest$Outbound,
  LucidResolveDisputeRequest
> = z.object({
  disputeId: z.string(),
  body: z.lazy(() => LucidResolveDisputeRequestBody$outboundSchema),
});

export function lucidResolveDisputeRequestToJSON(
  lucidResolveDisputeRequest: LucidResolveDisputeRequest,
): string {
  return JSON.stringify(
    LucidResolveDisputeRequest$outboundSchema.parse(lucidResolveDisputeRequest),
  );
}
