/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidGetIdentityRequest = {
  /**
   * CAIP-10 address to resolve (e.g. eip155:8453:0x1234...)
   */
  caip10: string;
};

/** @internal */
export type LucidGetIdentityRequest$Outbound = {
  caip10: string;
};

/** @internal */
export const LucidGetIdentityRequest$outboundSchema: z.ZodMiniType<
  LucidGetIdentityRequest$Outbound,
  LucidGetIdentityRequest
> = z.object({
  caip10: z.string(),
});

export function lucidGetIdentityRequestToJSON(
  lucidGetIdentityRequest: LucidGetIdentityRequest,
): string {
  return JSON.stringify(
    LucidGetIdentityRequest$outboundSchema.parse(lucidGetIdentityRequest),
  );
}
