/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Alive
 */
export type LucidCheckLivenessResponse = {
  status: string;
  timestamp: Date;
  uptime: number;
};

/** @internal */
export const LucidCheckLivenessResponse$inboundSchema: z.ZodMiniType<
  LucidCheckLivenessResponse,
  unknown
> = z.object({
  status: types.string(),
  timestamp: types.date(),
  uptime: types.number(),
});

export function lucidCheckLivenessResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidCheckLivenessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidCheckLivenessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidCheckLivenessResponse' from JSON`,
  );
}
