/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidListAgentDeploymentsRequest = {
  /**
   * Filter deployments by tenant identifier
   */
  tenantId?: string | undefined;
  /**
   * Filter by deployment status (e.g. running, stopped, failed)
   */
  status?: string | undefined;
  /**
   * Filter by deploy target (docker, railway, akash, phala, ionet, nosana)
   */
  target?: string | undefined;
};

/**
 * OK
 */
export type LucidListAgentDeploymentsResponse = {
  success: boolean;
  deployments: Array<{ [k: string]: any }>;
};

/** @internal */
export type LucidListAgentDeploymentsRequest$Outbound = {
  tenant_id?: string | undefined;
  status?: string | undefined;
  target?: string | undefined;
};

/** @internal */
export const LucidListAgentDeploymentsRequest$outboundSchema: z.ZodMiniType<
  LucidListAgentDeploymentsRequest$Outbound,
  LucidListAgentDeploymentsRequest
> = z.pipe(
  z.object({
    tenantId: z.optional(z.string()),
    status: z.optional(z.string()),
    target: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
    });
  }),
);

export function lucidListAgentDeploymentsRequestToJSON(
  lucidListAgentDeploymentsRequest: LucidListAgentDeploymentsRequest,
): string {
  return JSON.stringify(
    LucidListAgentDeploymentsRequest$outboundSchema.parse(
      lucidListAgentDeploymentsRequest,
    ),
  );
}

/** @internal */
export const LucidListAgentDeploymentsResponse$inboundSchema: z.ZodMiniType<
  LucidListAgentDeploymentsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  deployments: z.array(z.record(z.string(), z.any())),
});

export function lucidListAgentDeploymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidListAgentDeploymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListAgentDeploymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListAgentDeploymentsResponse' from JSON`,
  );
}
