/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidListModulesRequest = {
  /**
   * EVM chain identifier for the smart account
   */
  chainId: string;
  /**
   * Smart account address (EVM 0x format)
   */
  account: string;
};

/** @internal */
export type LucidListModulesRequest$Outbound = {
  chainId: string;
  account: string;
};

/** @internal */
export const LucidListModulesRequest$outboundSchema: z.ZodMiniType<
  LucidListModulesRequest$Outbound,
  LucidListModulesRequest
> = z.object({
  chainId: z.string(),
  account: z.string(),
});

export function lucidListModulesRequestToJSON(
  lucidListModulesRequest: LucidListModulesRequest,
): string {
  return JSON.stringify(
    LucidListModulesRequest$outboundSchema.parse(lucidListModulesRequest),
  );
}
