/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Context = {
  tenantId: string;
  variables?: { [k: string]: any } | undefined;
};

export const Executor = {
  N8n: "n8n",
  Langgraph: "langgraph",
} as const;
export type Executor = ClosedEnum<typeof Executor>;

export type LucidExecuteAgentFlowspecRequest = {
  flowspec: { [k: string]: any };
  context: Context;
  executor?: Executor | undefined;
};

/**
 * OK
 */
export type LucidExecuteAgentFlowspecResponse = {
  success: boolean;
  result?: { [k: string]: any } | undefined;
};

/** @internal */
export type Context$Outbound = {
  tenantId: string;
  variables?: { [k: string]: any } | undefined;
};

/** @internal */
export const Context$outboundSchema: z.ZodMiniType<Context$Outbound, Context> =
  z.object({
    tenantId: z.string(),
    variables: z.optional(z.record(z.string(), z.any())),
  });

export function contextToJSON(context: Context): string {
  return JSON.stringify(Context$outboundSchema.parse(context));
}

/** @internal */
export const Executor$outboundSchema: z.ZodMiniEnum<typeof Executor> = z.enum(
  Executor,
);

/** @internal */
export type LucidExecuteAgentFlowspecRequest$Outbound = {
  flowspec: { [k: string]: any };
  context: Context$Outbound;
  executor?: string | undefined;
};

/** @internal */
export const LucidExecuteAgentFlowspecRequest$outboundSchema: z.ZodMiniType<
  LucidExecuteAgentFlowspecRequest$Outbound,
  LucidExecuteAgentFlowspecRequest
> = z.object({
  flowspec: z.record(z.string(), z.any()),
  context: z.lazy(() => Context$outboundSchema),
  executor: z.optional(Executor$outboundSchema),
});

export function lucidExecuteAgentFlowspecRequestToJSON(
  lucidExecuteAgentFlowspecRequest: LucidExecuteAgentFlowspecRequest,
): string {
  return JSON.stringify(
    LucidExecuteAgentFlowspecRequest$outboundSchema.parse(
      lucidExecuteAgentFlowspecRequest,
    ),
  );
}

/** @internal */
export const LucidExecuteAgentFlowspecResponse$inboundSchema: z.ZodMiniType<
  LucidExecuteAgentFlowspecResponse,
  unknown
> = z.object({
  success: types.boolean(),
  result: types.optional(z.record(z.string(), z.any())),
});

export function lucidExecuteAgentFlowspecResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidExecuteAgentFlowspecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidExecuteAgentFlowspecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidExecuteAgentFlowspecResponse' from JSON`,
  );
}
