/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidGetPassportRequest = {
  passportId: string;
};

/** @internal */
export type LucidGetPassportRequest$Outbound = {
  passport_id: string;
};

/** @internal */
export const LucidGetPassportRequest$outboundSchema: z.ZodMiniType<
  LucidGetPassportRequest$Outbound,
  LucidGetPassportRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function lucidGetPassportRequestToJSON(
  lucidGetPassportRequest: LucidGetPassportRequest,
): string {
  return JSON.stringify(
    LucidGetPassportRequest$outboundSchema.parse(lucidGetPassportRequest),
  );
}
