/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidGetSignerPubkeyResponse = {
  success: boolean;
  signerType?: string | undefined;
  pubkey: string;
};

/** @internal */
export const LucidGetSignerPubkeyResponse$inboundSchema: z.ZodMiniType<
  LucidGetSignerPubkeyResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    signer_type: types.optional(types.string()),
    pubkey: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "signer_type": "signerType",
    });
  }),
);

export function lucidGetSignerPubkeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetSignerPubkeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetSignerPubkeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetSignerPubkeyResponse' from JSON`,
  );
}
