/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidGetAgentHistoryRequest = {
  /**
   * Legacy agent identifier
   */
  agentId: string;
};

/**
 * OK
 */
export type LucidGetAgentHistoryResponse = {
  success: boolean;
  agentId: string;
  history: Array<models.AgentHistoryEntry>;
  totalEpochs: number;
  message?: string | undefined;
};

/** @internal */
export type LucidGetAgentHistoryRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidGetAgentHistoryRequest$outboundSchema: z.ZodMiniType<
  LucidGetAgentHistoryRequest$Outbound,
  LucidGetAgentHistoryRequest
> = z.object({
  agentId: z.string(),
});

export function lucidGetAgentHistoryRequestToJSON(
  lucidGetAgentHistoryRequest: LucidGetAgentHistoryRequest,
): string {
  return JSON.stringify(
    LucidGetAgentHistoryRequest$outboundSchema.parse(
      lucidGetAgentHistoryRequest,
    ),
  );
}

/** @internal */
export const LucidGetAgentHistoryResponse$inboundSchema: z.ZodMiniType<
  LucidGetAgentHistoryResponse,
  unknown
> = z.object({
  success: types.boolean(),
  agentId: types.string(),
  history: z.array(models.AgentHistoryEntry$inboundSchema),
  totalEpochs: types.number(),
  message: types.optional(types.string()),
});

export function lucidGetAgentHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAgentHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetAgentHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAgentHistoryResponse' from JSON`,
  );
}
