/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidRollbackDeploymentRequest = {
  /**
   * Agent passport identifier
   */
  passportId: string;
};

/**
 * Rolled back
 */
export type LucidRollbackDeploymentResponse = {
  success: boolean;
  message: string;
  deploymentId?: string | undefined;
};

/** @internal */
export type LucidRollbackDeploymentRequest$Outbound = {
  passportId: string;
};

/** @internal */
export const LucidRollbackDeploymentRequest$outboundSchema: z.ZodMiniType<
  LucidRollbackDeploymentRequest$Outbound,
  LucidRollbackDeploymentRequest
> = z.object({
  passportId: z.string(),
});

export function lucidRollbackDeploymentRequestToJSON(
  lucidRollbackDeploymentRequest: LucidRollbackDeploymentRequest,
): string {
  return JSON.stringify(
    LucidRollbackDeploymentRequest$outboundSchema.parse(
      lucidRollbackDeploymentRequest,
    ),
  );
}

/** @internal */
export const LucidRollbackDeploymentResponse$inboundSchema: z.ZodMiniType<
  LucidRollbackDeploymentResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    message: types.string(),
    deployment_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "deployment_id": "deploymentId",
    });
  }),
);

export function lucidRollbackDeploymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidRollbackDeploymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidRollbackDeploymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidRollbackDeploymentResponse' from JSON`,
  );
}
