/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetAgentDeployLogsRequest = {
  /**
   * Agent passport identifier
   */
  passportId: string;
  /**
   * Number of log lines to return (default 100)
   */
  tail?: number | undefined;
};

/**
 * OK
 */
export type LucidGetAgentDeployLogsResponse = {
  success: boolean;
  logs: { [k: string]: any };
};

/** @internal */
export type LucidGetAgentDeployLogsRequest$Outbound = {
  passportId: string;
  tail: number;
};

/** @internal */
export const LucidGetAgentDeployLogsRequest$outboundSchema: z.ZodMiniType<
  LucidGetAgentDeployLogsRequest$Outbound,
  LucidGetAgentDeployLogsRequest
> = z.object({
  passportId: z.string(),
  tail: z._default(z.int(), 100),
});

export function lucidGetAgentDeployLogsRequestToJSON(
  lucidGetAgentDeployLogsRequest: LucidGetAgentDeployLogsRequest,
): string {
  return JSON.stringify(
    LucidGetAgentDeployLogsRequest$outboundSchema.parse(
      lucidGetAgentDeployLogsRequest,
    ),
  );
}

/** @internal */
export const LucidGetAgentDeployLogsResponse$inboundSchema: z.ZodMiniType<
  LucidGetAgentDeployLogsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  logs: z.record(z.string(), z.any()),
});

export function lucidGetAgentDeployLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAgentDeployLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetAgentDeployLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAgentDeployLogsResponse' from JSON`,
  );
}
