/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as models from "../index.js";

export type Type = models.PassportType | Array<models.PassportType>;

export type LucidListPassportsStatus =
  | models.PassportStatus
  | Array<models.PassportStatus>;

export const TagMatch = {
  All: "all",
  Any: "any",
} as const;
export type TagMatch = ClosedEnum<typeof TagMatch>;

export const SortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
} as const;
export type SortBy = ClosedEnum<typeof SortBy>;

export const SortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SortOrder = ClosedEnum<typeof SortOrder>;

export type LucidListPassportsRequest = {
  type?: models.PassportType | Array<models.PassportType> | undefined;
  owner?: string | undefined;
  status?: models.PassportStatus | Array<models.PassportStatus> | undefined;
  /**
   * Comma-separated
   */
  tags?: string | undefined;
  tagMatch?: TagMatch | undefined;
  search?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
  sortBy?: SortBy | undefined;
  sortOrder?: SortOrder | undefined;
};

/** @internal */
export type Type$Outbound = string | Array<string>;

/** @internal */
export const Type$outboundSchema: z.ZodMiniType<Type$Outbound, Type> =
  smartUnion([
    models.PassportType$outboundSchema,
    z.array(models.PassportType$outboundSchema),
  ]);

export function typeToJSON(type: Type): string {
  return JSON.stringify(Type$outboundSchema.parse(type));
}

/** @internal */
export type LucidListPassportsStatus$Outbound = string | Array<string>;

/** @internal */
export const LucidListPassportsStatus$outboundSchema: z.ZodMiniType<
  LucidListPassportsStatus$Outbound,
  LucidListPassportsStatus
> = smartUnion([
  models.PassportStatus$outboundSchema,
  z.array(models.PassportStatus$outboundSchema),
]);

export function lucidListPassportsStatusToJSON(
  lucidListPassportsStatus: LucidListPassportsStatus,
): string {
  return JSON.stringify(
    LucidListPassportsStatus$outboundSchema.parse(lucidListPassportsStatus),
  );
}

/** @internal */
export const TagMatch$outboundSchema: z.ZodMiniEnum<typeof TagMatch> = z.enum(
  TagMatch,
);

/** @internal */
export const SortBy$outboundSchema: z.ZodMiniEnum<typeof SortBy> = z.enum(
  SortBy,
);

/** @internal */
export const SortOrder$outboundSchema: z.ZodMiniEnum<typeof SortOrder> = z.enum(
  SortOrder,
);

/** @internal */
export type LucidListPassportsRequest$Outbound = {
  type?: string | Array<string> | undefined;
  owner?: string | undefined;
  status?: string | Array<string> | undefined;
  tags?: string | undefined;
  tag_match?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
  sort_by?: string | undefined;
  sort_order?: string | undefined;
};

/** @internal */
export const LucidListPassportsRequest$outboundSchema: z.ZodMiniType<
  LucidListPassportsRequest$Outbound,
  LucidListPassportsRequest
> = z.pipe(
  z.object({
    type: z.optional(
      smartUnion([
        models.PassportType$outboundSchema,
        z.array(models.PassportType$outboundSchema),
      ]),
    ),
    owner: z.optional(z.string()),
    status: z.optional(
      smartUnion([
        models.PassportStatus$outboundSchema,
        z.array(models.PassportStatus$outboundSchema),
      ]),
    ),
    tags: z.optional(z.string()),
    tagMatch: z.optional(TagMatch$outboundSchema),
    search: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
    sortBy: z.optional(SortBy$outboundSchema),
    sortOrder: z.optional(SortOrder$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      tagMatch: "tag_match",
      perPage: "per_page",
      sortBy: "sort_by",
      sortOrder: "sort_order",
    });
  }),
);

export function lucidListPassportsRequestToJSON(
  lucidListPassportsRequest: LucidListPassportsRequest,
): string {
  return JSON.stringify(
    LucidListPassportsRequest$outboundSchema.parse(lucidListPassportsRequest),
  );
}
