/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidValidateFlowspecResponse = {
  success: boolean;
  validation: { [k: string]: any };
  message?: string | undefined;
};

/** @internal */
export const LucidValidateFlowspecResponse$inboundSchema: z.ZodMiniType<
  LucidValidateFlowspecResponse,
  unknown
> = z.object({
  success: types.boolean(),
  validation: z.record(z.string(), z.any()),
  message: types.optional(types.string()),
});

export function lucidValidateFlowspecResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidValidateFlowspecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidValidateFlowspecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidValidateFlowspecResponse' from JSON`,
  );
}
