/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidSubscribeAssetRequestBody = {
  passportId: string;
  durationHours?: number | undefined;
};

export type LucidSubscribeAssetRequest = {
  /**
   * Transaction hash proving USDC payment (x402 protocol)
   */
  xPaymentProof: string;
  body: LucidSubscribeAssetRequestBody;
};

/**
 * Subscription created
 */
export type LucidSubscribeAssetResponse = {
  subscribed: boolean;
  passportId: string;
  /**
   * Unix timestamp
   */
  expiresAt: number;
  durationHours: number;
};

/** @internal */
export type LucidSubscribeAssetRequestBody$Outbound = {
  passport_id: string;
  duration_hours: number;
};

/** @internal */
export const LucidSubscribeAssetRequestBody$outboundSchema: z.ZodMiniType<
  LucidSubscribeAssetRequestBody$Outbound,
  LucidSubscribeAssetRequestBody
> = z.pipe(
  z.object({
    passportId: z.string(),
    durationHours: z._default(z.int(), 24),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
      durationHours: "duration_hours",
    });
  }),
);

export function lucidSubscribeAssetRequestBodyToJSON(
  lucidSubscribeAssetRequestBody: LucidSubscribeAssetRequestBody,
): string {
  return JSON.stringify(
    LucidSubscribeAssetRequestBody$outboundSchema.parse(
      lucidSubscribeAssetRequestBody,
    ),
  );
}

/** @internal */
export type LucidSubscribeAssetRequest$Outbound = {
  "X-Payment-Proof": string;
  body: LucidSubscribeAssetRequestBody$Outbound;
};

/** @internal */
export const LucidSubscribeAssetRequest$outboundSchema: z.ZodMiniType<
  LucidSubscribeAssetRequest$Outbound,
  LucidSubscribeAssetRequest
> = z.pipe(
  z.object({
    xPaymentProof: z.string(),
    body: z.lazy(() => LucidSubscribeAssetRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xPaymentProof: "X-Payment-Proof",
    });
  }),
);

export function lucidSubscribeAssetRequestToJSON(
  lucidSubscribeAssetRequest: LucidSubscribeAssetRequest,
): string {
  return JSON.stringify(
    LucidSubscribeAssetRequest$outboundSchema.parse(lucidSubscribeAssetRequest),
  );
}

/** @internal */
export const LucidSubscribeAssetResponse$inboundSchema: z.ZodMiniType<
  LucidSubscribeAssetResponse,
  unknown
> = z.pipe(
  z.object({
    subscribed: types.boolean(),
    passport_id: types.string(),
    expires_at: types.number(),
    duration_hours: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "passport_id": "passportId",
      "expires_at": "expiresAt",
      "duration_hours": "durationHours",
    });
  }),
);

export function lucidSubscribeAssetResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidSubscribeAssetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidSubscribeAssetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidSubscribeAssetResponse' from JSON`,
  );
}
