/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidListDatasetsRequest = {
  /**
   * Filter by dataset owner wallet address
   */
  owner?: string | undefined;
  /**
   * Comma-separated
   */
  tags?: string | undefined;
  /**
   * Free-text search across dataset name and description
   */
  search?: string | undefined;
  /**
   * Page number for pagination (starts at 1)
   */
  page?: number | undefined;
  /**
   * Number of results per page (1-100)
   */
  perPage?: number | undefined;
};

/**
 * OK
 */
export type LucidListDatasetsResponseBody = {
  success: boolean;
  datasets: Array<models.Passport>;
  pagination: models.Pagination;
};

export type LucidListDatasetsResponse = {
  result: LucidListDatasetsResponseBody;
};

/** @internal */
export type LucidListDatasetsRequest$Outbound = {
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const LucidListDatasetsRequest$outboundSchema: z.ZodMiniType<
  LucidListDatasetsRequest$Outbound,
  LucidListDatasetsRequest
> = z.pipe(
  z.object({
    owner: z.optional(z.string()),
    tags: z.optional(z.string()),
    search: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function lucidListDatasetsRequestToJSON(
  lucidListDatasetsRequest: LucidListDatasetsRequest,
): string {
  return JSON.stringify(
    LucidListDatasetsRequest$outboundSchema.parse(lucidListDatasetsRequest),
  );
}

/** @internal */
export const LucidListDatasetsResponseBody$inboundSchema: z.ZodMiniType<
  LucidListDatasetsResponseBody,
  unknown
> = z.object({
  success: types.boolean(),
  datasets: z.array(models.Passport$inboundSchema),
  pagination: models.Pagination$inboundSchema,
});

export function lucidListDatasetsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LucidListDatasetsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListDatasetsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListDatasetsResponseBody' from JSON`,
  );
}

/** @internal */
export const LucidListDatasetsResponse$inboundSchema: z.ZodMiniType<
  LucidListDatasetsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => LucidListDatasetsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function lucidListDatasetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidListDatasetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListDatasetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListDatasetsResponse' from JSON`,
  );
}
