/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidMatchRequestBody = {
  /**
   * Metadata for a model passport. Validated against schemas/ModelMeta.schema.json (additionalProperties: false).
   */
  modelMeta?: models.ModelMeta | undefined;
  policy?: models.Policy | undefined;
  computeCatalog?: Array<models.ComputeMeta> | undefined;
  requireLiveHealthy?: boolean | undefined;
};

export type LucidMatchRequest = {
  /**
   * Transaction hash proving USDC payment (x402 protocol)
   */
  xPaymentProof?: string | undefined;
  body: LucidMatchRequestBody;
};

/**
 * OK
 */
export type LucidMatchResponse = {
  success: boolean;
  match: { [k: string]: any };
  explain: { [k: string]: any };
};

/** @internal */
export type LucidMatchRequestBody$Outbound = {
  model_meta?: models.ModelMeta$Outbound | undefined;
  policy?: models.Policy$Outbound | undefined;
  compute_catalog?: Array<models.ComputeMeta$Outbound> | undefined;
  require_live_healthy: boolean;
};

/** @internal */
export const LucidMatchRequestBody$outboundSchema: z.ZodMiniType<
  LucidMatchRequestBody$Outbound,
  LucidMatchRequestBody
> = z.pipe(
  z.object({
    modelMeta: z.optional(models.ModelMeta$outboundSchema),
    policy: z.optional(models.Policy$outboundSchema),
    computeCatalog: z.optional(z.array(models.ComputeMeta$outboundSchema)),
    requireLiveHealthy: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelMeta: "model_meta",
      computeCatalog: "compute_catalog",
      requireLiveHealthy: "require_live_healthy",
    });
  }),
);

export function lucidMatchRequestBodyToJSON(
  lucidMatchRequestBody: LucidMatchRequestBody,
): string {
  return JSON.stringify(
    LucidMatchRequestBody$outboundSchema.parse(lucidMatchRequestBody),
  );
}

/** @internal */
export type LucidMatchRequest$Outbound = {
  "X-Payment-Proof"?: string | undefined;
  body: LucidMatchRequestBody$Outbound;
};

/** @internal */
export const LucidMatchRequest$outboundSchema: z.ZodMiniType<
  LucidMatchRequest$Outbound,
  LucidMatchRequest
> = z.pipe(
  z.object({
    xPaymentProof: z.optional(z.string()),
    body: z.lazy(() => LucidMatchRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xPaymentProof: "X-Payment-Proof",
    });
  }),
);

export function lucidMatchRequestToJSON(
  lucidMatchRequest: LucidMatchRequest,
): string {
  return JSON.stringify(
    LucidMatchRequest$outboundSchema.parse(lucidMatchRequest),
  );
}

/** @internal */
export const LucidMatchResponse$inboundSchema: z.ZodMiniType<
  LucidMatchResponse,
  unknown
> = z.object({
  success: types.boolean(),
  match: z.record(z.string(), z.any()),
  explain: z.record(z.string(), z.any()),
});

export function lucidMatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidMatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidMatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidMatchResponse' from JSON`,
  );
}
