/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetSupportedChainsChain = {
  chain?: string | undefined;
  tokens?: Array<string> | undefined;
};

/**
 * Supported chains
 */
export type LucidGetSupportedChainsResponse = {
  success: boolean;
  chains: Array<LucidGetSupportedChainsChain>;
};

/** @internal */
export const LucidGetSupportedChainsChain$inboundSchema: z.ZodMiniType<
  LucidGetSupportedChainsChain,
  unknown
> = z.object({
  chain: types.optional(types.string()),
  tokens: types.optional(z.array(types.string())),
});

export function lucidGetSupportedChainsChainFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetSupportedChainsChain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetSupportedChainsChain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetSupportedChainsChain' from JSON`,
  );
}

/** @internal */
export const LucidGetSupportedChainsResponse$inboundSchema: z.ZodMiniType<
  LucidGetSupportedChainsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  chains: z.array(z.lazy(() => LucidGetSupportedChainsChain$inboundSchema)),
});

export function lucidGetSupportedChainsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetSupportedChainsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetSupportedChainsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetSupportedChainsResponse' from JSON`,
  );
}
