/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const Role = {
  User: "user",
  Assistant: "assistant",
  System: "system",
  Tool: "tool",
} as const;
export type Role = ClosedEnum<typeof Role>;

export const LucidAddEpisodicMemoryMemoryLane = {
  Self: "self",
  User: "user",
  Shared: "shared",
  Market: "market",
} as const;
export type LucidAddEpisodicMemoryMemoryLane = ClosedEnum<
  typeof LucidAddEpisodicMemoryMemoryLane
>;

export type LucidAddEpisodicMemoryRequestBody = {
  sessionId: string;
  role: Role;
  content: string;
  tokens?: number | undefined;
  namespace?: string | undefined;
  memoryLane?: LucidAddEpisodicMemoryMemoryLane | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export type LucidAddEpisodicMemoryRequest = {
  xAgentPassportId: string;
  body: LucidAddEpisodicMemoryRequestBody;
};

/** @internal */
export const Role$outboundSchema: z.ZodMiniEnum<typeof Role> = z.enum(Role);

/** @internal */
export const LucidAddEpisodicMemoryMemoryLane$outboundSchema: z.ZodMiniEnum<
  typeof LucidAddEpisodicMemoryMemoryLane
> = z.enum(LucidAddEpisodicMemoryMemoryLane);

/** @internal */
export type LucidAddEpisodicMemoryRequestBody$Outbound = {
  session_id: string;
  role: string;
  content: string;
  tokens: number;
  namespace?: string | undefined;
  memory_lane?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const LucidAddEpisodicMemoryRequestBody$outboundSchema: z.ZodMiniType<
  LucidAddEpisodicMemoryRequestBody$Outbound,
  LucidAddEpisodicMemoryRequestBody
> = z.pipe(
  z.object({
    sessionId: z.string(),
    role: Role$outboundSchema,
    content: z.string(),
    tokens: z._default(z.int(), 0),
    namespace: z.optional(z.string()),
    memoryLane: z.optional(LucidAddEpisodicMemoryMemoryLane$outboundSchema),
    metadata: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sessionId: "session_id",
      memoryLane: "memory_lane",
    });
  }),
);

export function lucidAddEpisodicMemoryRequestBodyToJSON(
  lucidAddEpisodicMemoryRequestBody: LucidAddEpisodicMemoryRequestBody,
): string {
  return JSON.stringify(
    LucidAddEpisodicMemoryRequestBody$outboundSchema.parse(
      lucidAddEpisodicMemoryRequestBody,
    ),
  );
}

/** @internal */
export type LucidAddEpisodicMemoryRequest$Outbound = {
  "X-Agent-Passport-Id": string;
  body: LucidAddEpisodicMemoryRequestBody$Outbound;
};

/** @internal */
export const LucidAddEpisodicMemoryRequest$outboundSchema: z.ZodMiniType<
  LucidAddEpisodicMemoryRequest$Outbound,
  LucidAddEpisodicMemoryRequest
> = z.pipe(
  z.object({
    xAgentPassportId: z.string(),
    body: z.lazy(() => LucidAddEpisodicMemoryRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xAgentPassportId: "X-Agent-Passport-Id",
    });
  }),
);

export function lucidAddEpisodicMemoryRequestToJSON(
  lucidAddEpisodicMemoryRequest: LucidAddEpisodicMemoryRequest,
): string {
  return JSON.stringify(
    LucidAddEpisodicMemoryRequest$outboundSchema.parse(
      lucidAddEpisodicMemoryRequest,
    ),
  );
}
