/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidGetReceiptRequest = {
  receiptId: string;
};

/**
 * OK
 */
export type LucidGetReceiptResponse = {
  success: boolean;
  receipt: models.Receipt;
};

/** @internal */
export type LucidGetReceiptRequest$Outbound = {
  receipt_id: string;
};

/** @internal */
export const LucidGetReceiptRequest$outboundSchema: z.ZodMiniType<
  LucidGetReceiptRequest$Outbound,
  LucidGetReceiptRequest
> = z.pipe(
  z.object({
    receiptId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      receiptId: "receipt_id",
    });
  }),
);

export function lucidGetReceiptRequestToJSON(
  lucidGetReceiptRequest: LucidGetReceiptRequest,
): string {
  return JSON.stringify(
    LucidGetReceiptRequest$outboundSchema.parse(lucidGetReceiptRequest),
  );
}

/** @internal */
export const LucidGetReceiptResponse$inboundSchema: z.ZodMiniType<
  LucidGetReceiptResponse,
  unknown
> = z.object({
  success: types.boolean(),
  receipt: models.Receipt$inboundSchema,
});

export function lucidGetReceiptResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetReceiptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetReceiptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetReceiptResponse' from JSON`,
  );
}
