/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidAccomplishAgentGoalResponse = {
  success: boolean;
  goal: string;
  result?: { [k: string]: any } | undefined;
  execution?: { [k: string]: any } | undefined;
};

/** @internal */
export const LucidAccomplishAgentGoalResponse$inboundSchema: z.ZodMiniType<
  LucidAccomplishAgentGoalResponse,
  unknown
> = z.object({
  success: types.boolean(),
  goal: types.string(),
  result: types.optional(z.record(z.string(), z.any())),
  execution: types.optional(z.record(z.string(), z.any())),
});

export function lucidAccomplishAgentGoalResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidAccomplishAgentGoalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidAccomplishAgentGoalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidAccomplishAgentGoalResponse' from JSON`,
  );
}
