/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Mode = {
  Warm: "warm",
  Cold: "cold",
  Full: "full",
} as const;
export type Mode = ClosedEnum<typeof Mode>;

export type LucidCompactMemoryRequestBody = {
  namespace?: string | undefined;
  sessionId?: string | undefined;
  mode?: Mode | undefined;
};

export type LucidCompactMemoryRequest = {
  xAgentPassportId: string;
  body: LucidCompactMemoryRequestBody;
};

export type LucidCompactMemoryData = {
  sessionsCompacted?: number | undefined;
  episodicArchived?: number | undefined;
  extractionTriggered?: boolean | undefined;
  coldPruned?: number | undefined;
  snapshotCid?: string | null | undefined;
};

/**
 * OK
 */
export type LucidCompactMemoryResponse = {
  success?: boolean | undefined;
  data?: LucidCompactMemoryData | undefined;
};

/** @internal */
export const Mode$outboundSchema: z.ZodMiniEnum<typeof Mode> = z.enum(Mode);

/** @internal */
export type LucidCompactMemoryRequestBody$Outbound = {
  namespace?: string | undefined;
  session_id?: string | undefined;
  mode: string;
};

/** @internal */
export const LucidCompactMemoryRequestBody$outboundSchema: z.ZodMiniType<
  LucidCompactMemoryRequestBody$Outbound,
  LucidCompactMemoryRequestBody
> = z.pipe(
  z.object({
    namespace: z.optional(z.string()),
    sessionId: z.optional(z.string()),
    mode: z._default(Mode$outboundSchema, "full"),
  }),
  z.transform((v) => {
    return remap$(v, {
      sessionId: "session_id",
    });
  }),
);

export function lucidCompactMemoryRequestBodyToJSON(
  lucidCompactMemoryRequestBody: LucidCompactMemoryRequestBody,
): string {
  return JSON.stringify(
    LucidCompactMemoryRequestBody$outboundSchema.parse(
      lucidCompactMemoryRequestBody,
    ),
  );
}

/** @internal */
export type LucidCompactMemoryRequest$Outbound = {
  "X-Agent-Passport-Id": string;
  body: LucidCompactMemoryRequestBody$Outbound;
};

/** @internal */
export const LucidCompactMemoryRequest$outboundSchema: z.ZodMiniType<
  LucidCompactMemoryRequest$Outbound,
  LucidCompactMemoryRequest
> = z.pipe(
  z.object({
    xAgentPassportId: z.string(),
    body: z.lazy(() => LucidCompactMemoryRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xAgentPassportId: "X-Agent-Passport-Id",
    });
  }),
);

export function lucidCompactMemoryRequestToJSON(
  lucidCompactMemoryRequest: LucidCompactMemoryRequest,
): string {
  return JSON.stringify(
    LucidCompactMemoryRequest$outboundSchema.parse(lucidCompactMemoryRequest),
  );
}

/** @internal */
export const LucidCompactMemoryData$inboundSchema: z.ZodMiniType<
  LucidCompactMemoryData,
  unknown
> = z.pipe(
  z.object({
    sessions_compacted: types.optional(types.number()),
    episodic_archived: types.optional(types.number()),
    extraction_triggered: types.optional(types.boolean()),
    cold_pruned: types.optional(types.number()),
    snapshot_cid: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "sessions_compacted": "sessionsCompacted",
      "episodic_archived": "episodicArchived",
      "extraction_triggered": "extractionTriggered",
      "cold_pruned": "coldPruned",
      "snapshot_cid": "snapshotCid",
    });
  }),
);

export function lucidCompactMemoryDataFromJSON(
  jsonString: string,
): SafeParseResult<LucidCompactMemoryData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidCompactMemoryData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidCompactMemoryData' from JSON`,
  );
}

/** @internal */
export const LucidCompactMemoryResponse$inboundSchema: z.ZodMiniType<
  LucidCompactMemoryResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => LucidCompactMemoryData$inboundSchema)),
});

export function lucidCompactMemoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidCompactMemoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidCompactMemoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidCompactMemoryResponse' from JSON`,
  );
}
