/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetExecutorDecisionRequest = {
  flowspec: { [k: string]: any };
};

export type Decision = {
  executor?: string | undefined;
  reason?: string | undefined;
};

/**
 * OK
 */
export type LucidGetExecutorDecisionResponse = {
  success: boolean;
  decision: Decision;
  message?: string | undefined;
};

/** @internal */
export type LucidGetExecutorDecisionRequest$Outbound = {
  flowspec: { [k: string]: any };
};

/** @internal */
export const LucidGetExecutorDecisionRequest$outboundSchema: z.ZodMiniType<
  LucidGetExecutorDecisionRequest$Outbound,
  LucidGetExecutorDecisionRequest
> = z.object({
  flowspec: z.record(z.string(), z.any()),
});

export function lucidGetExecutorDecisionRequestToJSON(
  lucidGetExecutorDecisionRequest: LucidGetExecutorDecisionRequest,
): string {
  return JSON.stringify(
    LucidGetExecutorDecisionRequest$outboundSchema.parse(
      lucidGetExecutorDecisionRequest,
    ),
  );
}

/** @internal */
export const Decision$inboundSchema: z.ZodMiniType<Decision, unknown> = z
  .object({
    executor: types.optional(types.string()),
    reason: types.optional(types.string()),
  });

export function decisionFromJSON(
  jsonString: string,
): SafeParseResult<Decision, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Decision$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Decision' from JSON`,
  );
}

/** @internal */
export const LucidGetExecutorDecisionResponse$inboundSchema: z.ZodMiniType<
  LucidGetExecutorDecisionResponse,
  unknown
> = z.object({
  success: types.boolean(),
  decision: z.lazy(() => Decision$inboundSchema),
  message: types.optional(types.string()),
});

export function lucidGetExecutorDecisionResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetExecutorDecisionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetExecutorDecisionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetExecutorDecisionResponse' from JSON`,
  );
}
