/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidGetCompositeReputationRequest = {
  /**
   * Agent identifier for composite reputation score
   */
  agentId: string;
};

/**
 * Composite score
 */
export type LucidGetCompositeReputationResponse = {
  success: boolean;
  agentId: string;
  composite: models.CompositeReputationScore;
};

/** @internal */
export type LucidGetCompositeReputationRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidGetCompositeReputationRequest$outboundSchema: z.ZodMiniType<
  LucidGetCompositeReputationRequest$Outbound,
  LucidGetCompositeReputationRequest
> = z.object({
  agentId: z.string(),
});

export function lucidGetCompositeReputationRequestToJSON(
  lucidGetCompositeReputationRequest: LucidGetCompositeReputationRequest,
): string {
  return JSON.stringify(
    LucidGetCompositeReputationRequest$outboundSchema.parse(
      lucidGetCompositeReputationRequest,
    ),
  );
}

/** @internal */
export const LucidGetCompositeReputationResponse$inboundSchema: z.ZodMiniType<
  LucidGetCompositeReputationResponse,
  unknown
> = z.object({
  success: types.boolean(),
  agentId: types.string(),
  composite: models.CompositeReputationScore$inboundSchema,
});

export function lucidGetCompositeReputationResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetCompositeReputationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LucidGetCompositeReputationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetCompositeReputationResponse' from JSON`,
  );
}
