/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * OK
 */
export type LucidPayoutFromReceiptResponse = {
  success: boolean;
  payout: models.Payout;
};

/** @internal */
export const LucidPayoutFromReceiptResponse$inboundSchema: z.ZodMiniType<
  LucidPayoutFromReceiptResponse,
  unknown
> = z.object({
  success: types.boolean(),
  payout: models.Payout$inboundSchema,
});

export function lucidPayoutFromReceiptResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidPayoutFromReceiptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidPayoutFromReceiptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidPayoutFromReceiptResponse' from JSON`,
  );
}
