/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidGetPaymasterRateRequest = {
  /**
   * EVM chain identifier for exchange rate lookup
   */
  chainId: string;
};

/** @internal */
export type LucidGetPaymasterRateRequest$Outbound = {
  chainId: string;
};

/** @internal */
export const LucidGetPaymasterRateRequest$outboundSchema: z.ZodMiniType<
  LucidGetPaymasterRateRequest$Outbound,
  LucidGetPaymasterRateRequest
> = z.object({
  chainId: z.string(),
});

export function lucidGetPaymasterRateRequestToJSON(
  lucidGetPaymasterRateRequest: LucidGetPaymasterRateRequest,
): string {
  return JSON.stringify(
    LucidGetPaymasterRateRequest$outboundSchema.parse(
      lucidGetPaymasterRateRequest,
    ),
  );
}
