/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidSearchModelsRequest = {
  runtime?: string | undefined;
  format?: string | undefined;
  maxVram?: number | undefined;
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

/**
 * OK
 */
export type LucidSearchModelsResponse = {
  success: boolean;
  models: Array<models.Passport>;
  pagination: models.Pagination;
};

/** @internal */
export type LucidSearchModelsRequest$Outbound = {
  runtime?: string | undefined;
  format?: string | undefined;
  max_vram?: number | undefined;
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const LucidSearchModelsRequest$outboundSchema: z.ZodMiniType<
  LucidSearchModelsRequest$Outbound,
  LucidSearchModelsRequest
> = z.pipe(
  z.object({
    runtime: z.optional(z.string()),
    format: z.optional(z.string()),
    maxVram: z.optional(z.int()),
    owner: z.optional(z.string()),
    tags: z.optional(z.string()),
    search: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxVram: "max_vram",
      perPage: "per_page",
    });
  }),
);

export function lucidSearchModelsRequestToJSON(
  lucidSearchModelsRequest: LucidSearchModelsRequest,
): string {
  return JSON.stringify(
    LucidSearchModelsRequest$outboundSchema.parse(lucidSearchModelsRequest),
  );
}

/** @internal */
export const LucidSearchModelsResponse$inboundSchema: z.ZodMiniType<
  LucidSearchModelsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  models: z.array(models.Passport$inboundSchema),
  pagination: models.Pagination$inboundSchema,
});

export function lucidSearchModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidSearchModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidSearchModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidSearchModelsResponse' from JSON`,
  );
}
