/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * OK
 */
export type LucidCheckAgentOrchestratorHealthResponse = {
  success: boolean;
  health: { [k: string]: any };
  message?: string | undefined;
};

/** @internal */
export const LucidCheckAgentOrchestratorHealthResponse$inboundSchema:
  z.ZodMiniType<LucidCheckAgentOrchestratorHealthResponse, unknown> = z.object({
    success: types.boolean(),
    health: z.record(z.string(), z.any()),
    message: types.optional(types.string()),
  });

export function lucidCheckAgentOrchestratorHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LucidCheckAgentOrchestratorHealthResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LucidCheckAgentOrchestratorHealthResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LucidCheckAgentOrchestratorHealthResponse' from JSON`,
  );
}
