/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidListToolsRequest = {
  owner?: string | undefined;
  /**
   * Comma-separated
   */
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

/**
 * OK
 */
export type LucidListToolsResponse = {
  success: boolean;
  tools: Array<models.Passport>;
  pagination: models.Pagination;
};

/** @internal */
export type LucidListToolsRequest$Outbound = {
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const LucidListToolsRequest$outboundSchema: z.ZodMiniType<
  LucidListToolsRequest$Outbound,
  LucidListToolsRequest
> = z.pipe(
  z.object({
    owner: z.optional(z.string()),
    tags: z.optional(z.string()),
    search: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      perPage: "per_page",
    });
  }),
);

export function lucidListToolsRequestToJSON(
  lucidListToolsRequest: LucidListToolsRequest,
): string {
  return JSON.stringify(
    LucidListToolsRequest$outboundSchema.parse(lucidListToolsRequest),
  );
}

/** @internal */
export const LucidListToolsResponse$inboundSchema: z.ZodMiniType<
  LucidListToolsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  tools: z.array(models.Passport$inboundSchema),
  pagination: models.Pagination$inboundSchema,
});

export function lucidListToolsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidListToolsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListToolsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListToolsResponse' from JSON`,
  );
}
