/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Proof generated
 */
export type LucidGenerateZkmlProofResponse = {
  success: boolean;
  proof?: models.ZkMLProof | undefined;
};

/** @internal */
export const LucidGenerateZkmlProofResponse$inboundSchema: z.ZodMiniType<
  LucidGenerateZkmlProofResponse,
  unknown
> = z.object({
  success: types.boolean(),
  proof: types.optional(models.ZkMLProof$inboundSchema),
});

export function lucidGenerateZkmlProofResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGenerateZkmlProofResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGenerateZkmlProofResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGenerateZkmlProofResponse' from JSON`,
  );
}
