/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetDeploymentEventsRequest = {
  /**
   * Agent passport identifier
   */
  passportId: string;
  /**
   * Maximum number of events to return
   */
  limit?: number | undefined;
};

export type Metadata = {};

export type LucidGetDeploymentEventsData = {
  eventId?: string | undefined;
  deploymentId?: string | undefined;
  eventType?: string | undefined;
  actor?: string | undefined;
  previousState?: string | undefined;
  newState?: string | undefined;
  metadata?: Metadata | undefined;
  createdAt?: Date | undefined;
};

/**
 * OK
 */
export type LucidGetDeploymentEventsResponse = {
  success?: boolean | undefined;
  data?: Array<LucidGetDeploymentEventsData> | undefined;
};

/** @internal */
export type LucidGetDeploymentEventsRequest$Outbound = {
  passportId: string;
  limit: number;
};

/** @internal */
export const LucidGetDeploymentEventsRequest$outboundSchema: z.ZodMiniType<
  LucidGetDeploymentEventsRequest$Outbound,
  LucidGetDeploymentEventsRequest
> = z.object({
  passportId: z.string(),
  limit: z._default(z.int(), 50),
});

export function lucidGetDeploymentEventsRequestToJSON(
  lucidGetDeploymentEventsRequest: LucidGetDeploymentEventsRequest,
): string {
  return JSON.stringify(
    LucidGetDeploymentEventsRequest$outboundSchema.parse(
      lucidGetDeploymentEventsRequest,
    ),
  );
}

/** @internal */
export const Metadata$inboundSchema: z.ZodMiniType<Metadata, unknown> = z
  .object({});

export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const LucidGetDeploymentEventsData$inboundSchema: z.ZodMiniType<
  LucidGetDeploymentEventsData,
  unknown
> = z.pipe(
  z.object({
    event_id: types.optional(types.string()),
    deployment_id: types.optional(types.string()),
    event_type: types.optional(types.string()),
    actor: types.optional(types.string()),
    previous_state: types.optional(types.string()),
    new_state: types.optional(types.string()),
    metadata: types.optional(z.lazy(() => Metadata$inboundSchema)),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "deployment_id": "deploymentId",
      "event_type": "eventType",
      "previous_state": "previousState",
      "new_state": "newState",
      "created_at": "createdAt",
    });
  }),
);

export function lucidGetDeploymentEventsDataFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetDeploymentEventsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetDeploymentEventsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetDeploymentEventsData' from JSON`,
  );
}

/** @internal */
export const LucidGetDeploymentEventsResponse$inboundSchema: z.ZodMiniType<
  LucidGetDeploymentEventsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(
    z.array(z.lazy(() => LucidGetDeploymentEventsData$inboundSchema)),
  ),
});

export function lucidGetDeploymentEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetDeploymentEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetDeploymentEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetDeploymentEventsResponse' from JSON`,
  );
}
