/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidGetA2aAgentCardRequest = {
  /**
   * Agent passport identifier for A2A card discovery
   */
  passportId: string;
};

/** @internal */
export type LucidGetA2aAgentCardRequest$Outbound = {
  passportId: string;
};

/** @internal */
export const LucidGetA2aAgentCardRequest$outboundSchema: z.ZodMiniType<
  LucidGetA2aAgentCardRequest$Outbound,
  LucidGetA2aAgentCardRequest
> = z.object({
  passportId: z.string(),
});

export function lucidGetA2aAgentCardRequestToJSON(
  lucidGetA2aAgentCardRequest: LucidGetA2aAgentCardRequest,
): string {
  return JSON.stringify(
    LucidGetA2aAgentCardRequest$outboundSchema.parse(
      lucidGetA2aAgentCardRequest,
    ),
  );
}
