/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidPreviewAgentRequest = {
  name?: string | undefined;
  owner?: string | undefined;
  /**
   * Agent runtime descriptor
   */
  descriptor: { [k: string]: any };
  preferredAdapter?: string | undefined;
};

/**
 * Preview generated
 */
export type LucidPreviewAgentResponse = {
  success: boolean;
  preview: { [k: string]: any };
};

/** @internal */
export type LucidPreviewAgentRequest$Outbound = {
  name?: string | undefined;
  owner?: string | undefined;
  descriptor: { [k: string]: any };
  preferred_adapter?: string | undefined;
};

/** @internal */
export const LucidPreviewAgentRequest$outboundSchema: z.ZodMiniType<
  LucidPreviewAgentRequest$Outbound,
  LucidPreviewAgentRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    owner: z.optional(z.string()),
    descriptor: z.record(z.string(), z.any()),
    preferredAdapter: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      preferredAdapter: "preferred_adapter",
    });
  }),
);

export function lucidPreviewAgentRequestToJSON(
  lucidPreviewAgentRequest: LucidPreviewAgentRequest,
): string {
  return JSON.stringify(
    LucidPreviewAgentRequest$outboundSchema.parse(lucidPreviewAgentRequest),
  );
}

/** @internal */
export const LucidPreviewAgentResponse$inboundSchema: z.ZodMiniType<
  LucidPreviewAgentResponse,
  unknown
> = z.object({
  success: types.boolean(),
  preview: z.record(z.string(), z.any()),
});

export function lucidPreviewAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidPreviewAgentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidPreviewAgentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidPreviewAgentResponse' from JSON`,
  );
}
