/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidGetAnchorRequest = {
  anchorId: string;
};

/**
 * OK
 */
export type LucidGetAnchorResponse = {
  success?: boolean | undefined;
  data?: models.AnchorRecord | undefined;
};

/** @internal */
export type LucidGetAnchorRequest$Outbound = {
  anchor_id: string;
};

/** @internal */
export const LucidGetAnchorRequest$outboundSchema: z.ZodMiniType<
  LucidGetAnchorRequest$Outbound,
  LucidGetAnchorRequest
> = z.pipe(
  z.object({
    anchorId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      anchorId: "anchor_id",
    });
  }),
);

export function lucidGetAnchorRequestToJSON(
  lucidGetAnchorRequest: LucidGetAnchorRequest,
): string {
  return JSON.stringify(
    LucidGetAnchorRequest$outboundSchema.parse(lucidGetAnchorRequest),
  );
}

/** @internal */
export const LucidGetAnchorResponse$inboundSchema: z.ZodMiniType<
  LucidGetAnchorResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.AnchorRecord$inboundSchema),
});

export function lucidGetAnchorResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetAnchorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidGetAnchorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetAnchorResponse' from JSON`,
  );
}
