/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type LucidMatchRequest = {
  modelMeta?: { [k: string]: any } | undefined;
  policy?: models.Policy | undefined;
  computeCatalog?: Array<{ [k: string]: any }> | undefined;
  requireLiveHealthy?: boolean | undefined;
};

/**
 * OK
 */
export type LucidMatchResponse = {
  success: boolean;
  match: { [k: string]: any };
  explain: { [k: string]: any };
};

/** @internal */
export type LucidMatchRequest$Outbound = {
  model_meta?: { [k: string]: any } | undefined;
  policy?: models.Policy$Outbound | undefined;
  compute_catalog?: Array<{ [k: string]: any }> | undefined;
  require_live_healthy: boolean;
};

/** @internal */
export const LucidMatchRequest$outboundSchema: z.ZodMiniType<
  LucidMatchRequest$Outbound,
  LucidMatchRequest
> = z.pipe(
  z.object({
    modelMeta: z.optional(z.record(z.string(), z.any())),
    policy: z.optional(models.Policy$outboundSchema),
    computeCatalog: z.optional(z.array(z.record(z.string(), z.any()))),
    requireLiveHealthy: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelMeta: "model_meta",
      computeCatalog: "compute_catalog",
      requireLiveHealthy: "require_live_healthy",
    });
  }),
);

export function lucidMatchRequestToJSON(
  lucidMatchRequest: LucidMatchRequest,
): string {
  return JSON.stringify(
    LucidMatchRequest$outboundSchema.parse(lucidMatchRequest),
  );
}

/** @internal */
export const LucidMatchResponse$inboundSchema: z.ZodMiniType<
  LucidMatchResponse,
  unknown
> = z.object({
  success: types.boolean(),
  match: z.record(z.string(), z.any()),
  explain: z.record(z.string(), z.any()),
});

export function lucidMatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidMatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidMatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidMatchResponse' from JSON`,
  );
}
