/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidGetAgentRunProofSecurity = {
  adminAuth: string;
};

export type LucidGetAgentRunProofRequest = {
  /**
   * Agent passport identifier
   */
  passportId: string;
  /**
   * Specific inference run identifier for leaf-level proof
   */
  runId: string;
};

/** @internal */
export type LucidGetAgentRunProofSecurity$Outbound = {
  AdminAuth: string;
};

/** @internal */
export const LucidGetAgentRunProofSecurity$outboundSchema: z.ZodMiniType<
  LucidGetAgentRunProofSecurity$Outbound,
  LucidGetAgentRunProofSecurity
> = z.pipe(
  z.object({
    adminAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      adminAuth: "AdminAuth",
    });
  }),
);

export function lucidGetAgentRunProofSecurityToJSON(
  lucidGetAgentRunProofSecurity: LucidGetAgentRunProofSecurity,
): string {
  return JSON.stringify(
    LucidGetAgentRunProofSecurity$outboundSchema.parse(
      lucidGetAgentRunProofSecurity,
    ),
  );
}

/** @internal */
export type LucidGetAgentRunProofRequest$Outbound = {
  passportId: string;
  runId: string;
};

/** @internal */
export const LucidGetAgentRunProofRequest$outboundSchema: z.ZodMiniType<
  LucidGetAgentRunProofRequest$Outbound,
  LucidGetAgentRunProofRequest
> = z.object({
  passportId: z.string(),
  runId: z.string(),
});

export function lucidGetAgentRunProofRequestToJSON(
  lucidGetAgentRunProofRequest: LucidGetAgentRunProofRequest,
): string {
  return JSON.stringify(
    LucidGetAgentRunProofRequest$outboundSchema.parse(
      lucidGetAgentRunProofRequest,
    ),
  );
}
