/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidTerminateAgentRequest = {
  /**
   * Agent passport identifier to terminate
   */
  passportId: string;
};

/**
 * Agent terminated
 */
export type LucidTerminateAgentResponse = {
  success: boolean;
  message: string;
};

/** @internal */
export type LucidTerminateAgentRequest$Outbound = {
  passportId: string;
};

/** @internal */
export const LucidTerminateAgentRequest$outboundSchema: z.ZodMiniType<
  LucidTerminateAgentRequest$Outbound,
  LucidTerminateAgentRequest
> = z.object({
  passportId: z.string(),
});

export function lucidTerminateAgentRequestToJSON(
  lucidTerminateAgentRequest: LucidTerminateAgentRequest,
): string {
  return JSON.stringify(
    LucidTerminateAgentRequest$outboundSchema.parse(lucidTerminateAgentRequest),
  );
}

/** @internal */
export const LucidTerminateAgentResponse$inboundSchema: z.ZodMiniType<
  LucidTerminateAgentResponse,
  unknown
> = z.object({
  success: types.boolean(),
  message: types.string(),
});

export function lucidTerminateAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidTerminateAgentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidTerminateAgentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidTerminateAgentResponse' from JSON`,
  );
}
