/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidListMemoryEntriesRequest = {
  /**
   * Agent passport identifier to filter entries
   */
  agentPassportId?: string | undefined;
  /**
   * Memory type filter (episodic, semantic, procedural, entity, trust_weighted, temporal)
   */
  type?: string | undefined;
  /**
   * Namespace filter
   */
  namespace?: string | undefined;
  /**
   * Page number for pagination
   */
  page?: number | undefined;
  /**
   * Number of results per page
   */
  perPage?: number | undefined;
};

export type Pagination = {
  page?: number | undefined;
  perPage?: number | undefined;
  total?: number | undefined;
  totalPages?: number | undefined;
};

/**
 * OK
 */
export type LucidListMemoryEntriesResponse = {
  entries?: Array<{ [k: string]: any }> | undefined;
  pagination?: Pagination | undefined;
};

/** @internal */
export type LucidListMemoryEntriesRequest$Outbound = {
  agent_passport_id?: string | undefined;
  type?: string | undefined;
  namespace?: string | undefined;
  page: number;
  per_page: number;
};

/** @internal */
export const LucidListMemoryEntriesRequest$outboundSchema: z.ZodMiniType<
  LucidListMemoryEntriesRequest$Outbound,
  LucidListMemoryEntriesRequest
> = z.pipe(
  z.object({
    agentPassportId: z.optional(z.string()),
    type: z.optional(z.string()),
    namespace: z.optional(z.string()),
    page: z._default(z.int(), 1),
    perPage: z._default(z.int(), 20),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentPassportId: "agent_passport_id",
      perPage: "per_page",
    });
  }),
);

export function lucidListMemoryEntriesRequestToJSON(
  lucidListMemoryEntriesRequest: LucidListMemoryEntriesRequest,
): string {
  return JSON.stringify(
    LucidListMemoryEntriesRequest$outboundSchema.parse(
      lucidListMemoryEntriesRequest,
    ),
  );
}

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .pipe(
    z.object({
      page: types.optional(types.number()),
      per_page: types.optional(types.number()),
      total: types.optional(types.number()),
      total_pages: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "per_page": "perPage",
        "total_pages": "totalPages",
      });
    }),
  );

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const LucidListMemoryEntriesResponse$inboundSchema: z.ZodMiniType<
  LucidListMemoryEntriesResponse,
  unknown
> = z.object({
  entries: types.optional(z.array(z.record(z.string(), z.any()))),
  pagination: types.optional(z.lazy(() => Pagination$inboundSchema)),
});

export function lucidListMemoryEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidListMemoryEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListMemoryEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListMemoryEntriesResponse' from JSON`,
  );
}
