/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetReceiptBasedReputationRequest = {
  /**
   * Agent identifier for receipt-based reputation
   */
  agentId: string;
};

/**
 * Receipt-based score
 */
export type LucidGetReceiptBasedReputationResponse = {
  success: boolean;
  agentId?: string | undefined;
  score?: number | undefined;
  receiptCount?: number | undefined;
  verifiedCount?: number | undefined;
};

/** @internal */
export type LucidGetReceiptBasedReputationRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const LucidGetReceiptBasedReputationRequest$outboundSchema:
  z.ZodMiniType<
    LucidGetReceiptBasedReputationRequest$Outbound,
    LucidGetReceiptBasedReputationRequest
  > = z.object({
    agentId: z.string(),
  });

export function lucidGetReceiptBasedReputationRequestToJSON(
  lucidGetReceiptBasedReputationRequest: LucidGetReceiptBasedReputationRequest,
): string {
  return JSON.stringify(
    LucidGetReceiptBasedReputationRequest$outboundSchema.parse(
      lucidGetReceiptBasedReputationRequest,
    ),
  );
}

/** @internal */
export const LucidGetReceiptBasedReputationResponse$inboundSchema:
  z.ZodMiniType<LucidGetReceiptBasedReputationResponse, unknown> = z.object({
    success: types.boolean(),
    agentId: types.optional(types.string()),
    score: types.optional(types.number()),
    receiptCount: types.optional(types.number()),
    verifiedCount: types.optional(types.number()),
  });

export function lucidGetReceiptBasedReputationResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidGetReceiptBasedReputationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LucidGetReceiptBasedReputationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidGetReceiptBasedReputationResponse' from JSON`,
  );
}
