/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * OK
 */
export type LucidListChainsResponse = {
  success: boolean;
  count: number;
  chains: Array<models.ChainInfo>;
};

/** @internal */
export const LucidListChainsResponse$inboundSchema: z.ZodMiniType<
  LucidListChainsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  count: types.number(),
  chains: z.array(models.ChainInfo$inboundSchema),
});

export function lucidListChainsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LucidListChainsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LucidListChainsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LucidListChainsResponse' from JSON`,
  );
}
