/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type LucidSubmitEvidenceRequest = {
  /**
   * Dispute identifier for evidence submission
   */
  disputeId: string;
  body: models.SubmitEvidenceRequest;
};

/** @internal */
export type LucidSubmitEvidenceRequest$Outbound = {
  disputeId: string;
  body: models.SubmitEvidenceRequest$Outbound;
};

/** @internal */
export const LucidSubmitEvidenceRequest$outboundSchema: z.ZodMiniType<
  LucidSubmitEvidenceRequest$Outbound,
  LucidSubmitEvidenceRequest
> = z.object({
  disputeId: z.string(),
  body: models.SubmitEvidenceRequest$outboundSchema,
});

export function lucidSubmitEvidenceRequestToJSON(
  lucidSubmitEvidenceRequest: LucidSubmitEvidenceRequest,
): string {
  return JSON.stringify(
    LucidSubmitEvidenceRequest$outboundSchema.parse(lucidSubmitEvidenceRequest),
  );
}
