/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type LucidUpdatePassportEndpointsRequest = {
  /**
   * Passport identifier to update endpoints for
   */
  passportId: string;
  /**
   * Owner wallet address for ownership verification
   */
  xOwnerAddress?: string | undefined;
  body: models.UpdatePassportEndpointsRequest;
};

/** @internal */
export type LucidUpdatePassportEndpointsRequest$Outbound = {
  passport_id: string;
  "X-Owner-Address"?: string | undefined;
  body: models.UpdatePassportEndpointsRequest$Outbound;
};

/** @internal */
export const LucidUpdatePassportEndpointsRequest$outboundSchema: z.ZodMiniType<
  LucidUpdatePassportEndpointsRequest$Outbound,
  LucidUpdatePassportEndpointsRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    xOwnerAddress: z.optional(z.string()),
    body: models.UpdatePassportEndpointsRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
      xOwnerAddress: "X-Owner-Address",
    });
  }),
);

export function lucidUpdatePassportEndpointsRequestToJSON(
  lucidUpdatePassportEndpointsRequest: LucidUpdatePassportEndpointsRequest,
): string {
  return JSON.stringify(
    LucidUpdatePassportEndpointsRequest$outboundSchema.parse(
      lucidUpdatePassportEndpointsRequest,
    ),
  );
}
