/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LucidGetAgentOrchestratorHistoryRequest = {
  /**
   * Tenant identifier for execution history lookup
   */
  tenantId: string;
  /**
   * Maximum number of history entries to return
   */
  limit?: number | undefined;
};

/**
 * OK
 */
export type LucidGetAgentOrchestratorHistoryResponse = {
  success: boolean;
  tenantId: string;
  history: Array<{ [k: string]: any }>;
  stats?: { [k: string]: any } | undefined;
  message?: string | undefined;
};

/** @internal */
export type LucidGetAgentOrchestratorHistoryRequest$Outbound = {
  tenantId: string;
  limit?: number | undefined;
};

/** @internal */
export const LucidGetAgentOrchestratorHistoryRequest$outboundSchema:
  z.ZodMiniType<
    LucidGetAgentOrchestratorHistoryRequest$Outbound,
    LucidGetAgentOrchestratorHistoryRequest
  > = z.object({
    tenantId: z.string(),
    limit: z.optional(z.int()),
  });

export function lucidGetAgentOrchestratorHistoryRequestToJSON(
  lucidGetAgentOrchestratorHistoryRequest:
    LucidGetAgentOrchestratorHistoryRequest,
): string {
  return JSON.stringify(
    LucidGetAgentOrchestratorHistoryRequest$outboundSchema.parse(
      lucidGetAgentOrchestratorHistoryRequest,
    ),
  );
}

/** @internal */
export const LucidGetAgentOrchestratorHistoryResponse$inboundSchema:
  z.ZodMiniType<LucidGetAgentOrchestratorHistoryResponse, unknown> = z.object({
    success: types.boolean(),
    tenantId: types.string(),
    history: z.array(z.record(z.string(), z.any())),
    stats: types.optional(z.record(z.string(), z.any())),
    message: types.optional(types.string()),
  });

export function lucidGetAgentOrchestratorHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LucidGetAgentOrchestratorHistoryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LucidGetAgentOrchestratorHistoryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LucidGetAgentOrchestratorHistoryResponse' from JSON`,
  );
}
