/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const LucidAddTrustWeightedMemoryMemoryLane = {
  Self: "self",
  User: "user",
  Shared: "shared",
  Market: "market",
} as const;
export type LucidAddTrustWeightedMemoryMemoryLane = ClosedEnum<
  typeof LucidAddTrustWeightedMemoryMemoryLane
>;

export type LucidAddTrustWeightedMemoryRequestBody = {
  sourceAgentPassportId: string;
  trustScore?: number | undefined;
  decayFactor?: number | undefined;
  weightedRelevance?: number | undefined;
  content?: string | undefined;
  namespace?: string | undefined;
  memoryLane?: LucidAddTrustWeightedMemoryMemoryLane | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export type LucidAddTrustWeightedMemoryRequest = {
  xAgentPassportId: string;
  body: LucidAddTrustWeightedMemoryRequestBody;
};

/** @internal */
export const LucidAddTrustWeightedMemoryMemoryLane$outboundSchema:
  z.ZodMiniEnum<typeof LucidAddTrustWeightedMemoryMemoryLane> = z.enum(
    LucidAddTrustWeightedMemoryMemoryLane,
  );

/** @internal */
export type LucidAddTrustWeightedMemoryRequestBody$Outbound = {
  source_agent_passport_id: string;
  trust_score?: number | undefined;
  decay_factor?: number | undefined;
  weighted_relevance?: number | undefined;
  content?: string | undefined;
  namespace?: string | undefined;
  memory_lane?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const LucidAddTrustWeightedMemoryRequestBody$outboundSchema:
  z.ZodMiniType<
    LucidAddTrustWeightedMemoryRequestBody$Outbound,
    LucidAddTrustWeightedMemoryRequestBody
  > = z.pipe(
    z.object({
      sourceAgentPassportId: z.string(),
      trustScore: z.optional(z.number()),
      decayFactor: z.optional(z.number()),
      weightedRelevance: z.optional(z.number()),
      content: z.optional(z.string()),
      namespace: z.optional(z.string()),
      memoryLane: z.optional(
        LucidAddTrustWeightedMemoryMemoryLane$outboundSchema,
      ),
      metadata: z.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        sourceAgentPassportId: "source_agent_passport_id",
        trustScore: "trust_score",
        decayFactor: "decay_factor",
        weightedRelevance: "weighted_relevance",
        memoryLane: "memory_lane",
      });
    }),
  );

export function lucidAddTrustWeightedMemoryRequestBodyToJSON(
  lucidAddTrustWeightedMemoryRequestBody:
    LucidAddTrustWeightedMemoryRequestBody,
): string {
  return JSON.stringify(
    LucidAddTrustWeightedMemoryRequestBody$outboundSchema.parse(
      lucidAddTrustWeightedMemoryRequestBody,
    ),
  );
}

/** @internal */
export type LucidAddTrustWeightedMemoryRequest$Outbound = {
  "X-Agent-Passport-Id": string;
  body: LucidAddTrustWeightedMemoryRequestBody$Outbound;
};

/** @internal */
export const LucidAddTrustWeightedMemoryRequest$outboundSchema: z.ZodMiniType<
  LucidAddTrustWeightedMemoryRequest$Outbound,
  LucidAddTrustWeightedMemoryRequest
> = z.pipe(
  z.object({
    xAgentPassportId: z.string(),
    body: z.lazy(() => LucidAddTrustWeightedMemoryRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xAgentPassportId: "X-Agent-Passport-Id",
    });
  }),
);

export function lucidAddTrustWeightedMemoryRequestToJSON(
  lucidAddTrustWeightedMemoryRequest: LucidAddTrustWeightedMemoryRequest,
): string {
  return JSON.stringify(
    LucidAddTrustWeightedMemoryRequest$outboundSchema.parse(
      lucidAddTrustWeightedMemoryRequest,
    ),
  );
}
