/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidGetIdentityChainsRequest = {
  /**
   * CAIP-10 address to query chains for
   */
  caip10: string;
};

/** @internal */
export type LucidGetIdentityChainsRequest$Outbound = {
  caip10: string;
};

/** @internal */
export const LucidGetIdentityChainsRequest$outboundSchema: z.ZodMiniType<
  LucidGetIdentityChainsRequest$Outbound,
  LucidGetIdentityChainsRequest
> = z.object({
  caip10: z.string(),
});

export function lucidGetIdentityChainsRequestToJSON(
  lucidGetIdentityChainsRequest: LucidGetIdentityChainsRequest,
): string {
  return JSON.stringify(
    LucidGetIdentityChainsRequest$outboundSchema.parse(
      lucidGetIdentityChainsRequest,
    ),
  );
}
