/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PreviewAgentWorkflowRequest = {
  goal: string;
  context?: { [k: string]: any } | undefined;
};

/**
 * OK
 */
export type PreviewAgentWorkflowResponse = {
  success: boolean;
  preview: { [k: string]: any };
  flowspec: { [k: string]: any };
  reasoning?: string | undefined;
};

/** @internal */
export type PreviewAgentWorkflowRequest$Outbound = {
  goal: string;
  context?: { [k: string]: any } | undefined;
};

/** @internal */
export const PreviewAgentWorkflowRequest$outboundSchema: z.ZodMiniType<
  PreviewAgentWorkflowRequest$Outbound,
  PreviewAgentWorkflowRequest
> = z.object({
  goal: z.string(),
  context: z.optional(z.record(z.string(), z.any())),
});

export function previewAgentWorkflowRequestToJSON(
  previewAgentWorkflowRequest: PreviewAgentWorkflowRequest,
): string {
  return JSON.stringify(
    PreviewAgentWorkflowRequest$outboundSchema.parse(
      previewAgentWorkflowRequest,
    ),
  );
}

/** @internal */
export const PreviewAgentWorkflowResponse$inboundSchema: z.ZodMiniType<
  PreviewAgentWorkflowResponse,
  unknown
> = z.object({
  success: types.boolean(),
  preview: z.record(z.string(), z.any()),
  flowspec: z.record(z.string(), z.any()),
  reasoning: types.optional(types.string()),
});

export function previewAgentWorkflowResponseFromJSON(
  jsonString: string,
): SafeParseResult<PreviewAgentWorkflowResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewAgentWorkflowResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewAgentWorkflowResponse' from JSON`,
  );
}
