/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * OK
 */
export type ProcessAgentEpochResponse = {
  success: boolean;
  agentId: string;
  epochNumber: number;
  vectorCount: number;
  mmrRoot: string;
  ipfsCid?: string | undefined;
  transactionSignature?: string | undefined;
  gasCost?: models.GasCost | undefined;
  message?: string | undefined;
};

/** @internal */
export const ProcessAgentEpochResponse$inboundSchema: z.ZodMiniType<
  ProcessAgentEpochResponse,
  unknown
> = z.object({
  success: types.boolean(),
  agentId: types.string(),
  epochNumber: types.number(),
  vectorCount: types.number(),
  mmrRoot: types.string(),
  ipfsCid: types.optional(types.string()),
  transactionSignature: types.optional(types.string()),
  gasCost: types.optional(models.GasCost$inboundSchema),
  message: types.optional(types.string()),
});

export function processAgentEpochResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProcessAgentEpochResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProcessAgentEpochResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProcessAgentEpochResponse' from JSON`,
  );
}
