/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VerifyAgentMmrRequest = {
  agentId: string;
};

/**
 * OK
 */
export type VerifyAgentMmrResponse = {
  success: boolean;
  agentId: string;
  verification: { [k: string]: any };
  message?: string | undefined;
};

/** @internal */
export type VerifyAgentMmrRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const VerifyAgentMmrRequest$outboundSchema: z.ZodMiniType<
  VerifyAgentMmrRequest$Outbound,
  VerifyAgentMmrRequest
> = z.object({
  agentId: z.string(),
});

export function verifyAgentMmrRequestToJSON(
  verifyAgentMmrRequest: VerifyAgentMmrRequest,
): string {
  return JSON.stringify(
    VerifyAgentMmrRequest$outboundSchema.parse(verifyAgentMmrRequest),
  );
}

/** @internal */
export const VerifyAgentMmrResponse$inboundSchema: z.ZodMiniType<
  VerifyAgentMmrResponse,
  unknown
> = z.object({
  success: types.boolean(),
  agentId: types.string(),
  verification: z.record(z.string(), z.any()),
  message: types.optional(types.string()),
});

export function verifyAgentMmrResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerifyAgentMmrResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyAgentMmrResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyAgentMmrResponse' from JSON`,
  );
}
