/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { RaijinlabsMcpCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$computeLucidGetHealth } from "./tools/computeLucidGetHealth.js";
import { tool$computeLucidHeartbeat } from "./tools/computeLucidHeartbeat.js";
import { tool$epochsLucidCommitEpochRoot } from "./tools/epochsLucidCommitEpochRoot.js";
import { tool$epochsLucidCommitEpochRootsBatch } from "./tools/epochsLucidCommitEpochRootsBatch.js";
import { tool$epochsLucidCreateEpoch } from "./tools/epochsLucidCreateEpoch.js";
import { tool$epochsLucidGetAnchoringHealth } from "./tools/epochsLucidGetAnchoringHealth.js";
import { tool$epochsLucidGetCurrentEpoch } from "./tools/epochsLucidGetCurrentEpoch.js";
import { tool$epochsLucidGetEpoch } from "./tools/epochsLucidGetEpoch.js";
import { tool$epochsLucidGetEpochStats } from "./tools/epochsLucidGetEpochStats.js";
import { tool$epochsLucidGetEpochTransaction } from "./tools/epochsLucidGetEpochTransaction.js";
import { tool$epochsLucidListEpochs } from "./tools/epochsLucidListEpochs.js";
import { tool$epochsLucidListEpochsReady } from "./tools/epochsLucidListEpochsReady.js";
import { tool$epochsLucidRetryEpoch } from "./tools/epochsLucidRetryEpoch.js";
import { tool$epochsLucidVerifyEpoch } from "./tools/epochsLucidVerifyEpoch.js";
import { tool$matchLucidMatch } from "./tools/matchLucidMatch.js";
import { tool$matchLucidMatchExplain } from "./tools/matchLucidMatchExplain.js";
import { tool$matchLucidRoute } from "./tools/matchLucidRoute.js";
import { tool$passportsLucidCreatePassport } from "./tools/passportsLucidCreatePassport.js";
import { tool$passportsLucidDeletePassport } from "./tools/passportsLucidDeletePassport.js";
import { tool$passportsLucidGetPassport } from "./tools/passportsLucidGetPassport.js";
import { tool$passportsLucidGetPassportStats } from "./tools/passportsLucidGetPassportStats.js";
import { tool$passportsLucidListPassports } from "./tools/passportsLucidListPassports.js";
import { tool$passportsLucidListPassportsPendingSync } from "./tools/passportsLucidListPassportsPendingSync.js";
import { tool$passportsLucidSearchCompute } from "./tools/passportsLucidSearchCompute.js";
import { tool$passportsLucidSearchModels } from "./tools/passportsLucidSearchModels.js";
import { tool$passportsLucidTriggerPassportSync } from "./tools/passportsLucidTriggerPassportSync.js";
import { tool$passportsLucidUpdatePassport } from "./tools/passportsLucidUpdatePassport.js";
import { tool$payoutsLucidCalculatePayout } from "./tools/payoutsLucidCalculatePayout.js";
import { tool$payoutsLucidGetPayout } from "./tools/payoutsLucidGetPayout.js";
import { tool$payoutsLucidPayoutFromReceipt } from "./tools/payoutsLucidPayoutFromReceipt.js";
import { tool$payoutsLucidVerifyPayout } from "./tools/payoutsLucidVerifyPayout.js";
import { tool$receiptsLucidCreateReceipt } from "./tools/receiptsLucidCreateReceipt.js";
import { tool$receiptsLucidGetMmrRoot } from "./tools/receiptsLucidGetMmrRoot.js";
import { tool$receiptsLucidGetReceipt } from "./tools/receiptsLucidGetReceipt.js";
import { tool$receiptsLucidGetReceiptProof } from "./tools/receiptsLucidGetReceiptProof.js";
import { tool$receiptsLucidGetSignerPubkey } from "./tools/receiptsLucidGetSignerPubkey.js";
import { tool$receiptsLucidVerifyReceipt } from "./tools/receiptsLucidVerifyReceipt.js";
import { tool$runLucidChatCompletions } from "./tools/runLucidChatCompletions.js";
import { tool$runLucidRunInference } from "./tools/runLucidRunInference.js";
import { tool$passportsLucidListTools } from "./tools/passportsLucidListTools.js";
import { tool$passportsLucidListDatasets } from "./tools/passportsLucidListDatasets.js";
import { tool$passportsLucidListAgentPassports } from "./tools/passportsLucidListAgentPassports.js";
import { tool$receiptsLucidVerifyReceiptByHash } from "./tools/receiptsLucidVerifyReceiptByHash.js";
import { tool$healthCheckSystemHealth } from "./tools/healthCheckSystemHealth.js";
import { tool$healthCheckLiveness } from "./tools/healthCheckLiveness.js";
import { tool$healthCheckReadiness } from "./tools/healthCheckReadiness.js";
import { tool$healthCheckDatabaseHealth } from "./tools/healthCheckDatabaseHealth.js";
import { tool$healthCheckRedisHealth } from "./tools/healthCheckRedisHealth.js";
import { tool$healthCheckNangoHealth } from "./tools/healthCheckNangoHealth.js";
import { tool$healthGetDetailedHealth } from "./tools/healthGetDetailedHealth.js";
import { tool$agentsInitAgent } from "./tools/agentsInitAgent.js";
import { tool$agentsProcessAgentEpoch } from "./tools/agentsProcessAgentEpoch.js";
import { tool$agentsProcessAgentBatchEpochs } from "./tools/agentsProcessAgentBatchEpochs.js";
import { tool$agentsGenerateAgentProof } from "./tools/agentsGenerateAgentProof.js";
import { tool$agentsGetAgentStats } from "./tools/agentsGetAgentStats.js";
import { tool$agentsGetAgentHistory } from "./tools/agentsGetAgentHistory.js";
import { tool$agentsGetAgentRoot } from "./tools/agentsGetAgentRoot.js";
import { tool$agentsVerifyAgentMmr } from "./tools/agentsVerifyAgentMmr.js";
import { tool$agentsListAgents } from "./tools/agentsListAgents.js";
import { tool$agentsPlanAgentWorkflow } from "./tools/agentsPlanAgentWorkflow.js";
import { tool$agentsAccomplishAgentGoal } from "./tools/agentsAccomplishAgentGoal.js";
import { tool$agentsPreviewAgentWorkflow } from "./tools/agentsPreviewAgentWorkflow.js";
import { tool$agentsGetAgentOrchestratorHistory } from "./tools/agentsGetAgentOrchestratorHistory.js";
import { tool$agentsCheckAgentOrchestratorHealth } from "./tools/agentsCheckAgentOrchestratorHealth.js";
import { tool$agentsExecuteAgentFlowspec } from "./tools/agentsExecuteAgentFlowspec.js";
import { tool$agentsValidateFlowspec } from "./tools/agentsValidateFlowspec.js";
import { tool$agentsGetPlannerInfo } from "./tools/agentsGetPlannerInfo.js";
import { tool$agentsCheckExecutorHealth } from "./tools/agentsCheckExecutorHealth.js";
import { tool$agentsGetExecutorDecision } from "./tools/agentsGetExecutorDecision.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => RaijinlabsMcpCore;
  serverURL?: string | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "RaijinlabsMcp",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new RaijinlabsMcpCore({
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$passportsLucidCreatePassport);
  tool(tool$passportsLucidListPassports);
  tool(tool$passportsLucidGetPassport);
  tool(tool$passportsLucidUpdatePassport);
  tool(tool$passportsLucidDeletePassport);
  tool(tool$passportsLucidTriggerPassportSync);
  tool(tool$passportsLucidListPassportsPendingSync);
  tool(tool$passportsLucidGetPassportStats);
  tool(tool$passportsLucidSearchModels);
  tool(tool$passportsLucidSearchCompute);
  tool(tool$matchLucidMatchExplain);
  tool(tool$matchLucidMatch);
  tool(tool$matchLucidRoute);
  tool(tool$runLucidRunInference);
  tool(tool$runLucidChatCompletions);
  tool(tool$computeLucidHeartbeat);
  tool(tool$computeLucidGetHealth);
  tool(tool$receiptsLucidCreateReceipt);
  tool(tool$receiptsLucidGetReceipt);
  tool(tool$receiptsLucidVerifyReceipt);
  tool(tool$receiptsLucidGetReceiptProof);
  tool(tool$receiptsLucidGetMmrRoot);
  tool(tool$receiptsLucidGetSignerPubkey);
  tool(tool$epochsLucidGetCurrentEpoch);
  tool(tool$epochsLucidListEpochs);
  tool(tool$epochsLucidCreateEpoch);
  tool(tool$epochsLucidGetEpoch);
  tool(tool$epochsLucidRetryEpoch);
  tool(tool$epochsLucidVerifyEpoch);
  tool(tool$epochsLucidGetEpochTransaction);
  tool(tool$epochsLucidCommitEpochRoot);
  tool(tool$epochsLucidCommitEpochRootsBatch);
  tool(tool$epochsLucidGetAnchoringHealth);
  tool(tool$epochsLucidListEpochsReady);
  tool(tool$epochsLucidGetEpochStats);
  tool(tool$payoutsLucidCalculatePayout);
  tool(tool$payoutsLucidPayoutFromReceipt);
  tool(tool$payoutsLucidGetPayout);
  tool(tool$payoutsLucidVerifyPayout);
  tool(tool$passportsLucidListTools);
  tool(tool$passportsLucidListDatasets);
  tool(tool$passportsLucidListAgentPassports);
  tool(tool$receiptsLucidVerifyReceiptByHash);
  tool(tool$healthCheckSystemHealth);
  tool(tool$healthCheckLiveness);
  tool(tool$healthCheckReadiness);
  tool(tool$healthCheckDatabaseHealth);
  tool(tool$healthCheckRedisHealth);
  tool(tool$healthCheckNangoHealth);
  tool(tool$healthGetDetailedHealth);
  tool(tool$agentsInitAgent);
  tool(tool$agentsProcessAgentEpoch);
  tool(tool$agentsProcessAgentBatchEpochs);
  tool(tool$agentsGenerateAgentProof);
  tool(tool$agentsGetAgentStats);
  tool(tool$agentsGetAgentHistory);
  tool(tool$agentsGetAgentRoot);
  tool(tool$agentsVerifyAgentMmr);
  tool(tool$agentsListAgents);
  tool(tool$agentsPlanAgentWorkflow);
  tool(tool$agentsAccomplishAgentGoal);
  tool(tool$agentsPreviewAgentWorkflow);
  tool(tool$agentsGetAgentOrchestratorHistory);
  tool(tool$agentsCheckAgentOrchestratorHealth);
  tool(tool$agentsExecuteAgentFlowspec);
  tool(tool$agentsValidateFlowspec);
  tool(tool$agentsGetPlannerInfo);
  tool(tool$agentsCheckExecutorHealth);
  tool(tool$agentsGetExecutorDecision);

  return { server, tools };
}
