/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type { AgentAccomplishRequest } from "./agentaccomplishrequest.js";
export { AgentAccomplishRequest$zodSchema } from "./agentaccomplishrequest.js";

/**
 * OK
 */
export type AccomplishAgentGoalResponseBody = {
  success: boolean;
  goal: string;
  result?: any | undefined;
  execution?: any | undefined;
};

export const AccomplishAgentGoalResponseBody$zodSchema: z.ZodType<
  AccomplishAgentGoalResponseBody
> = z.object({
  execution: z.any().optional(),
  goal: z.string(),
  result: z.any().optional(),
  success: z.boolean(),
}).describe("OK");

export type AccomplishAgentGoalResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: AccomplishAgentGoalResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const AccomplishAgentGoalResponse$zodSchema: z.ZodType<
  AccomplishAgentGoalResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => AccomplishAgentGoalResponseBody$zodSchema).optional(),
});
