/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentBatchEpochsRequest = {
  epochs: Array<{
    agentId: string;
    vectors: Array<string>;
    epochNumber?: number | undefined;
  }>;
};

export const AgentBatchEpochsRequest$zodSchema: z.ZodType<
  AgentBatchEpochsRequest
> = z.object({
  epochs: z.array(z.object({
    agentId: z.string(),
    epochNumber: z.number().int().optional(),
    vectors: z.array(z.string()),
  })),
});
