/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentStats = {
  agentId?: string | undefined;
  totalEpochs?: number | undefined;
  totalVectors?: number | undefined;
  currentRoot?: string | undefined;
  lastEpoch?: number | undefined;
  createdAt?: string | undefined;
};

export const AgentStats$zodSchema: z.ZodType<AgentStats> = z.object({
  agentId: z.string().optional(),
  createdAt: z.string().optional(),
  currentRoot: z.string().optional(),
  lastEpoch: z.number().int().optional(),
  totalEpochs: z.number().int().optional(),
  totalVectors: z.number().int().optional(),
});
