/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentInitRequest = {
  agentId: string;
  ipfsCid?: string | undefined;
};

export const AgentInitRequest$zodSchema: z.ZodType<AgentInitRequest> = z
  .object({
    agentId: z.string(),
    ipfsCid: z.string().optional(),
  });
