/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentPlanRequest = {
  goal: string;
  context?: { [k: string]: any } | undefined;
  constraints?: Array<string> | undefined;
  autoExecute?: boolean | undefined;
};

export const AgentPlanRequest$zodSchema: z.ZodType<AgentPlanRequest> = z
  .object({
    autoExecute: z.boolean().optional(),
    constraints: z.array(z.string()).optional(),
    context: z.record(z.string(), z.any()).optional(),
    goal: z.string(),
  });
