/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChatMessage, ChatMessage$zodSchema } from "./chatmessage.js";
import { Policy, Policy$zodSchema } from "./policy.js";

export type Stop = string | Array<string>;

export const Stop$zodSchema: z.ZodType<Stop> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ChatCompletionRequest = {
  model: string;
  messages: Array<ChatMessage>;
  max_tokens?: number | undefined;
  temperature?: number | undefined;
  top_p?: number | undefined;
  stop?: string | Array<string> | undefined;
  stream?: boolean | undefined;
  policy?: Policy | undefined;
  trace_id?: string | undefined;
};

export const ChatCompletionRequest$zodSchema: z.ZodType<ChatCompletionRequest> =
  z.object({
    max_tokens: z.int().optional(),
    messages: z.array(ChatMessage$zodSchema),
    model: z.string(),
    policy: Policy$zodSchema.optional(),
    stop: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    stream: z.boolean().optional(),
    temperature: z.number().optional(),
    top_p: z.number().optional(),
    trace_id: z.string().optional(),
  });
