/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChatMessage, ChatMessage$zodSchema } from "./chatmessage.js";

export type Choice = {
  index?: number | undefined;
  message?: ChatMessage | undefined;
  finish_reason?: string | null | undefined;
};

export const Choice$zodSchema: z.ZodType<Choice> = z.object({
  finish_reason: z.string().nullable().optional(),
  index: z.int().optional(),
  message: ChatMessage$zodSchema.optional(),
});

export type Usage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};

export const Usage$zodSchema: z.ZodType<Usage> = z.object({
  completion_tokens: z.int(),
  prompt_tokens: z.int(),
  total_tokens: z.int(),
});

export type ChatCompletionResponse = {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: Array<Choice>;
  usage: Usage;
};

export const ChatCompletionResponse$zodSchema: z.ZodType<
  ChatCompletionResponse
> = z.object({
  choices: z.array(z.lazy(() => Choice$zodSchema)),
  created: z.int(),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  usage: z.lazy(() => Usage$zodSchema),
});
