/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

/**
 * OK
 */
export type CheckLivenessResponseBody = {
  status: string;
  timestamp: string;
  uptime: number;
};

export const CheckLivenessResponseBody$zodSchema: z.ZodType<
  CheckLivenessResponseBody
> = z.object({
  status: z.string(),
  timestamp: z.string(),
  uptime: z.number(),
}).describe("OK");

export type CheckLivenessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CheckLivenessResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const CheckLivenessResponse$zodSchema: z.ZodType<
  CheckLivenessResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => CheckLivenessResponseBody$zodSchema).optional(),
});
