/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

/**
 * OK
 */
export type CheckReadinessResponseBody = {
  status: string;
  timestamp?: string | undefined;
  dependencies?: { [k: string]: any } | undefined;
};

export const CheckReadinessResponseBody$zodSchema: z.ZodType<
  CheckReadinessResponseBody
> = z.object({
  dependencies: z.record(z.string(), z.any()).optional(),
  status: z.string(),
  timestamp: z.string().optional(),
}).describe("OK");

export type CheckReadinessResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CheckReadinessResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const CheckReadinessResponse$zodSchema: z.ZodType<
  CheckReadinessResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => CheckReadinessResponseBody$zodSchema).optional(),
});
