/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

/**
 * OK
 */
export type CheckExecutorHealthResponseBody = {
  success: boolean;
  executors?: {
    n8n?: boolean | undefined;
    langgraph?: boolean | undefined;
  } | undefined;
  message?: string | undefined;
};

export const CheckExecutorHealthResponseBody$zodSchema: z.ZodType<
  CheckExecutorHealthResponseBody
> = z.object({
  executors: z.object({
    langgraph: z.boolean().optional(),
    n8n: z.boolean().optional(),
  }).optional(),
  message: z.string().optional(),
  success: z.boolean(),
}).describe("OK");

export type CheckExecutorHealthResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CheckExecutorHealthResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const CheckExecutorHealthResponse$zodSchema: z.ZodType<
  CheckExecutorHealthResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => CheckExecutorHealthResponseBody$zodSchema).optional(),
});
