/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PassportType, PassportType$zodSchema } from "./passporttype.js";

export type CreatePassportRequest = {
  type: PassportType;
  owner: string;
  metadata: { [k: string]: any };
  name?: string | undefined;
  description?: string | undefined;
  version?: string | undefined;
  tags?: Array<string> | undefined;
};

export const CreatePassportRequest$zodSchema: z.ZodType<CreatePassportRequest> =
  z.object({
    description: z.string().optional(),
    metadata: z.record(z.string(), z.any()),
    name: z.string().optional(),
    owner: z.string(),
    tags: z.array(z.string()).optional(),
    type: PassportType$zodSchema,
    version: z.string().optional(),
  });
