/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Passport, Passport$zodSchema } from "./passport.js";

export type CreatePassportResponse = {
  success: boolean;
  passport_id: string;
  passport: Passport;
};

export const CreatePassportResponse$zodSchema: z.ZodType<
  CreatePassportResponse
> = z.object({
  passport: Passport$zodSchema,
  passport_id: z.string(),
  success: z.boolean(),
});
