/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type ExecuteAgentFlowspecRequest = {
  flowspec: any;
  context: {
    tenantId: string;
    variables?: any | undefined;
  };
  executor?: string | undefined;
};

export const ExecuteAgentFlowspecRequest$zodSchema: z.ZodType<
  ExecuteAgentFlowspecRequest
> = z.object({
  context: z.object({
    tenantId: z.string(),
    variables: z.any().optional(),
  }),
  executor: z.string().optional(),
  flowspec: z.any(),
});

/**
 * OK
 */
export type ExecuteAgentFlowspecResponseBody = {
  success: boolean;
  result?: any | undefined;
};

export const ExecuteAgentFlowspecResponseBody$zodSchema: z.ZodType<
  ExecuteAgentFlowspecResponseBody
> = z.object({
  result: z.any().optional(),
  success: z.boolean(),
}).describe("OK");

export type ExecuteAgentFlowspecResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ExecuteAgentFlowspecResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const ExecuteAgentFlowspecResponse$zodSchema: z.ZodType<
  ExecuteAgentFlowspecResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => ExecuteAgentFlowspecResponseBody$zodSchema).optional(),
});
