/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GasCost = {
  iGas: number;
  mGas: number;
  total: number;
};

export const GasCost$zodSchema: z.ZodType<GasCost> = z.object({
  iGas: z.number().int(),
  mGas: z.number().int(),
  total: z.number().int(),
});
