/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetAgentStatsRequest = {
  agentId: string;
};

export const GetAgentStatsRequest$zodSchema: z.ZodType<GetAgentStatsRequest> =
  z.object({
    agentId: z.string(),
  });

/**
 * OK
 */
export type GetAgentStatsResponseBody = {
  success: boolean;
  stats: any;
  message?: string | undefined;
};

export const GetAgentStatsResponseBody$zodSchema: z.ZodType<
  GetAgentStatsResponseBody
> = z.object({
  message: z.string().optional(),
  stats: z.any(),
  success: z.boolean(),
}).describe("OK");

export type GetAgentStatsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetAgentStatsResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const GetAgentStatsResponse$zodSchema: z.ZodType<
  GetAgentStatsResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => GetAgentStatsResponseBody$zodSchema).optional(),
});
