/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetAgentOrchestratorHistoryRequest = {
  tenantId: string;
  limit?: number | undefined;
};

export const GetAgentOrchestratorHistoryRequest$zodSchema: z.ZodType<
  GetAgentOrchestratorHistoryRequest
> = z.object({
  limit: z.number().int().optional(),
  tenantId: z.string(),
});

/**
 * OK
 */
export type GetAgentOrchestratorHistoryResponseBody = {
  success: boolean;
  tenantId: string;
  history: Array<any>;
  stats?: any | undefined;
  message?: string | undefined;
};

export const GetAgentOrchestratorHistoryResponseBody$zodSchema: z.ZodType<
  GetAgentOrchestratorHistoryResponseBody
> = z.object({
  history: z.array(z.any()),
  message: z.string().optional(),
  stats: z.any().optional(),
  success: z.boolean(),
  tenantId: z.string(),
}).describe("OK");

export type GetAgentOrchestratorHistoryResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetAgentOrchestratorHistoryResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const GetAgentOrchestratorHistoryResponse$zodSchema: z.ZodType<
  GetAgentOrchestratorHistoryResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => GetAgentOrchestratorHistoryResponseBody$zodSchema).optional(),
});
