/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetAgentHistoryRequest = {
  agentId: string;
};

export const GetAgentHistoryRequest$zodSchema: z.ZodType<
  GetAgentHistoryRequest
> = z.object({
  agentId: z.string(),
});

/**
 * OK
 */
export type GetAgentHistoryResponseBody = {
  success: boolean;
  agentId: string;
  history: Array<any>;
  totalEpochs: number;
  message?: string | undefined;
};

export const GetAgentHistoryResponseBody$zodSchema: z.ZodType<
  GetAgentHistoryResponseBody
> = z.object({
  agentId: z.string(),
  history: z.array(z.any()),
  message: z.string().optional(),
  success: z.boolean(),
  totalEpochs: z.number().int(),
}).describe("OK");

export type GetAgentHistoryResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetAgentHistoryResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const GetAgentHistoryResponse$zodSchema: z.ZodType<
  GetAgentHistoryResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => GetAgentHistoryResponseBody$zodSchema).optional(),
});
