/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InferenceResult = {
  success: boolean;
  run_id: string;
  request_id?: string | undefined;
  trace_id?: string | undefined;
  text?: string | undefined;
  finish_reason?: string | undefined;
  tokens_in: number;
  tokens_out: number;
  ttft_ms: number;
  total_latency_ms: number;
  model_passport_id: string;
  compute_passport_id: string;
  runtime: string;
  policy_hash?: string | undefined;
  receipt_id?: string | undefined;
  used_fallback?: boolean | undefined;
  fallback_reason?: string | undefined;
  error?: string | undefined;
  error_code?: string | undefined;
};

export const InferenceResult$zodSchema: z.ZodType<InferenceResult> = z.object({
  compute_passport_id: z.string(),
  error: z.string().optional(),
  error_code: z.string().optional(),
  fallback_reason: z.string().optional(),
  finish_reason: z.string().optional(),
  model_passport_id: z.string(),
  policy_hash: z.string().optional(),
  receipt_id: z.string().optional(),
  request_id: z.string().optional(),
  run_id: z.string(),
  runtime: z.string(),
  success: z.boolean(),
  text: z.string().optional(),
  tokens_in: z.int(),
  tokens_out: z.int(),
  total_latency_ms: z.int(),
  trace_id: z.string().optional(),
  ttft_ms: z.int(),
  used_fallback: z.boolean().optional(),
});
