/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidGetEpochRequest = { epoch_id: string };

export const LucidGetEpochRequest$zodSchema: z.ZodType<LucidGetEpochRequest> = z
  .object({
    epoch_id: z.string(),
  });

export type LucidGetEpochResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidGetEpochResponse$zodSchema: z.ZodType<LucidGetEpochResponse> =
  z.object({
    ContentType: z.string(),
    ErrorResponse: ErrorResponse$zodSchema.optional(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
  });
