/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { Policy, Policy$zodSchema } from "./policy.js";

export type LucidMatchExplainRequest = {
  policy?: Policy | undefined;
  compute_meta?: { [k: string]: any } | undefined;
  model_meta?: { [k: string]: any } | undefined;
};

export const LucidMatchExplainRequest$zodSchema: z.ZodType<
  LucidMatchExplainRequest
> = z.object({
  compute_meta: z.record(z.string(), z.any()).optional(),
  model_meta: z.record(z.string(), z.any()).optional(),
  policy: Policy$zodSchema.optional(),
});

export type LucidMatchExplainResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidMatchExplainResponse$zodSchema: z.ZodType<
  LucidMatchExplainResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
