/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

/**
 * OK
 */
export type LucidGetMmrRootResponseBody = {
  success: boolean;
  root: string;
  leaf_count: number;
};

export const LucidGetMmrRootResponseBody$zodSchema: z.ZodType<
  LucidGetMmrRootResponseBody
> = z.object({
  leaf_count: z.int(),
  root: z.string(),
  success: z.boolean(),
}).describe("OK");

export type LucidGetMmrRootResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: LucidGetMmrRootResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidGetMmrRootResponse$zodSchema: z.ZodType<
  LucidGetMmrRootResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => LucidGetMmrRootResponseBody$zodSchema).optional(),
});
