/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidRetryEpochRequest = { epoch_id: string };

export const LucidRetryEpochRequest$zodSchema: z.ZodType<
  LucidRetryEpochRequest
> = z.object({
  epoch_id: z.string(),
});

export type LucidRetryEpochResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidRetryEpochResponse$zodSchema: z.ZodType<
  LucidRetryEpochResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
