/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidCommitEpochRootsBatchRequest = { epoch_ids: Array<string> };

export const LucidCommitEpochRootsBatchRequest$zodSchema: z.ZodType<
  LucidCommitEpochRootsBatchRequest
> = z.object({
  epoch_ids: z.array(z.string()),
});

export type LucidCommitEpochRootsBatchResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidCommitEpochRootsBatchResponse$zodSchema: z.ZodType<
  LucidCommitEpochRootsBatchResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
