/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetPassportResponse,
  GetPassportResponse$zodSchema,
} from "./getpassportresponse.js";
import {
  UpdatePassportRequest,
  UpdatePassportRequest$zodSchema,
} from "./updatepassportrequest.js";

export type LucidUpdatePassportRequest = {
  passport_id: string;
  xOwnerAddress?: string | undefined;
  body: UpdatePassportRequest;
};

export const LucidUpdatePassportRequest$zodSchema: z.ZodType<
  LucidUpdatePassportRequest
> = z.object({
  body: UpdatePassportRequest$zodSchema,
  passport_id: z.string(),
  xOwnerAddress: z.string().optional(),
});

export type LucidUpdatePassportResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  GetPassportResponse?: GetPassportResponse | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidUpdatePassportResponse$zodSchema: z.ZodType<
  LucidUpdatePassportResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  GetPassportResponse: GetPassportResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
