/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidTriggerPassportSyncRequest = { passport_id: string };

export const LucidTriggerPassportSyncRequest$zodSchema: z.ZodType<
  LucidTriggerPassportSyncRequest
> = z.object({
  passport_id: z.string(),
});

/**
 * OK
 */
export type LucidTriggerPassportSyncResponseBody = {
  success: boolean;
  on_chain_pda?: string | null | undefined;
  on_chain_tx?: string | null | undefined;
};

export const LucidTriggerPassportSyncResponseBody$zodSchema: z.ZodType<
  LucidTriggerPassportSyncResponseBody
> = z.object({
  on_chain_pda: z.string().nullable().optional(),
  on_chain_tx: z.string().nullable().optional(),
  success: z.boolean(),
}).describe("OK");

export type LucidTriggerPassportSyncResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: LucidTriggerPassportSyncResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidTriggerPassportSyncResponse$zodSchema: z.ZodType<
  LucidTriggerPassportSyncResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => LucidTriggerPassportSyncResponseBody$zodSchema)
    .optional(),
});
