/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { Policy, Policy$zodSchema } from "./policy.js";

export type LucidMatchRequest = {
  model_meta?: { [k: string]: any } | undefined;
  policy?: Policy | undefined;
  compute_catalog?: Array<{ [k: string]: any }> | undefined;
  require_live_healthy?: boolean | undefined;
};

export const LucidMatchRequest$zodSchema: z.ZodType<LucidMatchRequest> = z
  .object({
    compute_catalog: z.array(z.record(z.string(), z.any())).optional(),
    model_meta: z.record(z.string(), z.any()).optional(),
    policy: Policy$zodSchema.optional(),
    require_live_healthy: z.boolean().default(true),
  });

export type LucidMatchResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidMatchResponse$zodSchema: z.ZodType<LucidMatchResponse> = z
  .object({
    ContentType: z.string(),
    ErrorResponse: ErrorResponse$zodSchema.optional(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
  });
