/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidListDatasetsRequest = {
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

export const LucidListDatasetsRequest$zodSchema: z.ZodType<
  LucidListDatasetsRequest
> = z.object({
  owner: z.string().optional(),
  page: z.number().int().optional(),
  per_page: z.number().int().optional(),
  search: z.string().optional(),
  tags: z.string().optional(),
});

/**
 * OK
 */
export type LucidListDatasetsResponseBody = {
  success: boolean;
  datasets: Array<any>;
  pagination: any;
};

export const LucidListDatasetsResponseBody$zodSchema: z.ZodType<
  LucidListDatasetsResponseBody
> = z.object({
  datasets: z.array(z.any()),
  pagination: z.any(),
  success: z.boolean(),
}).describe("OK");

export type LucidListDatasetsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: LucidListDatasetsResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidListDatasetsResponse$zodSchema: z.ZodType<
  LucidListDatasetsResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => LucidListDatasetsResponseBody$zodSchema).optional(),
});
