/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidDeletePassportRequest = {
  passport_id: string;
  xOwnerAddress?: string | undefined;
};

export const LucidDeletePassportRequest$zodSchema: z.ZodType<
  LucidDeletePassportRequest
> = z.object({
  passport_id: z.string(),
  xOwnerAddress: z.string().optional(),
});

/**
 * OK
 */
export type LucidDeletePassportResponseBody = {
  success: boolean;
  deleted: boolean;
};

export const LucidDeletePassportResponseBody$zodSchema: z.ZodType<
  LucidDeletePassportResponseBody
> = z.object({
  deleted: z.boolean(),
  success: z.boolean(),
}).describe("OK");

export type LucidDeletePassportResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: LucidDeletePassportResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidDeletePassportResponse$zodSchema: z.ZodType<
  LucidDeletePassportResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => LucidDeletePassportResponseBody$zodSchema).optional(),
});
