/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChatCompletionResponse,
  ChatCompletionResponse$zodSchema,
} from "./chatcompletionresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidChatCompletionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ChatCompletionResponse?: ChatCompletionResponse | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidChatCompletionsResponse$zodSchema: z.ZodType<
  LucidChatCompletionsResponse
> = z.object({
  ChatCompletionResponse: ChatCompletionResponse$zodSchema.optional(),
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
