/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ReceiptHashVerification,
  ReceiptHashVerification$zodSchema,
} from "./receipthashverification.js";

export type LucidVerifyReceiptByHashRequest = { receipt_hash: string };

export const LucidVerifyReceiptByHashRequest$zodSchema: z.ZodType<
  LucidVerifyReceiptByHashRequest
> = z.object({
  receipt_hash: z.string(),
});

export type LucidVerifyReceiptByHashResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ReceiptHashVerification?: ReceiptHashVerification | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidVerifyReceiptByHashResponse$zodSchema: z.ZodType<
  LucidVerifyReceiptByHashResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  ReceiptHashVerification: ReceiptHashVerification$zodSchema.optional(),
  StatusCode: z.number().int(),
});
