/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type LucidGetEpochTransactionRequest = { epoch_id: string };

export const LucidGetEpochTransactionRequest$zodSchema: z.ZodType<
  LucidGetEpochTransactionRequest
> = z.object({
  epoch_id: z.string(),
});

export type LucidGetEpochTransactionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorResponse?: ErrorResponse | undefined;
};

export const LucidGetEpochTransactionResponse$zodSchema: z.ZodType<
  LucidGetEpochTransactionResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
