/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PassportStatus = {
  Active: "active",
  Deprecated: "deprecated",
  Revoked: "revoked",
} as const;
export type PassportStatus = ClosedEnum<typeof PassportStatus>;

export const PassportStatus$zodSchema = z.enum([
  "active",
  "deprecated",
  "revoked",
]);
