/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type PreviewAgentWorkflowRequest = {
  goal: string;
  context?: { [k: string]: any } | undefined;
};

export const PreviewAgentWorkflowRequest$zodSchema: z.ZodType<
  PreviewAgentWorkflowRequest
> = z.object({
  context: z.record(z.string(), z.any()).optional(),
  goal: z.string(),
});

/**
 * OK
 */
export type PreviewAgentWorkflowResponseBody = {
  success: boolean;
  preview: any;
  flowspec: any;
  reasoning?: string | undefined;
};

export const PreviewAgentWorkflowResponseBody$zodSchema: z.ZodType<
  PreviewAgentWorkflowResponseBody
> = z.object({
  flowspec: z.any(),
  preview: z.any(),
  reasoning: z.string().optional(),
  success: z.boolean(),
}).describe("OK");

export type PreviewAgentWorkflowResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: PreviewAgentWorkflowResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const PreviewAgentWorkflowResponse$zodSchema: z.ZodType<
  PreviewAgentWorkflowResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => PreviewAgentWorkflowResponseBody$zodSchema).optional(),
});
