/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type { AgentEpochRequest } from "./agentepochrequest.js";
export { AgentEpochRequest$zodSchema } from "./agentepochrequest.js";

/**
 * OK
 */
export type ProcessAgentEpochResponseBody = {
  success: boolean;
  agentId: string;
  epochNumber: number;
  vectorCount: number;
  mmrRoot: string;
  ipfsCid?: string | undefined;
  transactionSignature?: string | undefined;
  gasCost?: any | undefined;
  message?: string | undefined;
};

export const ProcessAgentEpochResponseBody$zodSchema: z.ZodType<
  ProcessAgentEpochResponseBody
> = z.object({
  agentId: z.string(),
  epochNumber: z.number().int(),
  gasCost: z.any().optional(),
  ipfsCid: z.string().optional(),
  message: z.string().optional(),
  mmrRoot: z.string(),
  success: z.boolean(),
  transactionSignature: z.string().optional(),
  vectorCount: z.number().int(),
}).describe("OK");

export type ProcessAgentEpochResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ProcessAgentEpochResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const ProcessAgentEpochResponse$zodSchema: z.ZodType<
  ProcessAgentEpochResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => ProcessAgentEpochResponseBody$zodSchema).optional(),
});
