/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type { AgentBatchEpochsRequest } from "./agentbatchepochsrequest.js";
export { AgentBatchEpochsRequest$zodSchema } from "./agentbatchepochsrequest.js";

/**
 * OK
 */
export type ProcessAgentBatchEpochsResponseBody = {
  success: boolean;
  processedEpochs: number;
  results: Array<any>;
  totalGasCost: any;
  message?: string | undefined;
};

export const ProcessAgentBatchEpochsResponseBody$zodSchema: z.ZodType<
  ProcessAgentBatchEpochsResponseBody
> = z.object({
  message: z.string().optional(),
  processedEpochs: z.number().int(),
  results: z.array(z.any()),
  success: z.boolean(),
  totalGasCost: z.any(),
}).describe("OK");

export type ProcessAgentBatchEpochsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: ProcessAgentBatchEpochsResponseBody | undefined;
  ErrorResponse?: ErrorResponse | undefined;
};

export const ProcessAgentBatchEpochsResponse$zodSchema: z.ZodType<
  ProcessAgentBatchEpochsResponse
> = z.object({
  ContentType: z.string(),
  ErrorResponse: ErrorResponse$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => ProcessAgentBatchEpochsResponseBody$zodSchema).optional(),
});
