/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReceiptVerification = {
  success?: boolean | undefined;
  valid?: boolean | undefined;
  hash_valid?: boolean | undefined;
  signature_valid?: boolean | undefined;
  inclusion_valid?: boolean | undefined;
  expected_hash?: string | undefined;
  computed_hash?: string | undefined;
  merkle_root?: string | undefined;
};

export const ReceiptVerification$zodSchema: z.ZodType<ReceiptVerification> = z
  .object({
    computed_hash: z.string().optional(),
    expected_hash: z.string().optional(),
    hash_valid: z.boolean().optional(),
    inclusion_valid: z.boolean().optional(),
    merkle_root: z.string().optional(),
    signature_valid: z.boolean().optional(),
    success: z.boolean().optional(),
    valid: z.boolean().optional(),
  });
