/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HealthCheckResult,
  HealthCheckResult$zodSchema,
} from "./healthcheckresult.js";

export type SystemHealth = {
  status: string;
  timestamp: string;
  uptime: number;
  version: string;
  dependencies: { [k: string]: HealthCheckResult };
};

export const SystemHealth$zodSchema: z.ZodType<SystemHealth> = z.object({
  dependencies: z.record(z.string(), HealthCheckResult$zodSchema),
  status: z.string(),
  timestamp: z.string(),
  uptime: z.number(),
  version: z.string(),
});
