/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { RaijinLabsLucidAiError } from "./raijinlabslucidaierror.js";

export type HealthCheckResultErrorData = {
  status: models.HealthCheckResultStatus;
  latency?: number | undefined;
  error?: string | undefined;
  details?: { [k: string]: any } | undefined;
};

export class HealthCheckResultError extends RaijinLabsLucidAiError {
  status: models.HealthCheckResultStatus;
  latency?: number | undefined;
  error?: string | undefined;
  details?: { [k: string]: any } | undefined;

  /** The original data that was passed to this error instance. */
  data$: HealthCheckResultErrorData;

  constructor(
    err: HealthCheckResultErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    if (err.latency != null) this.latency = err.latency;
    if (err.error != null) this.error = err.error;
    if (err.details != null) this.details = err.details;

    this.name = "HealthCheckResultError";
  }
}

/** @internal */
export const HealthCheckResultError$inboundSchema: z.ZodMiniType<
  HealthCheckResultError,
  unknown
> = z.pipe(
  z.object({
    status: models.HealthCheckResultStatus$inboundSchema,
    latency: types.optional(types.number()),
    error: types.optional(types.string()),
    details: types.optional(z.record(z.string(), z.any())),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new HealthCheckResultError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
