/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type A2ASendTaskRequestPart = {
  type?: string | undefined;
  text?: string | undefined;
};

export type Message = {
  role?: string | undefined;
  parts: Array<A2ASendTaskRequestPart>;
};

export type A2ASendTaskRequest = {
  message: Message;
};

/** @internal */
export type A2ASendTaskRequestPart$Outbound = {
  type?: string | undefined;
  text?: string | undefined;
};

/** @internal */
export const A2ASendTaskRequestPart$outboundSchema: z.ZodMiniType<
  A2ASendTaskRequestPart$Outbound,
  A2ASendTaskRequestPart
> = z.object({
  type: z.optional(z.string()),
  text: z.optional(z.string()),
});

export function a2ASendTaskRequestPartToJSON(
  a2ASendTaskRequestPart: A2ASendTaskRequestPart,
): string {
  return JSON.stringify(
    A2ASendTaskRequestPart$outboundSchema.parse(a2ASendTaskRequestPart),
  );
}

/** @internal */
export type Message$Outbound = {
  role?: string | undefined;
  parts: Array<A2ASendTaskRequestPart$Outbound>;
};

/** @internal */
export const Message$outboundSchema: z.ZodMiniType<Message$Outbound, Message> =
  z.object({
    role: z.optional(z.string()),
    parts: z.array(z.lazy(() => A2ASendTaskRequestPart$outboundSchema)),
  });

export function messageToJSON(message: Message): string {
  return JSON.stringify(Message$outboundSchema.parse(message));
}

/** @internal */
export type A2ASendTaskRequest$Outbound = {
  message: Message$Outbound;
};

/** @internal */
export const A2ASendTaskRequest$outboundSchema: z.ZodMiniType<
  A2ASendTaskRequest$Outbound,
  A2ASendTaskRequest
> = z.object({
  message: z.lazy(() => Message$outboundSchema),
});

export function a2ASendTaskRequestToJSON(
  a2ASendTaskRequest: A2ASendTaskRequest,
): string {
  return JSON.stringify(
    A2ASendTaskRequest$outboundSchema.parse(a2ASendTaskRequest),
  );
}
