/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const State = {
  Submitted: "submitted",
  Working: "working",
  InputRequired: "input-required",
  Completed: "completed",
  Failed: "failed",
  Canceled: "canceled",
} as const;
export type State = OpenEnum<typeof State>;

export type A2ATaskStatus = {
  state?: State | undefined;
  timestamp?: Date | undefined;
  message?: string | undefined;
};

export type A2ATaskPart = {
  type?: string | undefined;
  text?: string | undefined;
};

export type Artifact = {
  parts?: Array<A2ATaskPart> | undefined;
};

export type A2ATask = {
  id?: string | undefined;
  status?: A2ATaskStatus | undefined;
  artifacts?: Array<Artifact> | undefined;
  history?: Array<{ [k: string]: any }> | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const State$inboundSchema: z.ZodMiniType<State, unknown> = openEnums
  .inboundSchema(State);

/** @internal */
export const A2ATaskStatus$inboundSchema: z.ZodMiniType<
  A2ATaskStatus,
  unknown
> = z.object({
  state: types.optional(State$inboundSchema),
  timestamp: types.optional(types.date()),
  message: types.optional(types.string()),
});

export function a2ATaskStatusFromJSON(
  jsonString: string,
): SafeParseResult<A2ATaskStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => A2ATaskStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'A2ATaskStatus' from JSON`,
  );
}

/** @internal */
export const A2ATaskPart$inboundSchema: z.ZodMiniType<A2ATaskPart, unknown> = z
  .object({
    type: types.optional(types.string()),
    text: types.optional(types.string()),
  });

export function a2ATaskPartFromJSON(
  jsonString: string,
): SafeParseResult<A2ATaskPart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => A2ATaskPart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'A2ATaskPart' from JSON`,
  );
}

/** @internal */
export const Artifact$inboundSchema: z.ZodMiniType<Artifact, unknown> = z
  .object({
    parts: types.optional(z.array(z.lazy(() => A2ATaskPart$inboundSchema))),
  });

export function artifactFromJSON(
  jsonString: string,
): SafeParseResult<Artifact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Artifact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Artifact' from JSON`,
  );
}

/** @internal */
export const A2ATask$inboundSchema: z.ZodMiniType<A2ATask, unknown> = z.object({
  id: types.optional(types.string()),
  status: types.optional(z.lazy(() => A2ATaskStatus$inboundSchema)),
  artifacts: types.optional(z.array(z.lazy(() => Artifact$inboundSchema))),
  history: types.optional(z.array(z.record(z.string(), z.any()))),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function a2ATaskFromJSON(
  jsonString: string,
): SafeParseResult<A2ATask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => A2ATask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'A2ATask' from JSON`,
  );
}
