/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentRunProof = {
  passportId: string;
  runId: string;
  receiptHash: string;
  epochId?: string | undefined;
  mmrRoot?: string | undefined;
  chainTx?: string | null | undefined;
  verified: boolean;
  epochStatus?: string | undefined;
  modelPassportId?: string | undefined;
  policyHash?: string | undefined;
  tokensIn?: number | undefined;
  tokensOut?: number | undefined;
  status?: string | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const AgentRunProof$inboundSchema: z.ZodMiniType<
  AgentRunProof,
  unknown
> = z.pipe(
  z.object({
    passport_id: types.string(),
    run_id: types.string(),
    receipt_hash: types.string(),
    epoch_id: types.optional(types.string()),
    mmr_root: types.optional(types.string()),
    chain_tx: z.optional(z.nullable(types.string())),
    verified: types.boolean(),
    epoch_status: types.optional(types.string()),
    model_passport_id: types.optional(types.string()),
    policy_hash: types.optional(types.string()),
    tokens_in: types.optional(types.number()),
    tokens_out: types.optional(types.number()),
    status: types.optional(types.string()),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "passport_id": "passportId",
      "run_id": "runId",
      "receipt_hash": "receiptHash",
      "epoch_id": "epochId",
      "mmr_root": "mmrRoot",
      "chain_tx": "chainTx",
      "epoch_status": "epochStatus",
      "model_passport_id": "modelPassportId",
      "policy_hash": "policyHash",
      "tokens_in": "tokensIn",
      "tokens_out": "tokensOut",
      "created_at": "createdAt",
    });
  }),
);

export function agentRunProofFromJSON(
  jsonString: string,
): SafeParseResult<AgentRunProof, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRunProof$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRunProof' from JSON`,
  );
}
