/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type AgentWalletLimitsRequest = {
  /**
   * Maximum USD per transaction
   */
  perTxUsd: number;
  /**
   * Maximum USD per day
   */
  dailyUsd: number;
};

/** @internal */
export type AgentWalletLimitsRequest$Outbound = {
  per_tx_usd: number;
  daily_usd: number;
};

/** @internal */
export const AgentWalletLimitsRequest$outboundSchema: z.ZodMiniType<
  AgentWalletLimitsRequest$Outbound,
  AgentWalletLimitsRequest
> = z.pipe(
  z.object({
    perTxUsd: z.number(),
    dailyUsd: z.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      perTxUsd: "per_tx_usd",
      dailyUsd: "daily_usd",
    });
  }),
);

export function agentWalletLimitsRequestToJSON(
  agentWalletLimitsRequest: AgentWalletLimitsRequest,
): string {
  return JSON.stringify(
    AgentWalletLimitsRequest$outboundSchema.parse(agentWalletLimitsRequest),
  );
}
