/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentRevenuePool = {
  agentPassportId: string;
  /**
   * Lamports accumulated in pool
   */
  accumulatedLamports: string;
  /**
   * Total lamports distributed via airdrops
   */
  totalDistributedLamports: string;
  /**
   * Unix timestamp of last airdrop (0 if never)
   */
  lastAirdropAt: number;
};

/** @internal */
export const AgentRevenuePool$inboundSchema: z.ZodMiniType<
  AgentRevenuePool,
  unknown
> = z.pipe(
  z.object({
    agent_passport_id: types.string(),
    accumulated_lamports: types.string(),
    total_distributed_lamports: types.string(),
    last_airdrop_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "agent_passport_id": "agentPassportId",
      "accumulated_lamports": "accumulatedLamports",
      "total_distributed_lamports": "totalDistributedLamports",
      "last_airdrop_at": "lastAirdropAt",
    });
  }),
);

export function agentRevenuePoolFromJSON(
  jsonString: string,
): SafeParseResult<AgentRevenuePool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRevenuePool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRevenuePool' from JSON`,
  );
}
