/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AgentProofRequest = {
  agentId: string;
  vectorText: string;
  epochNumber: number;
};

/** @internal */
export type AgentProofRequest$Outbound = {
  agentId: string;
  vectorText: string;
  epochNumber: number;
};

/** @internal */
export const AgentProofRequest$outboundSchema: z.ZodMiniType<
  AgentProofRequest$Outbound,
  AgentProofRequest
> = z.object({
  agentId: z.string(),
  vectorText: z.string(),
  epochNumber: z.int(),
});

export function agentProofRequestToJSON(
  agentProofRequest: AgentProofRequest,
): string {
  return JSON.stringify(
    AgentProofRequest$outboundSchema.parse(agentProofRequest),
  );
}
