/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AgentWalletSendRequest = {
  /**
   * Recipient address
   */
  to: string;
  /**
   * Amount to send
   */
  amount: string;
  /**
   * Token mint address (optional, defaults to SOL)
   */
  token?: string | undefined;
};

/** @internal */
export type AgentWalletSendRequest$Outbound = {
  to: string;
  amount: string;
  token?: string | undefined;
};

/** @internal */
export const AgentWalletSendRequest$outboundSchema: z.ZodMiniType<
  AgentWalletSendRequest$Outbound,
  AgentWalletSendRequest
> = z.object({
  to: z.string(),
  amount: z.string(),
  token: z.optional(z.string()),
});

export function agentWalletSendRequestToJSON(
  agentWalletSendRequest: AgentWalletSendRequest,
): string {
  return JSON.stringify(
    AgentWalletSendRequest$outboundSchema.parse(agentWalletSendRequest),
  );
}
