/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentStats = {
  agentId?: string | undefined;
  totalEpochs?: number | undefined;
  totalVectors?: number | undefined;
  currentRoot?: string | undefined;
  lastEpoch?: number | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const AgentStats$inboundSchema: z.ZodMiniType<AgentStats, unknown> = z
  .object({
    agentId: types.optional(types.string()),
    totalEpochs: types.optional(types.number()),
    totalVectors: types.optional(types.number()),
    currentRoot: types.optional(types.string()),
    lastEpoch: types.optional(types.number()),
    createdAt: types.optional(types.date()),
  });

export function agentStatsFromJSON(
  jsonString: string,
): SafeParseResult<AgentStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentStats' from JSON`,
  );
}
