/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const PreferredExecutor = {
  N8n: "n8n",
  Langgraph: "langgraph",
} as const;
export type PreferredExecutor = ClosedEnum<typeof PreferredExecutor>;

export type AgentAccomplishRequest = {
  goal: string;
  context?: { [k: string]: any } | undefined;
  preferredExecutor?: PreferredExecutor | undefined;
  dryRun?: boolean | undefined;
};

/** @internal */
export const PreferredExecutor$outboundSchema: z.ZodMiniEnum<
  typeof PreferredExecutor
> = z.enum(PreferredExecutor);

/** @internal */
export type AgentAccomplishRequest$Outbound = {
  goal: string;
  context?: { [k: string]: any } | undefined;
  preferredExecutor?: string | undefined;
  dryRun?: boolean | undefined;
};

/** @internal */
export const AgentAccomplishRequest$outboundSchema: z.ZodMiniType<
  AgentAccomplishRequest$Outbound,
  AgentAccomplishRequest
> = z.object({
  goal: z.string(),
  context: z.optional(z.record(z.string(), z.any())),
  preferredExecutor: z.optional(PreferredExecutor$outboundSchema),
  dryRun: z.optional(z.boolean()),
});

export function agentAccomplishRequestToJSON(
  agentAccomplishRequest: AgentAccomplishRequest,
): string {
  return JSON.stringify(
    AgentAccomplishRequest$outboundSchema.parse(agentAccomplishRequest),
  );
}
