/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AgentInitRequest = {
  agentId: string;
  depinCid?: string | undefined;
};

/** @internal */
export type AgentInitRequest$Outbound = {
  agentId: string;
  depinCid?: string | undefined;
};

/** @internal */
export const AgentInitRequest$outboundSchema: z.ZodMiniType<
  AgentInitRequest$Outbound,
  AgentInitRequest
> = z.object({
  agentId: z.string(),
  depinCid: z.optional(z.string()),
});

export function agentInitRequestToJSON(
  agentInitRequest: AgentInitRequest,
): string {
  return JSON.stringify(
    AgentInitRequest$outboundSchema.parse(agentInitRequest),
  );
}
