/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentProof = {
  passportId: string;
  epochId: string;
  epochIndex?: number | undefined;
  mmrRoot: string;
  leafCount?: number | undefined;
  chainTx?: string | null | undefined;
  verified: boolean;
  finalizedAt?: Date | undefined;
  totalReceipts?: number | undefined;
};

/** @internal */
export const AgentProof$inboundSchema: z.ZodMiniType<AgentProof, unknown> = z
  .pipe(
    z.object({
      passport_id: types.string(),
      epoch_id: types.string(),
      epoch_index: types.optional(types.number()),
      mmr_root: types.string(),
      leaf_count: types.optional(types.number()),
      chain_tx: z.optional(z.nullable(types.string())),
      verified: types.boolean(),
      finalized_at: types.optional(types.date()),
      total_receipts: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "passport_id": "passportId",
        "epoch_id": "epochId",
        "epoch_index": "epochIndex",
        "mmr_root": "mmrRoot",
        "leaf_count": "leafCount",
        "chain_tx": "chainTx",
        "finalized_at": "finalizedAt",
        "total_receipts": "totalReceipts",
      });
    }),
  );

export function agentProofFromJSON(
  jsonString: string,
): SafeParseResult<AgentProof, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentProof$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentProof' from JSON`,
  );
}
