/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentHistoryEntry = {
  epoch?: number | undefined;
  root?: string | undefined;
  timestamp?: number | undefined;
  date?: Date | undefined;
};

/** @internal */
export const AgentHistoryEntry$inboundSchema: z.ZodMiniType<
  AgentHistoryEntry,
  unknown
> = z.object({
  epoch: types.optional(types.number()),
  root: types.optional(types.string()),
  timestamp: types.optional(types.number()),
  date: types.optional(types.date()),
});

export function agentHistoryEntryFromJSON(
  jsonString: string,
): SafeParseResult<AgentHistoryEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentHistoryEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentHistoryEntry' from JSON`,
  );
}
