/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ArtifactType = {
  EpochBundle: "epoch_bundle",
  EpochProof: "epoch_proof",
  MemorySnapshot: "memory_snapshot",
  DeployArtifact: "deploy_artifact",
  PassportMetadata: "passport_metadata",
  NftMetadata: "nft_metadata",
  MmrCheckpoint: "mmr_checkpoint",
} as const;
export type ArtifactType = OpenEnum<typeof ArtifactType>;

export const StorageTier = {
  Permanent: "permanent",
  Evolving: "evolving",
} as const;
export type StorageTier = OpenEnum<typeof StorageTier>;

export const AnchorRecordStatus = {
  Uploaded: "uploaded",
  Verified: "verified",
  Unreachable: "unreachable",
} as const;
export type AnchorRecordStatus = OpenEnum<typeof AnchorRecordStatus>;

export type ChainTx = {};

export type Metadata = {};

export type AnchorRecord = {
  anchorId?: string | undefined;
  artifactType?: ArtifactType | undefined;
  artifactId?: string | undefined;
  agentPassportId?: string | null | undefined;
  producer?: string | undefined;
  provider?: string | undefined;
  storageTier?: StorageTier | undefined;
  cid?: string | undefined;
  contentHash?: string | undefined;
  url?: string | undefined;
  sizeBytes?: number | undefined;
  status?: AnchorRecordStatus | undefined;
  parentAnchorId?: string | null | undefined;
  chainTx?: ChainTx | null | undefined;
  metadata?: Metadata | undefined;
  /**
   * Unix timestamp in milliseconds
   */
  createdAt?: number | undefined;
  /**
   * Unix timestamp in milliseconds
   */
  verifiedAt?: number | null | undefined;
};

/** @internal */
export const ArtifactType$inboundSchema: z.ZodMiniType<ArtifactType, unknown> =
  openEnums.inboundSchema(ArtifactType);

/** @internal */
export const StorageTier$inboundSchema: z.ZodMiniType<StorageTier, unknown> =
  openEnums.inboundSchema(StorageTier);

/** @internal */
export const AnchorRecordStatus$inboundSchema: z.ZodMiniType<
  AnchorRecordStatus,
  unknown
> = openEnums.inboundSchema(AnchorRecordStatus);

/** @internal */
export const ChainTx$inboundSchema: z.ZodMiniType<ChainTx, unknown> = z.object(
  {},
);

export function chainTxFromJSON(
  jsonString: string,
): SafeParseResult<ChainTx, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChainTx$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChainTx' from JSON`,
  );
}

/** @internal */
export const Metadata$inboundSchema: z.ZodMiniType<Metadata, unknown> = z
  .object({});

export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const AnchorRecord$inboundSchema: z.ZodMiniType<AnchorRecord, unknown> =
  z.pipe(
    z.object({
      anchor_id: types.optional(types.string()),
      artifact_type: types.optional(ArtifactType$inboundSchema),
      artifact_id: types.optional(types.string()),
      agent_passport_id: z.optional(z.nullable(types.string())),
      producer: types.optional(types.string()),
      provider: types.optional(types.string()),
      storage_tier: types.optional(StorageTier$inboundSchema),
      cid: types.optional(types.string()),
      content_hash: types.optional(types.string()),
      url: types.optional(types.string()),
      size_bytes: types.optional(types.number()),
      status: types.optional(AnchorRecordStatus$inboundSchema),
      parent_anchor_id: z.optional(z.nullable(types.string())),
      chain_tx: z.optional(z.nullable(z.lazy(() => ChainTx$inboundSchema))),
      metadata: types.optional(z.lazy(() => Metadata$inboundSchema)),
      created_at: types.optional(types.number()),
      verified_at: z.optional(z.nullable(types.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "anchor_id": "anchorId",
        "artifact_type": "artifactType",
        "artifact_id": "artifactId",
        "agent_passport_id": "agentPassportId",
        "storage_tier": "storageTier",
        "content_hash": "contentHash",
        "size_bytes": "sizeBytes",
        "parent_anchor_id": "parentAnchorId",
        "chain_tx": "chainTx",
        "created_at": "createdAt",
        "verified_at": "verifiedAt",
      });
    }),
  );

export function anchorRecordFromJSON(
  jsonString: string,
): SafeParseResult<AnchorRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnchorRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnchorRecord' from JSON`,
  );
}
