/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Role = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Function: "function",
} as const;
export type Role = OpenEnum<typeof Role>;

export type FunctionCall = {
  name?: string | undefined;
  arguments?: string | undefined;
};

export type ChatMessage = {
  role: Role;
  content: string;
  name?: string | undefined;
  functionCall?: FunctionCall | undefined;
};

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = openEnums
  .inboundSchema(Role);
/** @internal */
export const Role$outboundSchema: z.ZodMiniType<string, Role> = openEnums
  .outboundSchema(Role);

/** @internal */
export const FunctionCall$inboundSchema: z.ZodMiniType<FunctionCall, unknown> =
  z.object({
    name: types.optional(types.string()),
    arguments: types.optional(types.string()),
  });
/** @internal */
export type FunctionCall$Outbound = {
  name?: string | undefined;
  arguments?: string | undefined;
};

/** @internal */
export const FunctionCall$outboundSchema: z.ZodMiniType<
  FunctionCall$Outbound,
  FunctionCall
> = z.object({
  name: z.optional(z.string()),
  arguments: z.optional(z.string()),
});

export function functionCallToJSON(functionCall: FunctionCall): string {
  return JSON.stringify(FunctionCall$outboundSchema.parse(functionCall));
}
export function functionCallFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCall' from JSON`,
  );
}

/** @internal */
export const ChatMessage$inboundSchema: z.ZodMiniType<ChatMessage, unknown> = z
  .pipe(
    z.object({
      role: Role$inboundSchema,
      content: types.string(),
      name: types.optional(types.string()),
      function_call: types.optional(z.lazy(() => FunctionCall$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "function_call": "functionCall",
      });
    }),
  );
/** @internal */
export type ChatMessage$Outbound = {
  role: string;
  content: string;
  name?: string | undefined;
  function_call?: FunctionCall$Outbound | undefined;
};

/** @internal */
export const ChatMessage$outboundSchema: z.ZodMiniType<
  ChatMessage$Outbound,
  ChatMessage
> = z.pipe(
  z.object({
    role: Role$outboundSchema,
    content: z.string(),
    name: z.optional(z.string()),
    functionCall: z.optional(z.lazy(() => FunctionCall$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      functionCall: "function_call",
    });
  }),
);

export function chatMessageToJSON(chatMessage: ChatMessage): string {
  return JSON.stringify(ChatMessage$outboundSchema.parse(chatMessage));
}
export function chatMessageFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessage' from JSON`,
  );
}
