/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ComputeEndpoints = {
  /**
   * URL for inference requests
   */
  inferenceUrl: string;
  quoteUrl?: string | undefined;
  jobsUrl?: string | undefined;
  healthUrl?: string | undefined;
  metricsUrl?: string | undefined;
};

/** @internal */
export type ComputeEndpoints$Outbound = {
  inference_url: string;
  quote_url?: string | undefined;
  jobs_url?: string | undefined;
  health_url?: string | undefined;
  metrics_url?: string | undefined;
};

/** @internal */
export const ComputeEndpoints$outboundSchema: z.ZodMiniType<
  ComputeEndpoints$Outbound,
  ComputeEndpoints
> = z.pipe(
  z.object({
    inferenceUrl: z.string(),
    quoteUrl: z.optional(z.string()),
    jobsUrl: z.optional(z.string()),
    healthUrl: z.optional(z.string()),
    metricsUrl: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      inferenceUrl: "inference_url",
      quoteUrl: "quote_url",
      jobsUrl: "jobs_url",
      healthUrl: "health_url",
      metricsUrl: "metrics_url",
    });
  }),
);

export function computeEndpointsToJSON(
  computeEndpoints: ComputeEndpoints,
): string {
  return JSON.stringify(
    ComputeEndpoints$outboundSchema.parse(computeEndpoints),
  );
}
