/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ComputeCapabilities,
  ComputeCapabilities$Outbound,
  ComputeCapabilities$outboundSchema,
} from "./computecapabilities.js";
import {
  ComputeEndpoints,
  ComputeEndpoints$Outbound,
  ComputeEndpoints$outboundSchema,
} from "./computeendpoints.js";
import {
  ComputeHardware,
  ComputeHardware$Outbound,
  ComputeHardware$outboundSchema,
} from "./computehardware.js";
import {
  ComputeRuntime,
  ComputeRuntime$Outbound,
  ComputeRuntime$outboundSchema,
} from "./computeruntime.js";
import {
  ComputeWorker,
  ComputeWorker$Outbound,
  ComputeWorker$outboundSchema,
} from "./computeworker.js";

export const ComputeMetaSchemaVersion = {
  OneDot0: "1.0",
} as const;
export type ComputeMetaSchemaVersion = ClosedEnum<
  typeof ComputeMetaSchemaVersion
>;

export const ProviderType = {
  Depin: "depin",
  Cloud: "cloud",
  Onprem: "onprem",
  Managed: "managed",
} as const;
export type ProviderType = ClosedEnum<typeof ProviderType>;

export const ExecutionMode = {
  ByoRuntime: "byo_runtime",
  ManagedEndpoint: "managed_endpoint",
} as const;
export type ExecutionMode = ClosedEnum<typeof ExecutionMode>;

export type Network = {
  p95MsEstimate?: number | undefined;
  bandwidth?: string | undefined;
};

export type Limits = {
  maxContext?: number | undefined;
  maxBatch?: number | undefined;
  maxInputTokens?: number | undefined;
  maxOutputTokens?: number | undefined;
  requestsPerMinute?: number | undefined;
};

export const Currency = {
  Lamports: "lamports",
  UsdCents: "usd_cents",
  Credits: "credits",
} as const;
export type Currency = ClosedEnum<typeof Currency>;

export type Pricing = {
  pricePer1kTokensEstimate?: number | undefined;
  pricePerMinuteEstimate?: number | undefined;
  perInputToken?: number | undefined;
  perOutputToken?: number | undefined;
  currency?: Currency | undefined;
};

export const Tier = {
  BestEffort: "best-effort",
  Standard: "standard",
  Premium: "premium",
  Enterprise: "enterprise",
} as const;
export type Tier = ClosedEnum<typeof Tier>;

export type Sla = {
  tier?: Tier | undefined;
  uptimeTarget?: number | undefined;
};

/**
 * Metadata for a compute provider passport. Validated against schemas/ComputeMeta.schema.json (additionalProperties: false).
 */
export type ComputeMeta = {
  schemaVersion: ComputeMetaSchemaVersion;
  computePassportId: string;
  providerType: ProviderType;
  executionMode?: ExecutionMode | undefined;
  /**
   * ed25519 public key (hex) of the provider operator
   */
  operatorPubkey?: string | undefined;
  regions: Array<string>;
  residencySupported?: boolean | undefined;
  hardware: ComputeHardware;
  /**
   * GPU hardware fingerprint. Must be null for managed_endpoint mode.
   */
  gpuFingerprint?: string | null | undefined;
  /**
   * Docker image digest. Must be null for managed_endpoint mode.
   */
  runtimeHash?: string | null | undefined;
  runtimes: Array<ComputeRuntime>;
  capabilities?: ComputeCapabilities | undefined;
  network?: Network | undefined;
  limits?: Limits | undefined;
  pricing?: Pricing | undefined;
  endpoints: ComputeEndpoints;
  workers?: Array<ComputeWorker> | undefined;
  sla?: Sla | undefined;
  /**
   * Tags for matching (e.g. 'hipaa', 'gdpr', 'no-logging')
   */
  policyTags?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ComputeMetaSchemaVersion$outboundSchema: z.ZodMiniEnum<
  typeof ComputeMetaSchemaVersion
> = z.enum(ComputeMetaSchemaVersion);

/** @internal */
export const ProviderType$outboundSchema: z.ZodMiniEnum<typeof ProviderType> = z
  .enum(ProviderType);

/** @internal */
export const ExecutionMode$outboundSchema: z.ZodMiniEnum<typeof ExecutionMode> =
  z.enum(ExecutionMode);

/** @internal */
export type Network$Outbound = {
  p95_ms_estimate?: number | undefined;
  bandwidth?: string | undefined;
};

/** @internal */
export const Network$outboundSchema: z.ZodMiniType<Network$Outbound, Network> =
  z.pipe(
    z.object({
      p95MsEstimate: z.optional(z.int()),
      bandwidth: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        p95MsEstimate: "p95_ms_estimate",
      });
    }),
  );

export function networkToJSON(network: Network): string {
  return JSON.stringify(Network$outboundSchema.parse(network));
}

/** @internal */
export type Limits$Outbound = {
  max_context?: number | undefined;
  max_batch?: number | undefined;
  max_input_tokens?: number | undefined;
  max_output_tokens?: number | undefined;
  requests_per_minute?: number | undefined;
};

/** @internal */
export const Limits$outboundSchema: z.ZodMiniType<Limits$Outbound, Limits> = z
  .pipe(
    z.object({
      maxContext: z.optional(z.int()),
      maxBatch: z.optional(z.int()),
      maxInputTokens: z.optional(z.int()),
      maxOutputTokens: z.optional(z.int()),
      requestsPerMinute: z.optional(z.int()),
    }),
    z.transform((v) => {
      return remap$(v, {
        maxContext: "max_context",
        maxBatch: "max_batch",
        maxInputTokens: "max_input_tokens",
        maxOutputTokens: "max_output_tokens",
        requestsPerMinute: "requests_per_minute",
      });
    }),
  );

export function limitsToJSON(limits: Limits): string {
  return JSON.stringify(Limits$outboundSchema.parse(limits));
}

/** @internal */
export const Currency$outboundSchema: z.ZodMiniEnum<typeof Currency> = z.enum(
  Currency,
);

/** @internal */
export type Pricing$Outbound = {
  price_per_1k_tokens_estimate?: number | undefined;
  price_per_minute_estimate?: number | undefined;
  per_input_token?: number | undefined;
  per_output_token?: number | undefined;
  currency?: string | undefined;
};

/** @internal */
export const Pricing$outboundSchema: z.ZodMiniType<Pricing$Outbound, Pricing> =
  z.pipe(
    z.object({
      pricePer1kTokensEstimate: z.optional(z.number()),
      pricePerMinuteEstimate: z.optional(z.number()),
      perInputToken: z.optional(z.number()),
      perOutputToken: z.optional(z.number()),
      currency: z.optional(Currency$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        pricePer1kTokensEstimate: "price_per_1k_tokens_estimate",
        pricePerMinuteEstimate: "price_per_minute_estimate",
        perInputToken: "per_input_token",
        perOutputToken: "per_output_token",
      });
    }),
  );

export function pricingToJSON(pricing: Pricing): string {
  return JSON.stringify(Pricing$outboundSchema.parse(pricing));
}

/** @internal */
export const Tier$outboundSchema: z.ZodMiniEnum<typeof Tier> = z.enum(Tier);

/** @internal */
export type Sla$Outbound = {
  tier?: string | undefined;
  uptime_target?: number | undefined;
};

/** @internal */
export const Sla$outboundSchema: z.ZodMiniType<Sla$Outbound, Sla> = z.pipe(
  z.object({
    tier: z.optional(Tier$outboundSchema),
    uptimeTarget: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      uptimeTarget: "uptime_target",
    });
  }),
);

export function slaToJSON(sla: Sla): string {
  return JSON.stringify(Sla$outboundSchema.parse(sla));
}

/** @internal */
export type ComputeMeta$Outbound = {
  schema_version: string;
  compute_passport_id: string;
  provider_type: string;
  execution_mode?: string | undefined;
  operator_pubkey?: string | undefined;
  regions: Array<string>;
  residency_supported: boolean;
  hardware: ComputeHardware$Outbound;
  gpu_fingerprint?: string | null | undefined;
  runtime_hash?: string | null | undefined;
  runtimes: Array<ComputeRuntime$Outbound>;
  capabilities?: ComputeCapabilities$Outbound | undefined;
  network?: Network$Outbound | undefined;
  limits?: Limits$Outbound | undefined;
  pricing?: Pricing$Outbound | undefined;
  endpoints: ComputeEndpoints$Outbound;
  workers?: Array<ComputeWorker$Outbound> | undefined;
  sla?: Sla$Outbound | undefined;
  policy_tags?: Array<string> | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ComputeMeta$outboundSchema: z.ZodMiniType<
  ComputeMeta$Outbound,
  ComputeMeta
> = z.pipe(
  z.object({
    schemaVersion: ComputeMetaSchemaVersion$outboundSchema,
    computePassportId: z.string(),
    providerType: ProviderType$outboundSchema,
    executionMode: z.optional(ExecutionMode$outboundSchema),
    operatorPubkey: z.optional(z.string()),
    regions: z.array(z.string()),
    residencySupported: z._default(z.boolean(), false),
    hardware: ComputeHardware$outboundSchema,
    gpuFingerprint: z.optional(z.nullable(z.string())),
    runtimeHash: z.optional(z.nullable(z.string())),
    runtimes: z.array(ComputeRuntime$outboundSchema),
    capabilities: z.optional(ComputeCapabilities$outboundSchema),
    network: z.optional(z.lazy(() => Network$outboundSchema)),
    limits: z.optional(z.lazy(() => Limits$outboundSchema)),
    pricing: z.optional(z.lazy(() => Pricing$outboundSchema)),
    endpoints: ComputeEndpoints$outboundSchema,
    workers: z.optional(z.array(ComputeWorker$outboundSchema)),
    sla: z.optional(z.lazy(() => Sla$outboundSchema)),
    policyTags: z.optional(z.array(z.string())),
    metadata: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      schemaVersion: "schema_version",
      computePassportId: "compute_passport_id",
      providerType: "provider_type",
      executionMode: "execution_mode",
      operatorPubkey: "operator_pubkey",
      residencySupported: "residency_supported",
      gpuFingerprint: "gpu_fingerprint",
      runtimeHash: "runtime_hash",
      policyTags: "policy_tags",
    });
  }),
);

export function computeMetaToJSON(computeMeta: ComputeMeta): string {
  return JSON.stringify(ComputeMeta$outboundSchema.parse(computeMeta));
}
