/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Name = {
  Vllm: "vllm",
  Tgi: "tgi",
  Tensorrt: "tensorrt",
  HfInferenceApi: "hf-inference-api",
  OpenaiCompatible: "openai-compatible",
  Custom: "custom",
} as const;
export type Name = ClosedEnum<typeof Name>;

export type ComputeRuntime = {
  name: Name;
  version?: string | undefined;
  /**
   * Docker image reference
   */
  image?: string | undefined;
};

/** @internal */
export const Name$outboundSchema: z.ZodMiniEnum<typeof Name> = z.enum(Name);

/** @internal */
export type ComputeRuntime$Outbound = {
  name: string;
  version?: string | undefined;
  image?: string | undefined;
};

/** @internal */
export const ComputeRuntime$outboundSchema: z.ZodMiniType<
  ComputeRuntime$Outbound,
  ComputeRuntime
> = z.object({
  name: Name$outboundSchema,
  version: z.optional(z.string()),
  image: z.optional(z.string()),
});

export function computeRuntimeToJSON(computeRuntime: ComputeRuntime): string {
  return JSON.stringify(ComputeRuntime$outboundSchema.parse(computeRuntime));
}
