/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const InferenceType = {
  TextGeneration: "text-generation",
  ChatCompletion: "chat-completion",
  Embeddings: "embeddings",
  ImageGeneration: "image-generation",
  SpeechToText: "speech-to-text",
} as const;
export type InferenceType = ClosedEnum<typeof InferenceType>;

export type ComputeCapabilities = {
  supportsStreaming?: boolean | undefined;
  supportsAttestation?: boolean | undefined;
  supportsCcOn?: boolean | undefined;
  inferenceTypes?: Array<InferenceType> | undefined;
};

/** @internal */
export const InferenceType$outboundSchema: z.ZodMiniEnum<typeof InferenceType> =
  z.enum(InferenceType);

/** @internal */
export type ComputeCapabilities$Outbound = {
  supports_streaming: boolean;
  supports_attestation: boolean;
  supports_cc_on: boolean;
  inference_types?: Array<string> | undefined;
};

/** @internal */
export const ComputeCapabilities$outboundSchema: z.ZodMiniType<
  ComputeCapabilities$Outbound,
  ComputeCapabilities
> = z.pipe(
  z.object({
    supportsStreaming: z._default(z.boolean(), true),
    supportsAttestation: z._default(z.boolean(), false),
    supportsCcOn: z._default(z.boolean(), false),
    inferenceTypes: z.optional(z.array(InferenceType$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      supportsStreaming: "supports_streaming",
      supportsAttestation: "supports_attestation",
      supportsCcOn: "supports_cc_on",
      inferenceTypes: "inference_types",
    });
  }),
);

export function computeCapabilitiesToJSON(
  computeCapabilities: ComputeCapabilities,
): string {
  return JSON.stringify(
    ComputeCapabilities$outboundSchema.parse(computeCapabilities),
  );
}
