/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateEscrowRequest = {
  /**
   * Chain identifier (e.g. 'base', 'ethereum-sepolia')
   */
  chainId: string;
  /**
   * Beneficiary address
   */
  beneficiary: string;
  /**
   * ERC-20 token address
   */
  token: string;
  /**
   * Amount in token base units
   */
  amount: string;
  /**
   * Escrow duration in seconds
   */
  duration: number;
  /**
   * Optional expected receipt hash for auto-release
   */
  expectedReceiptHash?: string | undefined;
};

/** @internal */
export type CreateEscrowRequest$Outbound = {
  chainId: string;
  beneficiary: string;
  token: string;
  amount: string;
  duration: number;
  expectedReceiptHash?: string | undefined;
};

/** @internal */
export const CreateEscrowRequest$outboundSchema: z.ZodMiniType<
  CreateEscrowRequest$Outbound,
  CreateEscrowRequest
> = z.object({
  chainId: z.string(),
  beneficiary: z.string(),
  token: z.string(),
  amount: z.string(),
  duration: z.int(),
  expectedReceiptHash: z.optional(z.string()),
});

export function createEscrowRequestToJSON(
  createEscrowRequest: CreateEscrowRequest,
): string {
  return JSON.stringify(
    CreateEscrowRequest$outboundSchema.parse(createEscrowRequest),
  );
}
