/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PaymentGrantAttestation,
  PaymentGrantAttestation$Outbound,
  PaymentGrantAttestation$outboundSchema,
} from "./paymentgrantattestation.js";
import {
  PaymentGrantLimits,
  PaymentGrantLimits$Outbound,
  PaymentGrantLimits$outboundSchema,
} from "./paymentgrantlimits.js";
import {
  PaymentGrantScope,
  PaymentGrantScope$Outbound,
  PaymentGrantScope$outboundSchema,
} from "./paymentgrantscope.js";

export type CreatePaymentGrantRequest = {
  tenantId: string;
  agentPassportId: string;
  runId: string;
  scope: PaymentGrantScope;
  limits: PaymentGrantLimits;
  attestation?: PaymentGrantAttestation | undefined;
};

/** @internal */
export type CreatePaymentGrantRequest$Outbound = {
  tenant_id: string;
  agent_passport_id: string;
  run_id: string;
  scope: PaymentGrantScope$Outbound;
  limits: PaymentGrantLimits$Outbound;
  attestation?: PaymentGrantAttestation$Outbound | undefined;
};

/** @internal */
export const CreatePaymentGrantRequest$outboundSchema: z.ZodMiniType<
  CreatePaymentGrantRequest$Outbound,
  CreatePaymentGrantRequest
> = z.pipe(
  z.object({
    tenantId: z.string(),
    agentPassportId: z.string(),
    runId: z.string(),
    scope: PaymentGrantScope$outboundSchema,
    limits: PaymentGrantLimits$outboundSchema,
    attestation: z.optional(PaymentGrantAttestation$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
      agentPassportId: "agent_passport_id",
      runId: "run_id",
    });
  }),
);

export function createPaymentGrantRequestToJSON(
  createPaymentGrantRequest: CreatePaymentGrantRequest,
): string {
  return JSON.stringify(
    CreatePaymentGrantRequest$outboundSchema.parse(createPaymentGrantRequest),
  );
}
