/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateTBARequest = {
  chainId: string;
  /**
   * NFT contract address
   */
  tokenContract: string;
  /**
   * NFT token ID
   */
  tokenId: string;
};

/** @internal */
export type CreateTBARequest$Outbound = {
  chainId: string;
  tokenContract: string;
  tokenId: string;
};

/** @internal */
export const CreateTBARequest$outboundSchema: z.ZodMiniType<
  CreateTBARequest$Outbound,
  CreateTBARequest
> = z.object({
  chainId: z.string(),
  tokenContract: z.string(),
  tokenId: z.string(),
});

export function createTBARequestToJSON(
  createTBARequest: CreateTBARequest,
): string {
  return JSON.stringify(
    CreateTBARequest$outboundSchema.parse(createTBARequest),
  );
}
