/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Passport, Passport$inboundSchema } from "./passport.js";

export type CreatePassportResponse = {
  success: boolean;
  passportId: string;
  passport: Passport;
};

/** @internal */
export const CreatePassportResponse$inboundSchema: z.ZodMiniType<
  CreatePassportResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    passport_id: types.string(),
    passport: Passport$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "passport_id": "passportId",
    });
  }),
);

export function createPassportResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePassportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePassportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePassportResponse' from JSON`,
  );
}
