/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeployAgentRequest = {
  name: string;
  description?: string | undefined;
  owner: string;
  /**
   * Agent runtime descriptor
   */
  descriptor: { [k: string]: any };
  /**
   * Runtime adapter (e.g. vercel-ai, openclaw, docker)
   */
  preferredAdapter?: string | undefined;
  tags?: Array<string> | undefined;
  listOnMarketplace?: boolean | undefined;
};

/** @internal */
export type DeployAgentRequest$Outbound = {
  name: string;
  description?: string | undefined;
  owner: string;
  descriptor: { [k: string]: any };
  preferred_adapter?: string | undefined;
  tags?: Array<string> | undefined;
  list_on_marketplace?: boolean | undefined;
};

/** @internal */
export const DeployAgentRequest$outboundSchema: z.ZodMiniType<
  DeployAgentRequest$Outbound,
  DeployAgentRequest
> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.string()),
    owner: z.string(),
    descriptor: z.record(z.string(), z.any()),
    preferredAdapter: z.optional(z.string()),
    tags: z.optional(z.array(z.string())),
    listOnMarketplace: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      preferredAdapter: "preferred_adapter",
      listOnMarketplace: "list_on_marketplace",
    });
  }),
);

export function deployAgentRequestToJSON(
  deployAgentRequest: DeployAgentRequest,
): string {
  return JSON.stringify(
    DeployAgentRequest$outboundSchema.parse(deployAgentRequest),
  );
}
