/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DisputeEscrowRequest = {
  chainId: string;
  escrowId: string;
  reason: string;
};

/** @internal */
export type DisputeEscrowRequest$Outbound = {
  chainId: string;
  escrowId: string;
  reason: string;
};

/** @internal */
export const DisputeEscrowRequest$outboundSchema: z.ZodMiniType<
  DisputeEscrowRequest$Outbound,
  DisputeEscrowRequest
> = z.object({
  chainId: z.string(),
  escrowId: z.string(),
  reason: z.string(),
});

export function disputeEscrowRequestToJSON(
  disputeEscrowRequest: DisputeEscrowRequest,
): string {
  return JSON.stringify(
    DisputeEscrowRequest$outboundSchema.parse(disputeEscrowRequest),
  );
}
