/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { DisputeStatus, DisputeStatus$inboundSchema } from "./disputestatus.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DisputeInfo = {
  disputeId?: string | undefined;
  escrowId?: string | undefined;
  status?: DisputeStatus | undefined;
  reason?: string | undefined;
  createdAt?: string | undefined;
  resolvedAt?: string | undefined;
  resolution?: string | undefined;
};

/** @internal */
export const DisputeInfo$inboundSchema: z.ZodMiniType<DisputeInfo, unknown> = z
  .object({
    disputeId: types.optional(types.string()),
    escrowId: types.optional(types.string()),
    status: types.optional(DisputeStatus$inboundSchema),
    reason: types.optional(types.string()),
    createdAt: types.optional(types.string()),
    resolvedAt: types.optional(types.string()),
    resolution: types.optional(types.string()),
  });

export function disputeInfoFromJSON(
  jsonString: string,
): SafeParseResult<DisputeInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisputeInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisputeInfo' from JSON`,
  );
}
