/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type EpochStatsResponseByStatus = {
  open?: number | undefined;
  anchoring?: number | undefined;
  anchored?: number | undefined;
  failed?: number | undefined;
};

export type EpochStatsResponseStats = {
  totalEpochs?: number | undefined;
  totalReceipts?: number | undefined;
  byStatus?: EpochStatsResponseByStatus | undefined;
  avgReceiptsPerEpoch?: number | undefined;
  lastAnchorTime?: number | undefined;
};

export type EpochStatsResponse = {
  success: boolean;
  stats: EpochStatsResponseStats;
};

/** @internal */
export const EpochStatsResponseByStatus$inboundSchema: z.ZodMiniType<
  EpochStatsResponseByStatus,
  unknown
> = z.object({
  open: types.optional(types.number()),
  anchoring: types.optional(types.number()),
  anchored: types.optional(types.number()),
  failed: types.optional(types.number()),
});

export function epochStatsResponseByStatusFromJSON(
  jsonString: string,
): SafeParseResult<EpochStatsResponseByStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EpochStatsResponseByStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EpochStatsResponseByStatus' from JSON`,
  );
}

/** @internal */
export const EpochStatsResponseStats$inboundSchema: z.ZodMiniType<
  EpochStatsResponseStats,
  unknown
> = z.pipe(
  z.object({
    total_epochs: types.optional(types.number()),
    total_receipts: types.optional(types.number()),
    by_status: types.optional(
      z.lazy(() => EpochStatsResponseByStatus$inboundSchema),
    ),
    avg_receipts_per_epoch: types.optional(types.number()),
    last_anchor_time: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_epochs": "totalEpochs",
      "total_receipts": "totalReceipts",
      "by_status": "byStatus",
      "avg_receipts_per_epoch": "avgReceiptsPerEpoch",
      "last_anchor_time": "lastAnchorTime",
    });
  }),
);

export function epochStatsResponseStatsFromJSON(
  jsonString: string,
): SafeParseResult<EpochStatsResponseStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EpochStatsResponseStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EpochStatsResponseStats' from JSON`,
  );
}

/** @internal */
export const EpochStatsResponse$inboundSchema: z.ZodMiniType<
  EpochStatsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  stats: z.lazy(() => EpochStatsResponseStats$inboundSchema),
});

export function epochStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<EpochStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EpochStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EpochStatsResponse' from JSON`,
  );
}
