/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type EpochsReadyResponseEpoch = {
  epochId?: string | undefined;
  projectId?: string | undefined;
  leafCount?: number | undefined;
  createdAt?: number | undefined;
  mmrRoot?: string | undefined;
};

export type EpochsReadyResponse = {
  success: boolean;
  count: number;
  epochs: Array<EpochsReadyResponseEpoch>;
};

/** @internal */
export const EpochsReadyResponseEpoch$inboundSchema: z.ZodMiniType<
  EpochsReadyResponseEpoch,
  unknown
> = z.pipe(
  z.object({
    epoch_id: types.optional(types.string()),
    project_id: types.optional(types.string()),
    leaf_count: types.optional(types.number()),
    created_at: types.optional(types.number()),
    mmr_root: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "epoch_id": "epochId",
      "project_id": "projectId",
      "leaf_count": "leafCount",
      "created_at": "createdAt",
      "mmr_root": "mmrRoot",
    });
  }),
);

export function epochsReadyResponseEpochFromJSON(
  jsonString: string,
): SafeParseResult<EpochsReadyResponseEpoch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EpochsReadyResponseEpoch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EpochsReadyResponseEpoch' from JSON`,
  );
}

/** @internal */
export const EpochsReadyResponse$inboundSchema: z.ZodMiniType<
  EpochsReadyResponse,
  unknown
> = z.object({
  success: types.boolean(),
  count: types.number(),
  epochs: z.array(z.lazy(() => EpochsReadyResponseEpoch$inboundSchema)),
});

export function epochsReadyResponseFromJSON(
  jsonString: string,
): SafeParseResult<EpochsReadyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EpochsReadyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EpochsReadyResponse' from JSON`,
  );
}
