/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * ERC-4337 UserOperation struct
 */
export type EstimateGasRequestUserOp = {};

export type EstimateGasRequest = {
  chainId: string;
  /**
   * ERC-4337 UserOperation struct
   */
  userOp: EstimateGasRequestUserOp;
};

/** @internal */
export type EstimateGasRequestUserOp$Outbound = {};

/** @internal */
export const EstimateGasRequestUserOp$outboundSchema: z.ZodMiniType<
  EstimateGasRequestUserOp$Outbound,
  EstimateGasRequestUserOp
> = z.object({});

export function estimateGasRequestUserOpToJSON(
  estimateGasRequestUserOp: EstimateGasRequestUserOp,
): string {
  return JSON.stringify(
    EstimateGasRequestUserOp$outboundSchema.parse(estimateGasRequestUserOp),
  );
}

/** @internal */
export type EstimateGasRequest$Outbound = {
  chainId: string;
  userOp: EstimateGasRequestUserOp$Outbound;
};

/** @internal */
export const EstimateGasRequest$outboundSchema: z.ZodMiniType<
  EstimateGasRequest$Outbound,
  EstimateGasRequest
> = z.object({
  chainId: z.string(),
  userOp: z.lazy(() => EstimateGasRequestUserOp$outboundSchema),
});

export function estimateGasRequestToJSON(
  estimateGasRequest: EstimateGasRequest,
): string {
  return JSON.stringify(
    EstimateGasRequest$outboundSchema.parse(estimateGasRequest),
  );
}
