/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Passport, Passport$inboundSchema } from "./passport.js";

export type GetPassportResponse = {
  success: boolean;
  passport: Passport;
};

/** @internal */
export const GetPassportResponse$inboundSchema: z.ZodMiniType<
  GetPassportResponse,
  unknown
> = z.object({
  success: types.boolean(),
  passport: Passport$inboundSchema,
});

export function getPassportResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPassportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPassportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPassportResponse' from JSON`,
  );
}
