/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type IdentityLink = {
  linkId?: string | undefined;
  primaryCaip10?: string | undefined;
  linkedCaip10?: string | undefined;
  createdAt?: string | undefined;
};

/** @internal */
export const IdentityLink$inboundSchema: z.ZodMiniType<IdentityLink, unknown> =
  z.object({
    linkId: types.optional(types.string()),
    primaryCaip10: types.optional(types.string()),
    linkedCaip10: types.optional(types.string()),
    createdAt: types.optional(types.string()),
  });

export function identityLinkFromJSON(
  jsonString: string,
): SafeParseResult<IdentityLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdentityLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdentityLink' from JSON`,
  );
}
