/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { IdentityLink, IdentityLink$inboundSchema } from "./identitylink.js";

export type IdentityLinkResponse = {
  success: boolean;
  link?: IdentityLink | undefined;
};

/** @internal */
export const IdentityLinkResponse$inboundSchema: z.ZodMiniType<
  IdentityLinkResponse,
  unknown
> = z.object({
  success: types.boolean(),
  link: types.optional(IdentityLink$inboundSchema),
});

export function identityLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdentityLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdentityLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdentityLinkResponse' from JSON`,
  );
}
