/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InferenceResult = {
  success: boolean;
  runId: string;
  requestId?: string | undefined;
  traceId?: string | undefined;
  text?: string | undefined;
  finishReason?: string | undefined;
  tokensIn: number;
  tokensOut: number;
  ttftMs: number;
  totalLatencyMs: number;
  modelPassportId: string;
  computePassportId: string;
  runtime: string;
  policyHash?: string | undefined;
  receiptId?: string | undefined;
  usedFallback?: boolean | undefined;
  fallbackReason?: string | undefined;
  error?: string | undefined;
  errorCode?: string | undefined;
};

/** @internal */
export const InferenceResult$inboundSchema: z.ZodMiniType<
  InferenceResult,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    run_id: types.string(),
    request_id: types.optional(types.string()),
    trace_id: types.optional(types.string()),
    text: types.optional(types.string()),
    finish_reason: types.optional(types.string()),
    tokens_in: types.number(),
    tokens_out: types.number(),
    ttft_ms: types.number(),
    total_latency_ms: types.number(),
    model_passport_id: types.string(),
    compute_passport_id: types.string(),
    runtime: types.string(),
    policy_hash: types.optional(types.string()),
    receipt_id: types.optional(types.string()),
    used_fallback: types.optional(types.boolean()),
    fallback_reason: types.optional(types.string()),
    error: types.optional(types.string()),
    error_code: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "run_id": "runId",
      "request_id": "requestId",
      "trace_id": "traceId",
      "finish_reason": "finishReason",
      "tokens_in": "tokensIn",
      "tokens_out": "tokensOut",
      "ttft_ms": "ttftMs",
      "total_latency_ms": "totalLatencyMs",
      "model_passport_id": "modelPassportId",
      "compute_passport_id": "computePassportId",
      "policy_hash": "policyHash",
      "receipt_id": "receiptId",
      "used_fallback": "usedFallback",
      "fallback_reason": "fallbackReason",
      "error_code": "errorCode",
    });
  }),
);

export function inferenceResultFromJSON(
  jsonString: string,
): SafeParseResult<InferenceResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InferenceResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InferenceResult' from JSON`,
  );
}
