/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type InstallModuleRequest = {
  chainId: string;
  /**
   * Smart account address
   */
  account: string;
  /**
   * Module type (validator, executor)
   */
  moduleType: string;
  /**
   * Module contract address
   */
  moduleAddress: string;
  /**
   * Optional init calldata (hex)
   */
  initData?: string | undefined;
};

/** @internal */
export type InstallModuleRequest$Outbound = {
  chainId: string;
  account: string;
  moduleType: string;
  moduleAddress: string;
  initData?: string | undefined;
};

/** @internal */
export const InstallModuleRequest$outboundSchema: z.ZodMiniType<
  InstallModuleRequest$Outbound,
  InstallModuleRequest
> = z.object({
  chainId: z.string(),
  account: z.string(),
  moduleType: z.string(),
  moduleAddress: z.string(),
  initData: z.optional(z.string()),
});

export function installModuleRequestToJSON(
  installModuleRequest: InstallModuleRequest,
): string {
  return JSON.stringify(
    InstallModuleRequest$outboundSchema.parse(installModuleRequest),
  );
}
