/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Deployment target provider
 */
export const LaunchImageRequestTarget = {
  Docker: "docker",
  Railway: "railway",
  Akash: "akash",
  Phala: "phala",
  Ionet: "ionet",
  Nosana: "nosana",
} as const;
/**
 * Deployment target provider
 */
export type LaunchImageRequestTarget = ClosedEnum<
  typeof LaunchImageRequestTarget
>;

/**
 * Verification mode (full includes receipts + memory + payment hooks)
 */
export const Verification = {
  Full: "full",
  Minimal: "minimal",
} as const;
/**
 * Verification mode (full includes receipts + memory + payment hooks)
 */
export type Verification = ClosedEnum<typeof Verification>;

/**
 * Private registry credentials (never stored, used at deploy time only)
 */
export type RegistryAuth = {
  username?: string | undefined;
  password?: string | undefined;
};

export type LaunchImageRequest = {
  /**
   * Launch mode — bring your own Docker image
   */
  mode: "image";
  /**
   * Docker image reference (e.g. ghcr.io/myorg/my-agent:latest)
   */
  image: string;
  /**
   * Deployment target provider
   */
  target: LaunchImageRequestTarget;
  /**
   * Owner wallet address (Solana base58 or EVM 0x)
   */
  owner: string;
  /**
   * Human-readable agent name
   */
  name: string;
  /**
   * Container port to expose (default 8080)
   */
  port?: number | undefined;
  /**
   * Verification mode (full includes receipts + memory + payment hooks)
   */
  verification?: Verification | undefined;
  /**
   * Additional environment variables injected into the container
   */
  envVars?: { [k: string]: string } | undefined;
  /**
   * Private registry credentials (never stored, used at deploy time only)
   */
  registryAuth?: RegistryAuth | undefined;
};

/** @internal */
export const LaunchImageRequestTarget$outboundSchema: z.ZodMiniEnum<
  typeof LaunchImageRequestTarget
> = z.enum(LaunchImageRequestTarget);

/** @internal */
export const Verification$outboundSchema: z.ZodMiniEnum<typeof Verification> = z
  .enum(Verification);

/** @internal */
export type RegistryAuth$Outbound = {
  username?: string | undefined;
  password?: string | undefined;
};

/** @internal */
export const RegistryAuth$outboundSchema: z.ZodMiniType<
  RegistryAuth$Outbound,
  RegistryAuth
> = z.object({
  username: z.optional(z.string()),
  password: z.optional(z.string()),
});

export function registryAuthToJSON(registryAuth: RegistryAuth): string {
  return JSON.stringify(RegistryAuth$outboundSchema.parse(registryAuth));
}

/** @internal */
export type LaunchImageRequest$Outbound = {
  mode: "image";
  image: string;
  target: string;
  owner: string;
  name: string;
  port?: number | undefined;
  verification: string;
  env_vars?: { [k: string]: string } | undefined;
  registry_auth?: RegistryAuth$Outbound | undefined;
};

/** @internal */
export const LaunchImageRequest$outboundSchema: z.ZodMiniType<
  LaunchImageRequest$Outbound,
  LaunchImageRequest
> = z.pipe(
  z.object({
    mode: z.literal("image"),
    image: z.string(),
    target: LaunchImageRequestTarget$outboundSchema,
    owner: z.string(),
    name: z.string(),
    port: z.optional(z.int()),
    verification: z._default(Verification$outboundSchema, "full"),
    envVars: z.optional(z.record(z.string(), z.string())),
    registryAuth: z.optional(z.lazy(() => RegistryAuth$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      envVars: "env_vars",
      registryAuth: "registry_auth",
    });
  }),
);

export function launchImageRequestToJSON(
  launchImageRequest: LaunchImageRequest,
): string {
  return JSON.stringify(
    LaunchImageRequest$outboundSchema.parse(launchImageRequest),
  );
}
