/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import { Passport, Passport$inboundSchema } from "./passport.js";

export type ListPassportsResponse = {
  success: boolean;
  passports: Array<Passport>;
  pagination: Pagination;
};

/** @internal */
export const ListPassportsResponse$inboundSchema: z.ZodMiniType<
  ListPassportsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  passports: z.array(Passport$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listPassportsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPassportsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPassportsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPassportsResponse' from JSON`,
  );
}
