/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Models = {};

export type ListZkMLModelsResponse = {
  success: boolean;
  models?: Models | undefined;
};

/** @internal */
export const Models$inboundSchema: z.ZodMiniType<Models, unknown> = z.object(
  {},
);

export function modelsFromJSON(
  jsonString: string,
): SafeParseResult<Models, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Models$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Models' from JSON`,
  );
}

/** @internal */
export const ListZkMLModelsResponse$inboundSchema: z.ZodMiniType<
  ListZkMLModelsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  models: types.optional(z.lazy(() => Models$inboundSchema)),
});

export function listZkMLModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListZkMLModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListZkMLModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListZkMLModelsResponse' from JSON`,
  );
}
