/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PassportStatus = {
  Active: "active",
  Deprecated: "deprecated",
  Revoked: "revoked",
} as const;
export type PassportStatus = OpenEnum<typeof PassportStatus>;

/** @internal */
export const PassportStatus$inboundSchema: z.ZodMiniType<
  PassportStatus,
  unknown
> = openEnums.inboundSchema(PassportStatus);
/** @internal */
export const PassportStatus$outboundSchema: z.ZodMiniType<
  string,
  PassportStatus
> = openEnums.outboundSchema(PassportStatus);
