/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PassportStatus,
  PassportStatus$inboundSchema,
} from "./passportstatus.js";
import { PassportType, PassportType$inboundSchema } from "./passporttype.js";

/**
 * Projection status
 */
export const PassportExternalRegistrationsStatus = {
  Synced: "synced",
  Failed: "failed",
  Pending: "pending",
} as const;
/**
 * Projection status
 */
export type PassportExternalRegistrationsStatus = OpenEnum<
  typeof PassportExternalRegistrationsStatus
>;

export type ExternalRegistrations = {
  /**
   * ID on the external registry (e.g., Metaplex asset pubkey)
   */
  externalId?: string | undefined;
  /**
   * Registration transaction signature
   */
  txSignature?: string | undefined;
  /**
   * ERC-8004 registration document URI on DePIN storage
   */
  registrationDocUri?: string | null | undefined;
  /**
   * Unix ms when first registered
   */
  registeredAt?: number | undefined;
  /**
   * Unix ms of last sync attempt
   */
  lastSyncedAt?: number | undefined;
  /**
   * Projection status
   */
  status?: PassportExternalRegistrationsStatus | undefined;
  /**
   * Last error message (null when synced)
   */
  lastError?: string | null | undefined;
};

export type OnChain = {
  pda?: string | null | undefined;
  tx?: string | null | undefined;
  syncedAt?: number | null | undefined;
};

export type Passport = {
  passportId: string;
  type: PassportType;
  owner: string;
  name?: string | null | undefined;
  description?: string | null | undefined;
  version?: string | null | undefined;
  tags?: Array<string> | null | undefined;
  status: PassportStatus;
  metadata?: { [k: string]: any } | null | undefined;
  metadataHash?: string | null | undefined;
  /**
   * DePIN storage CID for metadata
   */
  depinMetadataCid?: string | null | undefined;
  /**
   * DePIN provider used (arweave, lighthouse, mock)
   */
  depinProvider?: string | null | undefined;
  /**
   * NFT mint address (Solana base58 or EVM 0x)
   */
  nftMint?: string | null | undefined;
  /**
   * Chain where NFT was minted
   */
  nftChain?: string | null | undefined;
  /**
   * Share token SPL mint address
   */
  shareTokenMint?: string | null | undefined;
  /**
   * External identity projection status per registry (summary cache). Key is registry name.
   */
  externalRegistrations?:
    | { [k: string]: ExternalRegistrations }
    | null
    | undefined;
  createdAt: number;
  updatedAt: number;
  onChain?: OnChain | null | undefined;
};

/** @internal */
export const PassportExternalRegistrationsStatus$inboundSchema: z.ZodMiniType<
  PassportExternalRegistrationsStatus,
  unknown
> = openEnums.inboundSchema(PassportExternalRegistrationsStatus);

/** @internal */
export const ExternalRegistrations$inboundSchema: z.ZodMiniType<
  ExternalRegistrations,
  unknown
> = z.object({
  externalId: types.optional(types.string()),
  txSignature: types.optional(types.string()),
  registrationDocUri: z.optional(z.nullable(types.string())),
  registeredAt: types.optional(types.number()),
  lastSyncedAt: types.optional(types.number()),
  status: types.optional(PassportExternalRegistrationsStatus$inboundSchema),
  lastError: z.optional(z.nullable(types.string())),
});

export function externalRegistrationsFromJSON(
  jsonString: string,
): SafeParseResult<ExternalRegistrations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalRegistrations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalRegistrations' from JSON`,
  );
}

/** @internal */
export const OnChain$inboundSchema: z.ZodMiniType<OnChain, unknown> = z.pipe(
  z.object({
    pda: z.optional(z.nullable(types.string())),
    tx: z.optional(z.nullable(types.string())),
    synced_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "synced_at": "syncedAt",
    });
  }),
);

export function onChainFromJSON(
  jsonString: string,
): SafeParseResult<OnChain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnChain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnChain' from JSON`,
  );
}

/** @internal */
export const Passport$inboundSchema: z.ZodMiniType<Passport, unknown> = z.pipe(
  z.object({
    passport_id: types.string(),
    type: PassportType$inboundSchema,
    owner: types.string(),
    name: z.optional(z.nullable(types.string())),
    description: z.optional(z.nullable(types.string())),
    version: z.optional(z.nullable(types.string())),
    tags: z.optional(z.nullable(z.array(types.string()))),
    status: PassportStatus$inboundSchema,
    metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    metadata_hash: z.optional(z.nullable(types.string())),
    depin_metadata_cid: z.optional(z.nullable(types.string())),
    depin_provider: z.optional(z.nullable(types.string())),
    nft_mint: z.optional(z.nullable(types.string())),
    nft_chain: z.optional(z.nullable(types.string())),
    share_token_mint: z.optional(z.nullable(types.string())),
    external_registrations: z.optional(
      z.nullable(z.record(
        z.string(),
        z.lazy(() => ExternalRegistrations$inboundSchema),
      )),
    ),
    created_at: types.number(),
    updated_at: types.number(),
    on_chain: z.optional(z.nullable(z.lazy(() => OnChain$inboundSchema))),
  }),
  z.transform((v) => {
    return remap$(v, {
      "passport_id": "passportId",
      "metadata_hash": "metadataHash",
      "depin_metadata_cid": "depinMetadataCid",
      "depin_provider": "depinProvider",
      "nft_mint": "nftMint",
      "nft_chain": "nftChain",
      "share_token_mint": "shareTokenMint",
      "external_registrations": "externalRegistrations",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "on_chain": "onChain",
    });
  }),
);

export function passportFromJSON(
  jsonString: string,
): SafeParseResult<Passport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Passport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Passport' from JSON`,
  );
}
