/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PaymentGrantScope = {
  models: Array<string>;
  tools: Array<string>;
  maxPerCallUsd: number;
};

/** @internal */
export const PaymentGrantScope$inboundSchema: z.ZodMiniType<
  PaymentGrantScope,
  unknown
> = z.pipe(
  z.object({
    models: z.array(types.string()),
    tools: z.array(types.string()),
    max_per_call_usd: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_per_call_usd": "maxPerCallUsd",
    });
  }),
);
/** @internal */
export type PaymentGrantScope$Outbound = {
  models: Array<string>;
  tools: Array<string>;
  max_per_call_usd: number;
};

/** @internal */
export const PaymentGrantScope$outboundSchema: z.ZodMiniType<
  PaymentGrantScope$Outbound,
  PaymentGrantScope
> = z.pipe(
  z.object({
    models: z.array(z.string()),
    tools: z.array(z.string()),
    maxPerCallUsd: z.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxPerCallUsd: "max_per_call_usd",
    });
  }),
);

export function paymentGrantScopeToJSON(
  paymentGrantScope: PaymentGrantScope,
): string {
  return JSON.stringify(
    PaymentGrantScope$outboundSchema.parse(paymentGrantScope),
  );
}
export function paymentGrantScopeFromJSON(
  jsonString: string,
): SafeParseResult<PaymentGrantScope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentGrantScope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentGrantScope' from JSON`,
  );
}
