/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PayoutRecipient = {
  role: string;
  wallet: string;
  bp: number;
  /**
   * BigInt serialized as string
   */
  amountLamports: string;
};

/** @internal */
export const PayoutRecipient$inboundSchema: z.ZodMiniType<
  PayoutRecipient,
  unknown
> = z.pipe(
  z.object({
    role: types.string(),
    wallet: types.string(),
    bp: types.number(),
    amount_lamports: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "amount_lamports": "amountLamports",
    });
  }),
);

export function payoutRecipientFromJSON(
  jsonString: string,
): SafeParseResult<PayoutRecipient, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutRecipient$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutRecipient' from JSON`,
  );
}
