/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PayoutRecipient,
  PayoutRecipient$inboundSchema,
} from "./payoutrecipient.js";

export type Payout = {
  runId: string;
  /**
   * BigInt serialized as string
   */
  totalAmountLamports: string;
  recipients: Array<PayoutRecipient>;
  payoutHash: string;
  timestamp: number;
};

/** @internal */
export const Payout$inboundSchema: z.ZodMiniType<Payout, unknown> = z.pipe(
  z.object({
    run_id: types.string(),
    total_amount_lamports: types.string(),
    recipients: z.array(PayoutRecipient$inboundSchema),
    payout_hash: types.string(),
    timestamp: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "run_id": "runId",
      "total_amount_lamports": "totalAmountLamports",
      "payout_hash": "payoutHash",
    });
  }),
);

export function payoutFromJSON(
  jsonString: string,
): SafeParseResult<Payout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payout' from JSON`,
  );
}
