/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import {
  PayoutConfig,
  PayoutConfig$Outbound,
  PayoutConfig$outboundSchema,
} from "./payoutconfig.js";

export type TotalAmountLamports = string | number;

export type PayoutCalculateRequest = {
  runId: string;
  totalAmountLamports: string | number;
  computeWallet: string;
  modelWallet?: string | undefined;
  orchestratorWallet?: string | undefined;
  /**
   * Payout split configuration (basis points, must sum to 10000)
   */
  config?: PayoutConfig | undefined;
};

/** @internal */
export type TotalAmountLamports$Outbound = string | number;

/** @internal */
export const TotalAmountLamports$outboundSchema: z.ZodMiniType<
  TotalAmountLamports$Outbound,
  TotalAmountLamports
> = smartUnion([z.string(), z.int()]);

export function totalAmountLamportsToJSON(
  totalAmountLamports: TotalAmountLamports,
): string {
  return JSON.stringify(
    TotalAmountLamports$outboundSchema.parse(totalAmountLamports),
  );
}

/** @internal */
export type PayoutCalculateRequest$Outbound = {
  run_id: string;
  total_amount_lamports: string | number;
  compute_wallet: string;
  model_wallet?: string | undefined;
  orchestrator_wallet?: string | undefined;
  config?: PayoutConfig$Outbound | undefined;
};

/** @internal */
export const PayoutCalculateRequest$outboundSchema: z.ZodMiniType<
  PayoutCalculateRequest$Outbound,
  PayoutCalculateRequest
> = z.pipe(
  z.object({
    runId: z.string(),
    totalAmountLamports: smartUnion([z.string(), z.int()]),
    computeWallet: z.string(),
    modelWallet: z.optional(z.string()),
    orchestratorWallet: z.optional(z.string()),
    config: z.optional(PayoutConfig$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      runId: "run_id",
      totalAmountLamports: "total_amount_lamports",
      computeWallet: "compute_wallet",
      modelWallet: "model_wallet",
      orchestratorWallet: "orchestrator_wallet",
    });
  }),
);

export function payoutCalculateRequestToJSON(
  payoutCalculateRequest: PayoutCalculateRequest,
): string {
  return JSON.stringify(
    PayoutCalculateRequest$outboundSchema.parse(payoutCalculateRequest),
  );
}
