/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Direction = {
  L: "L",
  R: "R",
} as const;
export type Direction = OpenEnum<typeof Direction>;

export type ReceiptProof = {
  runId: string;
  receiptHash: string;
  /**
   * The leaf hash (receipt_hash) at leaf_index
   */
  leaf?: string | undefined;
  leafIndex: number;
  /**
   * Sibling hashes along the Merkle path
   */
  proof: Array<string>;
  root: string;
  /**
   * Direction of each sibling (L = sibling is on left, R = on right).
   */
  directions?: Array<Direction> | undefined;
};

/** @internal */
export const Direction$inboundSchema: z.ZodMiniType<Direction, unknown> =
  openEnums.inboundSchema(Direction);

/** @internal */
export const ReceiptProof$inboundSchema: z.ZodMiniType<ReceiptProof, unknown> =
  z.pipe(
    z.object({
      run_id: types.string(),
      receipt_hash: types.string(),
      leaf: types.optional(types.string()),
      leaf_index: types.number(),
      proof: z.array(types.string()),
      root: types.string(),
      directions: types.optional(z.array(Direction$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "run_id": "runId",
        "receipt_hash": "receiptHash",
        "leaf_index": "leafIndex",
      });
    }),
  );

export function receiptProofFromJSON(
  jsonString: string,
): SafeParseResult<ReceiptProof, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiptProof$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiptProof' from JSON`,
  );
}
