/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ReceiptVerification = {
  success?: boolean | undefined;
  valid?: boolean | undefined;
  hashValid?: boolean | undefined;
  signatureValid?: boolean | undefined;
  inclusionValid?: boolean | undefined;
  expectedHash?: string | undefined;
  computedHash?: string | undefined;
  merkleRoot?: string | undefined;
};

/** @internal */
export const ReceiptVerification$inboundSchema: z.ZodMiniType<
  ReceiptVerification,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    valid: types.optional(types.boolean()),
    hash_valid: types.optional(types.boolean()),
    signature_valid: types.optional(types.boolean()),
    inclusion_valid: types.optional(types.boolean()),
    expected_hash: types.optional(types.string()),
    computed_hash: types.optional(types.string()),
    merkle_root: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "hash_valid": "hashValid",
      "signature_valid": "signatureValid",
      "inclusion_valid": "inclusionValid",
      "expected_hash": "expectedHash",
      "computed_hash": "computedHash",
      "merkle_root": "merkleRoot",
    });
  }),
);

export function receiptVerificationFromJSON(
  jsonString: string,
): SafeParseResult<ReceiptVerification, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReceiptVerification$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReceiptVerification' from JSON`,
  );
}
