/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RegisterZkMLModelRequest = {
  chainId: string;
  modelHash: string;
  /**
   * Groth16 verifying key (hex)
   */
  verifyingKey: string;
};

/** @internal */
export type RegisterZkMLModelRequest$Outbound = {
  chainId: string;
  modelHash: string;
  verifyingKey: string;
};

/** @internal */
export const RegisterZkMLModelRequest$outboundSchema: z.ZodMiniType<
  RegisterZkMLModelRequest$Outbound,
  RegisterZkMLModelRequest
> = z.object({
  chainId: z.string(),
  modelHash: z.string(),
  verifyingKey: z.string(),
});

export function registerZkMLModelRequestToJSON(
  registerZkMLModelRequest: RegisterZkMLModelRequest,
): string {
  return JSON.stringify(
    RegisterZkMLModelRequest$outboundSchema.parse(registerZkMLModelRequest),
  );
}
