/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ReputationAlgorithmInfo = {
  id: string;
  name: string;
  version: string;
  description: string;
};

/** @internal */
export const ReputationAlgorithmInfo$inboundSchema: z.ZodMiniType<
  ReputationAlgorithmInfo,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  version: types.string(),
  description: types.string(),
});

export function reputationAlgorithmInfoFromJSON(
  jsonString: string,
): SafeParseResult<ReputationAlgorithmInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReputationAlgorithmInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReputationAlgorithmInfo' from JSON`,
  );
}
