/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ResolveIdentityRequest = {
  caip10: string;
};

/** @internal */
export type ResolveIdentityRequest$Outbound = {
  caip10: string;
};

/** @internal */
export const ResolveIdentityRequest$outboundSchema: z.ZodMiniType<
  ResolveIdentityRequest$Outbound,
  ResolveIdentityRequest
> = z.object({
  caip10: z.string(),
});

export function resolveIdentityRequestToJSON(
  resolveIdentityRequest: ResolveIdentityRequest,
): string {
  return JSON.stringify(
    ResolveIdentityRequest$outboundSchema.parse(resolveIdentityRequest),
  );
}
