/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type SetAssetPricingRequest = {
  /**
   * Micro-units (e.g. "10000" = $0.01)
   */
  pricePerCall?: string | undefined;
  pricePerToken?: string | undefined;
  priceSubscriptionHour?: string | undefined;
  acceptedTokens?: Array<string> | undefined;
  acceptedChains?: Array<string> | undefined;
  payoutAddress: string;
  customSplitBps?: { [k: string]: number } | undefined;
};

/** @internal */
export type SetAssetPricingRequest$Outbound = {
  price_per_call?: string | undefined;
  price_per_token?: string | undefined;
  price_subscription_hour?: string | undefined;
  accepted_tokens?: Array<string> | undefined;
  accepted_chains?: Array<string> | undefined;
  payout_address: string;
  custom_split_bps?: { [k: string]: number } | undefined;
};

/** @internal */
export const SetAssetPricingRequest$outboundSchema: z.ZodMiniType<
  SetAssetPricingRequest$Outbound,
  SetAssetPricingRequest
> = z.pipe(
  z.object({
    pricePerCall: z.optional(z.string()),
    pricePerToken: z.optional(z.string()),
    priceSubscriptionHour: z.optional(z.string()),
    acceptedTokens: z.optional(z.array(z.string())),
    acceptedChains: z.optional(z.array(z.string())),
    payoutAddress: z.string(),
    customSplitBps: z.optional(z.record(z.string(), z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      pricePerCall: "price_per_call",
      pricePerToken: "price_per_token",
      priceSubscriptionHour: "price_subscription_hour",
      acceptedTokens: "accepted_tokens",
      acceptedChains: "accepted_chains",
      payoutAddress: "payout_address",
      customSplitBps: "custom_split_bps",
    });
  }),
);

export function setAssetPricingRequestToJSON(
  setAssetPricingRequest: SetAssetPricingRequest,
): string {
  return JSON.stringify(
    SetAssetPricingRequest$outboundSchema.parse(setAssetPricingRequest),
  );
}
