/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * ERC-4337 UserOperation struct
 */
export type SponsorUserOpRequestUserOp = {};

export type SponsorUserOpRequest = {
  chainId: string;
  /**
   * ERC-4337 UserOperation struct
   */
  userOp: SponsorUserOpRequestUserOp;
};

/** @internal */
export type SponsorUserOpRequestUserOp$Outbound = {};

/** @internal */
export const SponsorUserOpRequestUserOp$outboundSchema: z.ZodMiniType<
  SponsorUserOpRequestUserOp$Outbound,
  SponsorUserOpRequestUserOp
> = z.object({});

export function sponsorUserOpRequestUserOpToJSON(
  sponsorUserOpRequestUserOp: SponsorUserOpRequestUserOp,
): string {
  return JSON.stringify(
    SponsorUserOpRequestUserOp$outboundSchema.parse(sponsorUserOpRequestUserOp),
  );
}

/** @internal */
export type SponsorUserOpRequest$Outbound = {
  chainId: string;
  userOp: SponsorUserOpRequestUserOp$Outbound;
};

/** @internal */
export const SponsorUserOpRequest$outboundSchema: z.ZodMiniType<
  SponsorUserOpRequest$Outbound,
  SponsorUserOpRequest
> = z.object({
  chainId: z.string(),
  userOp: z.lazy(() => SponsorUserOpRequestUserOp$outboundSchema),
});

export function sponsorUserOpRequestToJSON(
  sponsorUserOpRequest: SponsorUserOpRequest,
): string {
  return JSON.stringify(
    SponsorUserOpRequest$outboundSchema.parse(sponsorUserOpRequest),
  );
}
