/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SubmitEvidenceRequest = {
  chainId: string;
  receiptHash?: string | undefined;
  mmrRoot?: string | undefined;
  mmrProof?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export type SubmitEvidenceRequest$Outbound = {
  chainId: string;
  receiptHash?: string | undefined;
  mmrRoot?: string | undefined;
  mmrProof?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const SubmitEvidenceRequest$outboundSchema: z.ZodMiniType<
  SubmitEvidenceRequest$Outbound,
  SubmitEvidenceRequest
> = z.object({
  chainId: z.string(),
  receiptHash: z.optional(z.string()),
  mmrRoot: z.optional(z.string()),
  mmrProof: z.optional(z.string()),
  description: z.optional(z.string()),
});

export function submitEvidenceRequestToJSON(
  submitEvidenceRequest: SubmitEvidenceRequest,
): string {
  return JSON.stringify(
    SubmitEvidenceRequest$outboundSchema.parse(submitEvidenceRequest),
  );
}
