/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TokenLaunchResponse = {
  success: boolean;
  /**
   * SPL token mint address
   */
  mint: string;
  /**
   * Transaction signature
   */
  txSignature: string;
  totalSupply: number;
  /**
   * Token launcher provider used
   */
  provider: string;
};

/** @internal */
export const TokenLaunchResponse$inboundSchema: z.ZodMiniType<
  TokenLaunchResponse,
  unknown
> = z.object({
  success: types.boolean(),
  mint: types.string(),
  txSignature: types.string(),
  totalSupply: types.number(),
  provider: types.string(),
});

export function tokenLaunchResponseFromJSON(
  jsonString: string,
): SafeParseResult<TokenLaunchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenLaunchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenLaunchResponse' from JSON`,
  );
}
