/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Groth16 proof (a, b, c points)
 */
export type VerifyZkMLProofRequestProof = {};

export type VerifyZkMLProofRequest = {
  chainId: string;
  /**
   * Groth16 proof (a, b, c points)
   */
  proof: VerifyZkMLProofRequestProof;
  receiptHash: string;
};

/** @internal */
export type VerifyZkMLProofRequestProof$Outbound = {};

/** @internal */
export const VerifyZkMLProofRequestProof$outboundSchema: z.ZodMiniType<
  VerifyZkMLProofRequestProof$Outbound,
  VerifyZkMLProofRequestProof
> = z.object({});

export function verifyZkMLProofRequestProofToJSON(
  verifyZkMLProofRequestProof: VerifyZkMLProofRequestProof,
): string {
  return JSON.stringify(
    VerifyZkMLProofRequestProof$outboundSchema.parse(
      verifyZkMLProofRequestProof,
    ),
  );
}

/** @internal */
export type VerifyZkMLProofRequest$Outbound = {
  chainId: string;
  proof: VerifyZkMLProofRequestProof$Outbound;
  receiptHash: string;
};

/** @internal */
export const VerifyZkMLProofRequest$outboundSchema: z.ZodMiniType<
  VerifyZkMLProofRequest$Outbound,
  VerifyZkMLProofRequest
> = z.object({
  chainId: z.string(),
  proof: z.lazy(() => VerifyZkMLProofRequestProof$outboundSchema),
  receiptHash: z.string(),
});

export function verifyZkMLProofRequestToJSON(
  verifyZkMLProofRequest: VerifyZkMLProofRequest,
): string {
  return JSON.stringify(
    VerifyZkMLProofRequest$outboundSchema.parse(verifyZkMLProofRequest),
  );
}
