/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsLucidAccomplishAgentGoal } from "../funcs/agentsLucidAccomplishAgentGoal.js";
import { agentsLucidCheckAgentOrchestratorHealth } from "../funcs/agentsLucidCheckAgentOrchestratorHealth.js";
import { agentsLucidCheckExecutorHealth } from "../funcs/agentsLucidCheckExecutorHealth.js";
import { agentsLucidExecuteAgentFlowspec } from "../funcs/agentsLucidExecuteAgentFlowspec.js";
import { agentsLucidGenerateAgentProof } from "../funcs/agentsLucidGenerateAgentProof.js";
import { agentsLucidGetAgentHistory } from "../funcs/agentsLucidGetAgentHistory.js";
import { agentsLucidGetAgentOrchestratorHistory } from "../funcs/agentsLucidGetAgentOrchestratorHistory.js";
import { agentsLucidGetAgentRoot } from "../funcs/agentsLucidGetAgentRoot.js";
import { agentsLucidGetAgentStats } from "../funcs/agentsLucidGetAgentStats.js";
import { agentsLucidGetExecutorDecision } from "../funcs/agentsLucidGetExecutorDecision.js";
import { agentsLucidGetPlannerInfo } from "../funcs/agentsLucidGetPlannerInfo.js";
import { agentsLucidInitAgent } from "../funcs/agentsLucidInitAgent.js";
import { agentsLucidListAgents } from "../funcs/agentsLucidListAgents.js";
import { agentsLucidPlanAgentWorkflow } from "../funcs/agentsLucidPlanAgentWorkflow.js";
import { agentsLucidPreviewAgentWorkflow } from "../funcs/agentsLucidPreviewAgentWorkflow.js";
import { agentsLucidProcessAgentBatchEpochs } from "../funcs/agentsLucidProcessAgentBatchEpochs.js";
import { agentsLucidProcessAgentEpoch } from "../funcs/agentsLucidProcessAgentEpoch.js";
import { agentsLucidValidateFlowspec } from "../funcs/agentsLucidValidateFlowspec.js";
import { agentsLucidVerifyAgentMmr } from "../funcs/agentsLucidVerifyAgentMmr.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { AgentsCrosschain } from "./agentscrosschain.js";
import { Deploy } from "./deploy.js";
import { Launch } from "./launch.js";
import { Mirror } from "./mirror.js";
import { Revenue } from "./revenue.js";
import { Wallet } from "./wallet.js";

export class Agents extends ClientSDK {
  private _deploy?: Deploy;
  get deploy(): Deploy {
    return (this._deploy ??= new Deploy(this._options));
  }

  private _launch?: Launch;
  get launch(): Launch {
    return (this._launch ??= new Launch(this._options));
  }

  private _wallet?: Wallet;
  get wallet(): Wallet {
    return (this._wallet ??= new Wallet(this._options));
  }

  private _revenue?: Revenue;
  get revenue(): Revenue {
    return (this._revenue ??= new Revenue(this._options));
  }

  private _crosschain?: AgentsCrosschain;
  get crosschain(): AgentsCrosschain {
    return (this._crosschain ??= new AgentsCrosschain(this._options));
  }

  private _mirror?: Mirror;
  get mirror(): Mirror {
    return (this._mirror ??= new Mirror(this._options));
  }

  /**
   * Initialize an AI agent
   *
   * @remarks
   * DEPRECATED. Initialize or load a legacy agent for MMR-based proof-of-contribution tracking. Use /v1/agents/deploy instead for new agent deployments.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidInitAgent(
    request: models.AgentInitRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidInitAgentResponse> {
    return unwrapAsync(agentsLucidInitAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * Process an epoch for an agent
   *
   * @remarks
   * DEPRECATED. Process an epoch of vectors for a legacy agent, computing the MMR root and optionally anchoring on-chain. Use /v1/agents/* endpoints instead.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidProcessAgentEpoch(
    request: models.AgentEpochRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidProcessAgentEpochResponse> {
    return unwrapAsync(agentsLucidProcessAgentEpoch(
      this,
      request,
      options,
    ));
  }

  /**
   * Process multiple epochs in batch
   *
   * @remarks
   * DEPRECATED. Process multiple epochs in batch for one or more legacy agents. Returns per-epoch results with MMR roots and transaction signatures. Use /v1/agents/* endpoints instead.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidProcessAgentBatchEpochs(
    request: models.AgentBatchEpochsRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidProcessAgentBatchEpochsResponse> {
    return unwrapAsync(agentsLucidProcessAgentBatchEpochs(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate proof of contribution
   *
   * @remarks
   * DEPRECATED. Generate a cryptographic MMR proof of contribution for a specific vector submitted by a legacy agent. Use /v1/agents/{passportId}/proof instead.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGenerateAgentProof(
    request: models.AgentProofRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGenerateAgentProofResponse> {
    return unwrapAsync(agentsLucidGenerateAgentProof(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent statistics
   *
   * @remarks
   * DEPRECATED. Retrieve statistics and current status for a legacy agent including epoch count, total vectors, and current MMR root. Use /v1/agents/{passportId}/receipts instead.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetAgentStats(
    request: operations.LucidGetAgentStatsRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentStatsResponse> {
    return unwrapAsync(agentsLucidGetAgentStats(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent MMR root history
   *
   * @remarks
   * DEPRECATED. Retrieve a legacy agent's MMR root history across all epochs, ordered chronologically. Use /v1/agents/{passportId}/epoch instead.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetAgentHistory(
    request: operations.LucidGetAgentHistoryRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentHistoryResponse> {
    return unwrapAsync(agentsLucidGetAgentHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current MMR root for agent
   *
   * @remarks
   * DEPRECATED. Retrieve the current MMR root hash for a legacy agent. Use /v1/agents/{passportId}/proof instead for the modern equivalent.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetAgentRoot(
    request: operations.LucidGetAgentRootRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentRootResponse> {
    return unwrapAsync(agentsLucidGetAgentRoot(
      this,
      request,
      options,
    ));
  }

  /**
   * Verify MMR integrity for agent
   *
   * @remarks
   * DEPRECATED. Verify the MMR integrity for a legacy agent by recomputing the tree and comparing roots. Use /v1/receipts/{receipt_id}/verify for receipt-level verification.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidVerifyAgentMmr(
    request: operations.LucidVerifyAgentMmrRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidVerifyAgentMmrResponse> {
    return unwrapAsync(agentsLucidVerifyAgentMmr(
      this,
      request,
      options,
    ));
  }

  /**
   * List all registered agents
   *
   * @remarks
   * DEPRECATED. List all legacy registered agents with their statistics. Use GET /v1/agents (lucid_list_agent_passports) for the modern passport-based agent listing.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidListAgents(
    options?: RequestOptions,
  ): Promise<operations.LucidListAgentsResponse> {
    return unwrapAsync(agentsLucidListAgents(
      this,
      options,
    ));
  }

  /**
   * Plan a workflow from a goal
   *
   * @remarks
   * DEPRECATED. Plan a multi-step workflow from a natural language goal using the CrewAI planner. Returns a FlowSpec, reasoning explanation, and complexity estimate.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidPlanAgentWorkflow(
    request: models.AgentPlanRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidPlanAgentWorkflowResponse> {
    return unwrapAsync(agentsLucidPlanAgentWorkflow(
      this,
      request,
      options,
    ));
  }

  /**
   * Plan and execute a workflow in one call
   *
   * @remarks
   * DEPRECATED. Plan and execute a complete workflow in a single call via the Agent Orchestrator. Combines planning and execution with automatic executor selection.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidAccomplishAgentGoal(
    request: models.AgentAccomplishRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidAccomplishAgentGoalResponse> {
    return unwrapAsync(agentsLucidAccomplishAgentGoal(
      this,
      request,
      options,
    ));
  }

  /**
   * Preview a workflow without executing
   *
   * @remarks
   * DEPRECATED. Generate a workflow preview (dry run) from a natural language goal without executing it. Returns the FlowSpec and reasoning for review before committing.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidPreviewAgentWorkflow(
    request: operations.LucidPreviewAgentWorkflowRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidPreviewAgentWorkflowResponse> {
    return unwrapAsync(agentsLucidPreviewAgentWorkflow(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent execution history for a tenant
   *
   * @remarks
   * DEPRECATED. Retrieve the execution history for a specific tenant, including workflow results, timing, and status. Supports an optional limit parameter.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetAgentOrchestratorHistory(
    request: operations.LucidGetAgentOrchestratorHistoryRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentOrchestratorHistoryResponse> {
    return unwrapAsync(agentsLucidGetAgentOrchestratorHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Agent orchestrator health check
   *
   * @remarks
   * DEPRECATED. Check the health of all agent orchestrator sub-services (planner, executor router, n8n, LangGraph). Returns per-service status.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidCheckAgentOrchestratorHealth(
    options?: RequestOptions,
  ): Promise<operations.LucidCheckAgentOrchestratorHealthResponse> {
    return unwrapAsync(agentsLucidCheckAgentOrchestratorHealth(
      this,
      options,
    ));
  }

  /**
   * Execute a FlowSpec
   *
   * @remarks
   * DEPRECATED. Execute a FlowSpec workflow with automatic executor selection (n8n or LangGraph). Requires a tenant context with tenantId for execution tracking.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidExecuteAgentFlowspec(
    request: operations.LucidExecuteAgentFlowspecRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidExecuteAgentFlowspecResponse> {
    return unwrapAsync(agentsLucidExecuteAgentFlowspec(
      this,
      request,
      options,
    ));
  }

  /**
   * Validate a FlowSpec structure
   *
   * @remarks
   * DEPRECATED. Validate a FlowSpec structure for correctness without executing it. Returns validation results including any errors or warnings found in the spec.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidValidateFlowspec(
    request: { [k: string]: any },
    options?: RequestOptions,
  ): Promise<operations.LucidValidateFlowspecResponse> {
    return unwrapAsync(agentsLucidValidateFlowspec(
      this,
      request,
      options,
    ));
  }

  /**
   * Get planner service info
   *
   * @remarks
   * DEPRECATED. Retrieve the agent planner service information including status, available planning backends, and configuration details.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetPlannerInfo(
    options?: RequestOptions,
  ): Promise<operations.LucidGetPlannerInfoResponse> {
    return unwrapAsync(agentsLucidGetPlannerInfo(
      this,
      options,
    ));
  }

  /**
   * Check executor health
   *
   * @remarks
   * DEPRECATED. Check the health of all executor backends (n8n, LangGraph), returning a boolean status for each. Used for operational monitoring.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidCheckExecutorHealth(
    options?: RequestOptions,
  ): Promise<operations.LucidCheckExecutorHealthResponse> {
    return unwrapAsync(agentsLucidCheckExecutorHealth(
      this,
      options,
    ));
  }

  /**
   * Get executor decision for a FlowSpec
   *
   * @remarks
   * DEPRECATED. Get the recommended executor for a FlowSpec without actually running it. Returns the executor choice (n8n or langgraph) and the reasoning behind the decision.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async lucidGetExecutorDecision(
    request: operations.LucidGetExecutorDecisionRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetExecutorDecisionResponse> {
    return unwrapAsync(agentsLucidGetExecutorDecision(
      this,
      request,
      options,
    ));
  }
}
