/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chainsLucidGetChainStatus } from "../funcs/chainsLucidGetChainStatus.js";
import { chainsLucidListChains } from "../funcs/chainsLucidListChains.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chains extends ClientSDK {
  /**
   * List supported chains
   *
   * @remarks
   * List all supported chains with connection status and ERC-8004 info.
   */
  async lucidListChains(
    options?: RequestOptions,
  ): Promise<operations.LucidListChainsResponse> {
    return unwrapAsync(chainsLucidListChains(
      this,
      options,
    ));
  }

  /**
   * Get chain status
   *
   * @remarks
   * Get detailed status for a specific chain including account address.
   */
  async lucidGetChainStatus(
    request: operations.LucidGetChainStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetChainStatusResponse> {
    return unwrapAsync(chainsLucidGetChainStatus(
      this,
      request,
      options,
    ));
  }
}
