/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsCommitRoot } from "../funcs/epochsCommitRoot.js";
import { epochsCommitRootsBatch } from "../funcs/epochsCommitRootsBatch.js";
import { epochsCreate } from "../funcs/epochsCreate.js";
import { epochsGet } from "../funcs/epochsGet.js";
import { epochsGetAnchoringHealth } from "../funcs/epochsGetAnchoringHealth.js";
import { epochsGetCurrent } from "../funcs/epochsGetCurrent.js";
import { epochsGetStats } from "../funcs/epochsGetStats.js";
import { epochsGetTransaction } from "../funcs/epochsGetTransaction.js";
import { epochsList } from "../funcs/epochsList.js";
import { epochsListReady } from "../funcs/epochsListReady.js";
import { epochsRetry } from "../funcs/epochsRetry.js";
import { epochsVerify } from "../funcs/epochsVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Epochs extends ClientSDK {
  /**
   * Get current epoch
   *
   * @remarks
   * Retrieve the current open epoch, optionally filtered by project_id. Returns epoch metadata including MMR root, leaf count, status, and timestamps.
   */
  async getCurrent(
    request?: operations.LucidGetCurrentEpochRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.LucidGetCurrentEpochResponse> {
    return unwrapAsync(epochsGetCurrent(
      this,
      request,
      options,
    ));
  }

  /**
   * List epochs
   *
   * @remarks
   * Retrieve a paginated list of epochs with optional filtering by project_id and status (open, anchoring, anchored, failed). Defaults to page 1, 20 results per page.
   */
  async list(
    request?: operations.LucidListEpochsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.LucidListEpochsResponse, { page: number }>
  > {
    return unwrapResultIterator(epochsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create epoch
   *
   * @remarks
   * Create a new epoch, optionally scoped to a project_id. The epoch starts in 'open' status with an empty MMR root and zero leaf count.
   */
  async create(
    request: operations.LucidCreateEpochRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidCreateEpochResponse> {
    return unwrapAsync(epochsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get epoch
   *
   * @remarks
   * Retrieve a single epoch by its epoch_id, including the MMR root, leaf count, status, and on-chain anchoring details.
   */
  async get(
    request: operations.LucidGetEpochRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetEpochResponse> {
    return unwrapAsync(epochsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Retry failed epoch
   *
   * @remarks
   * Retry the on-chain anchoring for an epoch that previously failed. The epoch must be in 'failed' status. Resets the status and re-submits the Solana transaction.
   */
  async retry(
    request: operations.LucidRetryEpochRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidRetryEpochResponse> {
    return unwrapAsync(epochsRetry(
      this,
      request,
      options,
    ));
  }

  /**
   * Verify epoch anchor
   *
   * @remarks
   * Verify an epoch's on-chain anchor by comparing the committed MMR root on Solana with the expected off-chain root. Returns the comparison result and transaction signature.
   */
  async verify(
    request: operations.LucidVerifyEpochRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidVerifyEpochResponse> {
    return unwrapAsync(epochsVerify(
      this,
      request,
      options,
    ));
  }

  /**
   * Get epoch anchoring transaction
   *
   * @remarks
   * Retrieve the Solana transaction details for an epoch's on-chain anchoring, including the transaction signature, slot number, and block time.
   */
  async getTransaction(
    request: operations.LucidGetEpochTransactionRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetEpochTransactionResponse> {
    return unwrapAsync(epochsGetTransaction(
      this,
      request,
      options,
    ));
  }

  /**
   * Commit epoch root
   *
   * @remarks
   * Finalize the current epoch and commit its MMR root to Solana via the thought_epoch program. Optionally force-commit even if the epoch threshold has not been reached.
   */
  async commitRoot(
    request: operations.LucidCommitEpochRootRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidCommitEpochRootResponse> {
    return unwrapAsync(epochsCommitRoot(
      this,
      request,
      options,
    ));
  }

  /**
   * Commit multiple epoch roots
   *
   * @remarks
   * Commit multiple epoch roots to Solana in a single batch operation. Returns per-epoch success/failure results with transaction signatures. Uses the batch commit instruction for gas efficiency.
   */
  async commitRootsBatch(
    request: operations.LucidCommitEpochRootsBatchRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidCommitEpochRootsBatchResponse> {
    return unwrapAsync(epochsCommitRootsBatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Anchoring service health
   *
   * @remarks
   * Check the health of the on-chain anchoring service, including Solana connection status, network type, authority address, and whether mock mode is active.
   */
  async getAnchoringHealth(
    options?: RequestOptions,
  ): Promise<operations.LucidGetAnchoringHealthResponse> {
    return unwrapAsync(epochsGetAnchoringHealth(
      this,
      options,
    ));
  }

  /**
   * Get epochs ready for finalization
   *
   * @remarks
   * List all epochs that have met the finalization threshold (more than 100 receipts or older than 1 hour) and are ready to be committed on-chain.
   */
  async listReady(
    options?: RequestOptions,
  ): Promise<models.EpochsReadyResponse> {
    return unwrapAsync(epochsListReady(
      this,
      options,
    ));
  }

  /**
   * Epoch statistics
   *
   * @remarks
   * Retrieve aggregate epoch statistics including total count, counts by status, average receipts per epoch, and anchoring success rate.
   */
  async getStats(
    options?: RequestOptions,
  ): Promise<models.EpochStatsResponse> {
    return unwrapAsync(epochsGetStats(
      this,
      options,
    ));
  }
}
