/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { escrowLucidCreateEscrow } from "../funcs/escrowLucidCreateEscrow.js";
import { escrowLucidDisputeEscrow } from "../funcs/escrowLucidDisputeEscrow.js";
import { escrowLucidGetEscrow } from "../funcs/escrowLucidGetEscrow.js";
import { escrowLucidReleaseEscrow } from "../funcs/escrowLucidReleaseEscrow.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Escrow extends ClientSDK {
  /**
   * Create a time-locked escrow
   *
   * @remarks
   * Create a new time-locked escrow for agent-to-agent transactions on a specific chain. Funds are held until released by receipt verification or timed out.
   */
  async lucidCreateEscrow(
    request: models.CreateEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowLucidCreateEscrow(
      this,
      request,
      options,
    ));
  }

  /**
   * Release escrow with verified receipt
   *
   * @remarks
   * Release escrowed funds to the beneficiary after verifying the associated receipt. Requires a valid receipt hash proving service delivery.
   */
  async lucidReleaseEscrow(
    request: models.ReleaseEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowLucidReleaseEscrow(
      this,
      request,
      options,
    ));
  }

  /**
   * Dispute an escrow
   *
   * @remarks
   * Dispute an active escrow, freezing the funds and initiating the arbitration process. The escrow must be in 'active' status to be disputed.
   */
  async lucidDisputeEscrow(
    request: models.DisputeEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowLucidDisputeEscrow(
      this,
      request,
      options,
    ));
  }

  /**
   * Get escrow details
   *
   * @remarks
   * Retrieve the full details of a specific escrow by chain and escrow ID, including status, parties, amounts, timeout, and associated receipt hashes.
   */
  async lucidGetEscrow(
    request: operations.LucidGetEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.GetEscrowResponse> {
    return unwrapAsync(escrowLucidGetEscrow(
      this,
      request,
      options,
    ));
  }
}
