/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthLucidCheckDatabaseHealth } from "../funcs/healthLucidCheckDatabaseHealth.js";
import { healthLucidCheckLiveness } from "../funcs/healthLucidCheckLiveness.js";
import { healthLucidCheckNangoHealth } from "../funcs/healthLucidCheckNangoHealth.js";
import { healthLucidCheckReadiness } from "../funcs/healthLucidCheckReadiness.js";
import { healthLucidCheckRedisHealth } from "../funcs/healthLucidCheckRedisHealth.js";
import { healthLucidCheckSystemHealth } from "../funcs/healthLucidCheckSystemHealth.js";
import { healthLucidGetDetailedHealth } from "../funcs/healthLucidGetDetailedHealth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Overall system health
   *
   * @remarks
   * Check overall system health including all dependencies (database, Redis, Solana, Nango). Returns healthy, degraded, or down status with a 200 when healthy or 503 when degraded/down. Use /health/detailed for resource metrics.
   */
  async lucidCheckSystemHealth(
    options?: RequestOptions,
  ): Promise<models.SystemHealth> {
    return unwrapAsync(healthLucidCheckSystemHealth(
      this,
      options,
    ));
  }

  /**
   * Liveness probe
   *
   * @remarks
   * Kubernetes-compatible liveness probe. Returns 200 if the application process is alive. Does not check dependencies. Use /health/ready for full readiness.
   */
  async lucidCheckLiveness(
    options?: RequestOptions,
  ): Promise<operations.LucidCheckLivenessResponse> {
    return unwrapAsync(healthLucidCheckLiveness(
      this,
      options,
    ));
  }

  /**
   * Readiness probe
   *
   * @remarks
   * Kubernetes-compatible readiness probe. Checks all dependencies (database, Redis, etc.) and returns 200 only when the service is ready to accept traffic. Returns 503 with dependency status details when not ready.
   */
  async lucidCheckReadiness(
    options?: RequestOptions,
  ): Promise<operations.LucidCheckReadinessResponse> {
    return unwrapAsync(healthLucidCheckReadiness(
      this,
      options,
    ));
  }

  /**
   * Database health check
   *
   * @remarks
   * Check database (PostgreSQL/Supabase) connectivity and query latency. Returns 503 when the database is unreachable.
   */
  async lucidCheckDatabaseHealth(
    options?: RequestOptions,
  ): Promise<models.HealthCheckResult> {
    return unwrapAsync(healthLucidCheckDatabaseHealth(
      this,
      options,
    ));
  }

  /**
   * Redis health check
   *
   * @remarks
   * Check Redis connectivity and latency. Redis is used for spent proof deduplication and caching. Returns 503 when Redis is unreachable.
   */
  async lucidCheckRedisHealth(
    options?: RequestOptions,
  ): Promise<models.HealthCheckResult> {
    return unwrapAsync(healthLucidCheckRedisHealth(
      this,
      options,
    ));
  }

  /**
   * Nango service health check
   *
   * @remarks
   * Check Nango OAuth service connectivity. Nango manages third-party OAuth connections for agent integrations. Returns 503 when Nango is unreachable.
   */
  async lucidCheckNangoHealth(
    options?: RequestOptions,
  ): Promise<models.HealthCheckResult> {
    return unwrapAsync(healthLucidCheckNangoHealth(
      this,
      options,
    ));
  }

  /**
   * Detailed health with statistics
   *
   * @remarks
   * Detailed health check including system resources (memory, CPU), per-dependency status, version info, environment, and aggregate statistics. Use this for operational dashboards and monitoring.
   */
  async lucidGetDetailedHealth(
    options?: RequestOptions,
  ): Promise<operations.LucidGetDetailedHealthResponse> {
    return unwrapAsync(healthLucidGetDetailedHealth(
      this,
      options,
    ));
  }
}
