/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { matchCompute } from "../funcs/matchCompute.js";
import { matchExplain } from "../funcs/matchExplain.js";
import { matchPlanRoute } from "../funcs/matchPlanRoute.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Match extends ClientSDK {
  /**
   * Evaluate policy against compute/model meta
   */
  async explain(
    request: operations.LucidMatchExplainRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidMatchExplainResponse> {
    return unwrapAsync(matchExplain(
      this,
      request,
      options,
    ));
  }

  /**
   * Match compute for model
   */
  async compute(
    request: operations.LucidMatchRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidMatchResponse> {
    return unwrapAsync(matchCompute(
      this,
      request,
      options,
    ));
  }

  /**
   * Plan a route (match + resolve endpoint)
   */
  async planRoute(
    request: operations.LucidRouteRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidRouteResponse> {
    return unwrapAsync(matchPlanRoute(
      this,
      request,
      options,
    ));
  }
}
