/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modulesLucidConfigurePayoutModule } from "../funcs/modulesLucidConfigurePayoutModule.js";
import { modulesLucidConfigurePolicyModule } from "../funcs/modulesLucidConfigurePolicyModule.js";
import { modulesLucidInstallModule } from "../funcs/modulesLucidInstallModule.js";
import { modulesLucidListModules } from "../funcs/modulesLucidListModules.js";
import { modulesLucidUninstallModule } from "../funcs/modulesLucidUninstallModule.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Modules extends ClientSDK {
  /**
   * Install module on smart account
   *
   * @remarks
   * Install an ERC-7579 module (policy, payout, or receipt) on a smart account. The module type and initialization data must be provided in the request body.
   */
  async lucidInstallModule(
    request: models.InstallModuleRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesLucidInstallModule(
      this,
      request,
      options,
    ));
  }

  /**
   * Uninstall module from smart account
   *
   * @remarks
   * Uninstall an ERC-7579 module from a smart account. Requires the module address and type to identify which module to remove.
   */
  async lucidUninstallModule(
    request: models.UninstallModuleRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesLucidUninstallModule(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure policy module
   *
   * @remarks
   * Configure allowed policy hashes on the LucidPolicyModule. Only transactions matching an allowed policy hash will be permitted by the module.
   */
  async lucidConfigurePolicyModule(
    request: models.ConfigurePolicyRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesLucidConfigurePolicyModule(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure payout module
   *
   * @remarks
   * Configure the revenue split percentages on the LucidPayoutModule. Sets the basis-point allocations for compute, model, and protocol recipients.
   */
  async lucidConfigurePayoutModule(
    request: models.ConfigurePayoutRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesLucidConfigurePayoutModule(
      this,
      request,
      options,
    ));
  }

  /**
   * List installed modules
   *
   * @remarks
   * List all ERC-7579 modules installed on a smart account, including module type, address, and configuration status for each.
   */
  async lucidListModules(
    request: operations.LucidListModulesRequest,
    options?: RequestOptions,
  ): Promise<models.ListModulesResponse> {
    return unwrapAsync(modulesLucidListModules(
      this,
      request,
      options,
    ));
  }
}
