/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { payoutsCrosschainLucidExecutePayoutOnChain } from "../funcs/payoutsCrosschainLucidExecutePayoutOnChain.js";
import { payoutsCrosschainLucidGetPayoutExecution } from "../funcs/payoutsCrosschainLucidGetPayoutExecution.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PayoutsCrosschain extends ClientSDK {
  /**
   * Execute payout on-chain
   *
   * @remarks
   * Execute a payout split on-chain via USDC transfers.
   */
  async lucidExecutePayoutOnChain(
    request: operations.LucidExecutePayoutOnChainRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidExecutePayoutOnChainResponse> {
    return unwrapAsync(payoutsCrosschainLucidExecutePayoutOnChain(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payout execution status
   *
   * @remarks
   * Get the execution status and details for a specific payout.
   */
  async lucidGetPayoutExecution(
    request: operations.LucidGetPayoutExecutionRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetPayoutExecutionResponse> {
    return unwrapAsync(payoutsCrosschainLucidGetPayoutExecution(
      this,
      request,
      options,
    ));
  }
}
