/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reputationLucidComputeReputation } from "../funcs/reputationLucidComputeReputation.js";
import { reputationLucidGetCompositeReputation } from "../funcs/reputationLucidGetCompositeReputation.js";
import { reputationLucidListReputationAlgorithms } from "../funcs/reputationLucidListReputationAlgorithms.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { ReputationCrosschain } from "./reputationcrosschain.js";

export class Reputation extends ClientSDK {
  private _crosschain?: ReputationCrosschain;
  get crosschain(): ReputationCrosschain {
    return (this._crosschain ??= new ReputationCrosschain(this._options));
  }

  /**
   * List available scoring algorithms
   *
   * @remarks
   * List all registered reputation scoring algorithms with their IDs, names, descriptions, and version information. Used to discover available algorithms before computing scores.
   */
  async lucidListReputationAlgorithms(
    options?: RequestOptions,
  ): Promise<operations.LucidListReputationAlgorithmsResponse> {
    return unwrapAsync(reputationLucidListReputationAlgorithms(
      this,
      options,
    ));
  }

  /**
   * Compute reputation score
   *
   * @remarks
   * Compute a reputation score for an agent using a specific algorithm.
   * Defaults to `receipt-volume-v1` if no algorithmId is provided.
   */
  async lucidComputeReputation(
    request: operations.LucidComputeReputationRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidComputeReputationResponse> {
    return unwrapAsync(reputationLucidComputeReputation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get composite reputation score
   *
   * @remarks
   * Computes a composite reputation score from all registered algorithms
   * with equal weighting.
   */
  async lucidGetCompositeReputation(
    request: operations.LucidGetCompositeReputationRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetCompositeReputationResponse> {
    return unwrapAsync(reputationLucidGetCompositeReputation(
      this,
      request,
      options,
    ));
  }
}
