/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsRevenueLucidGetAgentRevenue } from "../funcs/agentsRevenueLucidGetAgentRevenue.js";
import { agentsRevenueLucidGetAgentRevenueHistory } from "../funcs/agentsRevenueLucidGetAgentRevenueHistory.js";
import { agentsRevenueLucidTriggerAgentAirdrop } from "../funcs/agentsRevenueLucidTriggerAgentAirdrop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Revenue extends ClientSDK {
  /**
   * Get agent revenue pool status
   *
   * @remarks
   * Retrieve the accumulated revenue pool for an agent, including total earned, pending distribution, and the share token configuration if launched.
   */
  async lucidGetAgentRevenue(
    request: operations.LucidGetAgentRevenueRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentRevenueResponse> {
    return unwrapAsync(agentsRevenueLucidGetAgentRevenue(
      this,
      request,
      options,
    ));
  }

  /**
   * Trigger revenue airdrop to share token holders
   *
   * @remarks
   * Admin-only. Distributes accumulated agent revenue to share token holders
   * proportionally based on their holdings.
   */
  async lucidTriggerAgentAirdrop(
    request: operations.LucidTriggerAgentAirdropRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidTriggerAgentAirdropResponse> {
    return unwrapAsync(agentsRevenueLucidTriggerAgentAirdrop(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent payout history
   *
   * @remarks
   * Retrieve the complete payout history for an agent, including airdrop distributions, amounts, recipient counts, and timestamps.
   */
  async lucidGetAgentRevenueHistory(
    request: operations.LucidGetAgentRevenueHistoryRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentRevenueHistoryResponse> {
    return unwrapAsync(agentsRevenueLucidGetAgentRevenueHistory(
      this,
      request,
      options,
    ));
  }
}
