/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Agents } from "./agents.js";
import { Compute } from "./compute.js";
import { Epochs } from "./epochs.js";
import { Health } from "./health.js";
import { Match } from "./match.js";
import { Passports } from "./passports.js";
import { Payouts } from "./payouts.js";
import { Receipts } from "./receipts.js";
import { Run } from "./run.js";

export class RaijinLabsLucidAi extends ClientSDK {
  private _passports?: Passports;
  get passports(): Passports {
    return (this._passports ??= new Passports(this._options));
  }

  private _compute?: Compute;
  get compute(): Compute {
    return (this._compute ??= new Compute(this._options));
  }

  private _match?: Match;
  get match(): Match {
    return (this._match ??= new Match(this._options));
  }

  private _run?: Run;
  get run(): Run {
    return (this._run ??= new Run(this._options));
  }

  private _receipts?: Receipts;
  get receipts(): Receipts {
    return (this._receipts ??= new Receipts(this._options));
  }

  private _epochs?: Epochs;
  get epochs(): Epochs {
    return (this._epochs ??= new Epochs(this._options));
  }

  private _payouts?: Payouts;
  get payouts(): Payouts {
    return (this._payouts ??= new Payouts(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _agents?: Agents;
  get agents(): Agents {
    return (this._agents ??= new Agents(this._options));
  }
}
