/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsWalletLucidAgentWalletSend } from "../funcs/agentsWalletLucidAgentWalletSend.js";
import { agentsWalletLucidGetAgentWalletBalance } from "../funcs/agentsWalletLucidGetAgentWalletBalance.js";
import { agentsWalletLucidGetAgentWalletPolicy } from "../funcs/agentsWalletLucidGetAgentWalletPolicy.js";
import { agentsWalletLucidSetAgentWalletLimits } from "../funcs/agentsWalletLucidSetAgentWalletLimits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Wallet extends ClientSDK {
  /**
   * Get agent wallet balance
   *
   * @remarks
   * Retrieve the wallet balance for a deployed agent's PDA wallet, including SOL and token balances on the configured chain.
   */
  async lucidGetAgentWalletBalance(
    request: operations.LucidGetAgentWalletBalanceRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentWalletBalanceResponse> {
    return unwrapAsync(agentsWalletLucidGetAgentWalletBalance(
      this,
      request,
      options,
    ));
  }

  /**
   * Send from agent wallet
   *
   * @remarks
   * Admin-only. Execute a policy-gated transaction from the agent's PDA wallet.
   */
  async lucidAgentWalletSend(
    request: operations.LucidAgentWalletSendRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidAgentWalletSendResponse> {
    return unwrapAsync(agentsWalletLucidAgentWalletSend(
      this,
      request,
      options,
    ));
  }

  /**
   * Set agent wallet spending limits
   *
   * @remarks
   * Admin-only. Set per-transaction and daily spending limits.
   */
  async lucidSetAgentWalletLimits(
    request: operations.LucidSetAgentWalletLimitsRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidSetAgentWalletLimitsResponse> {
    return unwrapAsync(agentsWalletLucidSetAgentWalletLimits(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent wallet policy
   *
   * @remarks
   * Retrieve the wallet policy and configuration for an agent, including the wallet address, chain, provider type, and any spending constraints.
   */
  async lucidGetAgentWalletPolicy(
    request: operations.LucidGetAgentWalletPolicyRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetAgentWalletPolicyResponse> {
    return unwrapAsync(agentsWalletLucidGetAgentWalletPolicy(
      this,
      request,
      options,
    ));
  }
}
