/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsInitAgent } from "../../funcs/agentsInitAgent.js";
import { AgentInitRequest$zodSchema } from "../../models/initagentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AgentInitRequest$zodSchema,
};

export const tool$agentsInitAgent: ToolDefinition<typeof args> = {
  name: "init_agent",
  description: `Initialize or load an AI agent for MMR-based proof-of-contribution.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsInitAgent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
