/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetExecutorDecision } from "../../funcs/agentsGetExecutorDecision.js";
import { GetExecutorDecisionRequest$zodSchema } from "../../models/getexecutordecisionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetExecutorDecisionRequest$zodSchema,
};

export const tool$agentsGetExecutorDecision: ToolDefinition<typeof args> = {
  name: "get_executor_decision",
  description: `Get recommended executor for a FlowSpec without executing.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsGetExecutorDecision(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
