/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsAccomplishAgentGoal } from "../../funcs/agentsAccomplishAgentGoal.js";
import { AgentAccomplishRequest$zodSchema } from "../../models/accomplishagentgoalop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AgentAccomplishRequest$zodSchema,
};

export const tool$agentsAccomplishAgentGoal: ToolDefinition<typeof args> = {
  name: "accomplish_agent_goal",
  description: `Plan and execute a workflow in one call via the Agent Orchestrator.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsAccomplishAgentGoal(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
