/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsPreviewAgentWorkflow } from "../../funcs/agentsPreviewAgentWorkflow.js";
import { PreviewAgentWorkflowRequest$zodSchema } from "../../models/previewagentworkflowop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PreviewAgentWorkflowRequest$zodSchema,
};

export const tool$agentsPreviewAgentWorkflow: ToolDefinition<typeof args> = {
  name: "preview_agent_workflow",
  description: `Preview a planned workflow (dry run) without executing.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsPreviewAgentWorkflow(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
