/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetAgentRoot } from "../../funcs/agentsGetAgentRoot.js";
import { GetAgentRootRequest$zodSchema } from "../../models/getagentrootop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentRootRequest$zodSchema,
};

export const tool$agentsGetAgentRoot: ToolDefinition<typeof args> = {
  name: "get_agent_root",
  description: `Get the current MMR root for an AI agent.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsGetAgentRoot(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
