/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsVerifyAgentMmr } from "../../funcs/agentsVerifyAgentMmr.js";
import { VerifyAgentMmrRequest$zodSchema } from "../../models/verifyagentmmrop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VerifyAgentMmrRequest$zodSchema,
};

export const tool$agentsVerifyAgentMmr: ToolDefinition<typeof args> = {
  name: "verify_agent_mmr",
  description: `Verify MMR integrity for an AI agent.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsVerifyAgentMmr(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
