/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidGetEpochStats } from "../../funcs/epochsLucidGetEpochStats.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$epochsLucidGetEpochStats: ToolDefinition = {
  name: "lucid_get_epoch_stats",
  description: `Get epoch statistics.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await epochsLucidGetEpochStats(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
