/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidListEpochs } from "../../funcs/epochsLucidListEpochs.js";
import { LucidListEpochsRequest$zodSchema } from "../../models/lucidlistepochsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidListEpochsRequest$zodSchema.optional(),
};

export const tool$epochsLucidListEpochs: ToolDefinition<typeof args> = {
  name: "lucid_list_epochs",
  description: `List epochs.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await epochsLucidListEpochs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
