/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidGetAnchoringHealth } from "../../funcs/epochsLucidGetAnchoringHealth.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$epochsLucidGetAnchoringHealth: ToolDefinition = {
  name: "lucid_get_anchoring_health",
  description: `Health check for anchoring service.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await epochsLucidGetAnchoringHealth(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
