/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidListEpochsReady } from "../../funcs/epochsLucidListEpochsReady.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$epochsLucidListEpochsReady: ToolDefinition = {
  name: "lucid_list_epochs_ready",
  description: `List epochs ready for finalization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await epochsLucidListEpochsReady(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
