/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidRetryEpoch } from "../../funcs/epochsLucidRetryEpoch.js";
import { LucidRetryEpochRequest$zodSchema } from "../../models/lucidretryepochop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidRetryEpochRequest$zodSchema,
};

export const tool$epochsLucidRetryEpoch: ToolDefinition<typeof args> = {
  name: "lucid_retry_epoch",
  description: `Retry a failed epoch.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await epochsLucidRetryEpoch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
