/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { epochsLucidVerifyEpoch } from "../../funcs/epochsLucidVerifyEpoch.js";
import { LucidVerifyEpochRequest$zodSchema } from "../../models/lucidverifyepochop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidVerifyEpochRequest$zodSchema,
};

export const tool$epochsLucidVerifyEpoch: ToolDefinition<typeof args> = {
  name: "lucid_verify_epoch",
  description: `Verify an epoch anchor.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await epochsLucidVerifyEpoch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
