/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGetDetailedHealth } from "../../funcs/healthGetDetailedHealth.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$healthGetDetailedHealth: ToolDefinition = {
  name: "get_detailed_health",
  description: `Detailed health check including system resources and statistics.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await healthGetDetailedHealth(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
