/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passportsLucidListTools } from "../../funcs/passportsLucidListTools.js";
import { LucidListToolsRequest$zodSchema } from "../../models/lucidlisttoolsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidListToolsRequest$zodSchema.optional(),
};

export const tool$passportsLucidListTools: ToolDefinition<typeof args> = {
  name: "lucid_list_tools",
  description: `List active tool passports with optional filtering.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passportsLucidListTools(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
