/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passportsLucidSearchCompute } from "../../funcs/passportsLucidSearchCompute.js";
import { LucidSearchComputeRequest$zodSchema } from "../../models/lucidsearchcomputeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidSearchComputeRequest$zodSchema.optional(),
};

export const tool$passportsLucidSearchCompute: ToolDefinition<typeof args> = {
  name: "lucid_search_compute",
  description: `Search compute passports (ComputeMeta filters).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passportsLucidSearchCompute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
