/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passportsLucidUpdatePassport } from "../../funcs/passportsLucidUpdatePassport.js";
import { LucidUpdatePassportRequest$zodSchema } from "../../models/lucidupdatepassportop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidUpdatePassportRequest$zodSchema,
};

export const tool$passportsLucidUpdatePassport: ToolDefinition<typeof args> = {
  name: "lucid_update_passport",
  description: `Update an existing passport by passport_id.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passportsLucidUpdatePassport(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
