/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passportsLucidListDatasets } from "../../funcs/passportsLucidListDatasets.js";
import { LucidListDatasetsRequest$zodSchema } from "../../models/lucidlistdatasetsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidListDatasetsRequest$zodSchema.optional(),
};

export const tool$passportsLucidListDatasets: ToolDefinition<typeof args> = {
  name: "lucid_list_datasets",
  description: `List active dataset passports with optional filtering.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passportsLucidListDatasets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
