/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { receiptsLucidGetReceiptProof } from "../../funcs/receiptsLucidGetReceiptProof.js";
import { LucidGetReceiptProofRequest$zodSchema } from "../../models/lucidgetreceiptproofop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidGetReceiptProofRequest$zodSchema,
};

export const tool$receiptsLucidGetReceiptProof: ToolDefinition<typeof args> = {
  name: "lucid_get_receipt_proof",
  description: `Get the inclusion proof for a receipt.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await receiptsLucidGetReceiptProof(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
