/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { receiptsLucidVerifyReceiptByHash } from "../../funcs/receiptsLucidVerifyReceiptByHash.js";
import { LucidVerifyReceiptByHashRequest$zodSchema } from "../../models/lucidverifyreceiptbyhashop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LucidVerifyReceiptByHashRequest$zodSchema,
};

export const tool$receiptsLucidVerifyReceiptByHash: ToolDefinition<typeof args> = {
  name: "lucid_verify_receipt_by_hash",
  description: `Verify a receipt by its hash. Returns inclusion proof and on-chain anchoring status.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await receiptsLucidVerifyReceiptByHash(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
