/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runLucidChatCompletions } from "../../funcs/runLucidChatCompletions.js";
import { ChatCompletionRequest$zodSchema } from "../../models/chatcompletionrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ChatCompletionRequest$zodSchema,
};

export const tool$runLucidChatCompletions: ToolDefinition<typeof args> = {
  name: "lucid_chat_completions",
  description: `OpenAI-compatible chat completions routed through LucidLayer.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runLucidChatCompletions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
